// 초등영어 게임 95종 데이터 (원본: 「Let's play a game!」 게임 룰 모음 53쪽, 중복 통합)
// 필드: en 영문명 / ko 국문명 / aim 학습 목표 / lang 언어 기능 / lv 권장 학년 / time 권장 시간
//       form 대형 / prep 준비물 / mats 머트리얼 ID / steps 진행 / talk 교실 영어 [화자, 문장] / tips 변형·팁 / src 원본 쪽
module.exports = {
  chapters: [
    { id: 'A', title: '어휘 · 그림카드 게임', en: 'Vocabulary & Card Games', color: 'teal',
      desc: '그림카드로 낱말을 익히고 바로 써 보는 게임. 단원 도입·복습에 가장 자주 쓰입니다.' },
    { id: 'B', title: '추측 게임', en: 'Guessing Games', color: 'blue',
      desc: '정보가 가려진 상황에서 질문하고 답하며 맞히는 게임. Yes/No 의문문 연습에 최적입니다.' },
    { id: 'C', title: 'TPR · 명령어 게임', en: 'Listen & Do', color: 'orange',
      desc: '몸으로 반응하는 전신반응(TPR) 게임. 듣기 집중력과 명령문 이해를 기릅니다.' },
    { id: 'D', title: '기억 · 연쇄 말하기', en: 'Memory & Chain Games', color: 'violet',
      desc: '앞사람 말을 기억해 덧붙이거나 전달하는 게임. 반복을 통해 문장 패턴이 자동화됩니다.' },
    { id: 'E', title: '숫자 · 시간 게임', en: 'Numbers & Time', color: 'green',
      desc: '수와 시각 표현을 익히는 게임. 저학년 수 세기부터 시계 읽기까지 단계별로 쓸 수 있습니다.' },
    { id: 'F', title: '보드 · 주사위 게임', en: 'Board & Dice Games', color: 'rose',
      desc: '게임판·주사위·동전을 쓰는 짝·모둠 게임. 학생 주도 말하기 시간을 길게 확보합니다.' },
    { id: 'G', title: '대화 · 역할 놀이', en: 'Dialogue & Role-play', color: 'teal',
      desc: '인사·주문·가족 소개 등 실제 상황 대화를 놀이로 반복하는 게임.' },
  ],
  materials: [
    { id: 'M01', name: '숫자 카드 0~20', pages: 2 },
    { id: 'M02', name: '그림 단어 카드 (12주제 90장)', pages: 8 },
    { id: 'M03', name: '시계 카드 (아날로그·빈 시계·시각 문장)', pages: 3 },
    { id: 'M04', name: '빙고판 3×3 · 4×4', pages: 2 },
    { id: 'M05', name: 'Snakes and Ladders 게임판', pages: 1 },
    { id: 'M06', name: 'Twenty Boxes 게임판', pages: 1 },
    { id: 'M07', name: 'Time Grid 게임판', pages: 1 },
    { id: 'M08', name: '주사위 전개도 (빈 칸 · 음식 · 장난감)', pages: 3 },
    { id: 'M09', name: '점수표 (팀 · 짝)', pages: 1 },
    { id: 'M10', name: '표지판 (O/X · YES/NO · UP/DOWN)', pages: 3 },
    { id: 'M11', name: 'Information Gap 그림 A · B', pages: 2 },
    { id: 'M12', name: 'Board Game 섬 지도', pages: 1 },
    { id: 'M13', name: '동전 던지기 놀이판 (집→학교)', pages: 1 },
    { id: 'M14', name: '삼목 보드 · 수 찾기 숫자판', pages: 2 },
    { id: 'M15', name: 'Word Family 분류 라벨', pages: 1 },
    { id: 'M16', name: '표시해 보세요 그림', pages: 1 },
    { id: 'M17', name: '이름 쪽지 · ○× 쪽지', pages: 1 },
    { id: 'M18', name: '가면 도안', pages: 1 },
    { id: 'M19', name: 'Twenty Questions 질문 힌트 포스터', pages: 1 },
    { id: 'M20', name: 'I like / I don\'t like 얼굴판', pages: 1 },
    { id: 'M21', name: '명령어 카드 (TPR 16 · Driving 5)', pages: 3 },
    { id: 'M22', name: '식당 메뉴판', pages: 1 },
    { id: 'M23', name: '위치 전치사 카드', pages: 1 },
    { id: 'M24', name: '요일 카드', pages: 1 },
    { id: 'M25', name: '사과 개수 카드 1~10', pages: 1 },
  ],
  games: [
  // ───────────── A. 어휘 · 그림카드 ─────────────
  { ch:'A', en:'Word Family Game', ko:'단어 가족 게임', aim:'낱말을 범주(동물·과일·운동·음식)별로 분류하며 어휘망 만들기', lang:'어휘 분류', lv:'초3~4', time:'10분',
    form:'팀별 5~6명', prep:['단어·그림 카드 20~30장(팀당)','분류 주머니 또는 봉투 4~5개'], mats:['M02','M15'],
    steps:['팀마다 카드 20~30장과 분류 주머니를 나누어 준다.','교사는 칠판에 분류 기준(Animals, Fruits, Sports, Food …)을 적는다.','제한 시간(3분) 안에 카드를 기준에 맞는 주머니에 넣는다.','교사가 확인하여 맞게 분류한 카드는 +1점, 틀린 카드는 −1점.','점수가 높은 팀이 승리.'],
    talk:[['T','Put the cards in the right bag. Ready, go!'],['T','Is a banana a fruit? Yes! One point.']],
    tips:['주머니 대신 책상 위에 라벨(M15)을 놓고 분류해도 된다.','고학년은 범주를 세분화(Pets / Wild animals)해 난이도를 높인다.'], src:1 },
  { ch:'A', en:"What's missing?", ko:'없어진 카드 찾기', aim:'학습한 낱말을 기억해 말하기', lang:'어휘 회상', lv:'전학년', time:'5~10분',
    form:'전체 (대표 1명씩)', prep:['그림카드 8~10장','자석 또는 칠판 테이프'], mats:['M02'],
    steps:['그림카드로 낱말을 먼저 지도한다.','카드를 칠판 여기저기에 붙인다.','학생들이 눈을 감는 동안 카드 한 장을 몰래 뗀다.','눈을 뜨게 한 뒤 "What\'s missing?" 하고 묻는다.','빠진 카드를 먼저 말한 학생(팀)이 1점.'],
    talk:[['T','Close your eyes. … Open your eyes!'],['T',"What's missing?"],['S','The cat is missing!']],
    tips:['카드가 많을수록 어렵다. 저학년 6장, 고학년 12장.','두 장을 동시에 빼면 and를 써서 답하게 한다.'], src:9 },
  { ch:'A', en:'Memory Game 1', ko:'카드 짝 맞추기 (기억 게임)', aim:'같은 그림 두 장을 찾으며 낱말 반복 말하기', lang:'어휘 말하기', lv:'전학년', time:'10분',
    form:'전체 또는 모둠 4~6명', prep:['같은 그림카드 2벌(8~12쌍)'], mats:['M02'],
    steps:['같은 종류의 카드를 2장씩 준비해 섞은 뒤 뒷면이 보이게 놓는다.','차례가 된 학생이 2장을 뒤집으며 각각의 낱말을 영어로 말한다.','두 장이 같으면 가져가고 한 번 더, 다르면 다시 엎어 놓는다.','카드가 다 없어지면 가장 많이 가진 학생이 승리.'],
    talk:[['S','A dog … a cat. Not the same.'],['S','A pig … a pig! Same!']],
    tips:['카드를 뒤집을 때 반드시 영어로 말해야 가져갈 수 있다는 규칙을 둔다.','그림–단어 카드 짝(그림 1장 + 글자 1장)으로 바꾸면 읽기 연습이 된다.'], src:35 },
  { ch:'A', en:'Memory Game 2', ko:'순간 기억 게임', aim:'짧게 본 카드를 기억해 영어로 쓰거나 말하기', lang:'어휘·숫자 회상', lv:'초3~6', time:'10분',
    form:'팀별 6~8명', prep:['큰 보자기(천)','숫자 카드 또는 그림카드 여러 장','종이·연필'], mats:['M01','M02'],
    steps:['팀별로 앞에 나오게 한 뒤 보자기를 들춰 카드 여러 장을 1~2초만 보여 준다.','제자리로 돌아가 본 것을 기억해 영어로 적는다.','가장 많이 기억해 발표한 팀이 승리.'],
    talk:[['T','Look carefully. One, two … cover!'],['T','What did you see?'],['S','Seven, two, ten!']],
    tips:['숫자 대신 사물 그림이나 실물을 보고 영어 단어를 말하는 게임으로 바꿀 수 있다.','보여 주는 시간을 줄이거나 카드 수를 늘려 난이도 조절.'], src:3 },
  { ch:'A', en:'Speed Game (Cards)', ko:'스피드 게임 (카드 집기)', aim:'들은 낱말에 해당하는 카드를 빠르게 찾기', lang:'듣고 식별', lv:'전학년', time:'10분',
    form:'2팀 또는 분단', prep:['낱말·그림 카드 15~20장'], mats:['M02'],
    steps:['두 팀으로 나누고 카드를 교실 바닥(또는 큰 책상) 한가운데에 펼쳐 놓는다.','팀에서 한 명씩(인원이 많으면 두 명씩) 카드 앞에 선다.','교사가 단어를 부르면 그 카드를 빨리 집는다.','카드가 다 없어질 때까지 반복, 카드를 많이 모은 팀이 승리.'],
    talk:[['T','Ready? … Elephant!'],['S','Got it! Elephant!']],
    tips:['집은 학생이 낱말을 다시 말해야 인정한다.','단어 대신 문장("I like bananas.")을 들려주고 핵심어 카드를 집게 하면 듣기 연습이 깊어진다.'], src:36 },
  { ch:'A', en:'Snap Cards', ko:'그림카드 먼저 집기', aim:'낱말을 듣고 같은 카드를 손바닥으로 먼저 덮기', lang:'듣고 식별', lv:'전학년', time:'10분',
    form:'모둠 6~8명', prep:['같은 그림카드 2벌 (모둠당)'], mats:['M02'],
    steps:['모둠별로 책상에 둘러앉는다. 카드 1벌은 그림이 보이게 책상에 펼치고, 1벌은 뒤집어 쌓아 둔다.','한 학생(또는 교사)이 더미 맨 위 카드를 집어 큰 소리로 낱말을 외친다.','펼쳐진 카드 중 해당 카드를 제일 먼저 손바닥으로 덮고 낱말을 말한 학생이 가져간다.','외친 학생이 가져간 카드는 더미 맨 아래에 넣는다. 카드가 다 없어지면 가장 많이 가진 학생이 승리.'],
    talk:[['S1','Strawberry!'],['S2','(덮으며) Strawberry!']],
    tips:['카드를 반복해서 잡은 학생이 다음 차례에 외치는 역할을 맡게 하면 모두가 말하게 된다.'], src:37 },
  { ch:'A', en:'Vocabulary Game', ko:'빨랫줄 카드 떼기', aim:'지시를 듣고 해당 그림카드를 찾아 떼기', lang:'듣고 식별 · Point to', lv:'초3~4', time:'10분',
    form:'전체 → 팀 대항', prep:['A4 크기 그림카드','고무줄(빨랫줄)·집게'], mats:['M02'],
    steps:['교사가 "Draw a cat." 식으로 지시하면 학생 전체가 그림을 그린다(워밍업).','칠판에 고무줄을 매고 집게로 그림카드를 매단다.','팀별로 한 명씩 나와 교사가 "Point to the socks." 하면 그 카드를 떼어 자기 팀에 쌓는다. 맞으면 가져간다.','한 사람이 두 번씩 하고 들어간다. 카드를 많이 모은 팀이 승리.'],
    talk:[['T','Draw a cat.'],['T','Point to the socks.'],['S','Socks!']],
    tips:['빨랫줄이 없으면 칠판에 자석으로 붙여도 된다.'], src:20 },
  { ch:'A', en:'Picture Puzzle', ko:'조각 그림 맞추기', aim:'일부만 보이는 그림을 보고 낱말 추측하기', lang:"What's this? / It's a ~", lv:'초3~4', time:'10분',
    form:'분단', prep:['큰 종이','크레용·색연필','가위·테이프'], mats:[],
    steps:['큰 종이에 학생들이 그리고 싶은 사물·동물·과일을 그린다.','그림을 가위로 4~6조각으로 자른다.','조각 하나를 칠판에 붙이고 "What\'s this?" 하고 묻는다.','정답이 나올 때까지 조각을 한 장씩 더 붙이며 묻는다.'],
    talk:[['T',"What's this?"],['S',"It's a … tiger?"],['T','Not yet! One more piece.']],
    tips:['아직 배우지 않은 단어는 우리말로 답해도 되며, 교사가 그림을 미리 준비해도 좋다.','M02 카드를 확대 복사해 잘라 써도 된다.'], src:28 },
  { ch:'A', en:'Collect Three Foods', ko:'음식 카드 모으기 놀이', aim:'Do you like ~? 로 묻고 카드 교환하기', lang:'Do you like ~? / Yes, I do. / No, I don\'t.', lv:'초3~4', time:'10분',
    form:'전체 (돌아다니기)', prep:['음식 카드 3종류 × 학생 수'], mats:['M02'],
    steps:['모든 학생에게 같은 종류의 음식 카드 3장씩 나누어 준다.','돌아다니며 자기 카드의 음식 이름을 넣어 묻는다. "Do you like hamburgers?"','질문받은 학생이 햄버거 카드를 갖고 있으면 "No, I don\'t." 하고 바꾸지 않는다.','갖고 있지 않으면 "Yes, I do." 하고 카드를 바꾼다.','서로 다른 종류 3장을 먼저 모은 학생이 승리.'],
    talk:[['S1','Do you like pizza?'],['S2',"Yes, I do. (카드 교환)"],['S2',"No, I don't. (교환 없음)"]],
    tips:['음식 종류는 교사가 가르쳐 주거나 우리 전통 음식(bibimbap, kimchi)을 써도 좋다.'], src:33 },
  { ch:'A', en:'Card Collecting', ko:'카드 놀이 (Can I have ~?)', aim:'공손히 요청하고 응답하기', lang:'Can I have a ~? / Yes. / No, I haven\'t.', lv:'초4~6', time:'10분',
    form:'모둠 4명', prep:['그림카드 4종류 × 4장(모둠당 16장)'], mats:['M02'],
    steps:['모둠 리더가 카드를 섞어 각자 4장씩 나누어 준다.','차례대로 다른 학생에게 필요한 카드를 요청한다. "Can I have a pencil?"','갖고 있으면 "Yes, here you are." 하고 건넨다. 없으면 "No, I haven\'t."','필요 없는 카드는 다른 학생에게 넘긴다.','같은 종류 4장을 먼저 모은 학생이 승리.'],
    talk:[['A','Can I have a pencil?'],['B',"Yes, here you are. / No, I haven't."],['A','Thank you.'],['B',"You're welcome."]],
    tips:['Go Fish 방식. 2인 1조로 같은 카드를 만들어 시작해도 된다.'], src:49 },
  { ch:'A', en:'Find Your Sport', ko:'그림 짝 맞추기 놀이 (운동)', aim:'좋아하는 운동을 묻고 같은 짝 찾기', lang:'Do you like soccer? / Let\'s play ~.', lv:'초4~6', time:'10분',
    form:'분단', prep:['운동용구 그림 쪽지 (학생 수만큼, 2장씩 같은 그림)','바구니'], mats:['M02'],
    steps:['교사는 축구공·야구방망이·라켓 등 운동 그림을 학생 수에 맞게 2장씩 그려 접어 바구니에 넣는다.','학생들은 한 장씩 뽑은 뒤 자기와 같은 운동 그림을 가진 짝을 질문하며 찾는다.','짝을 찾으면 둘이 교사에게 종이를 제출하고 "Let\'s play soccer." 하며 어깨동무하고 돌아간다.'],
    talk:[['S1','Do you like soccer?'],['S2',"Yes, I do. / No, I don't."],['S1+S2',"Let's play outside. Let's play soccer!"]],
    tips:['이미 배운 운동 이름이나 우리말처럼 쓰는 운동 이름(badminton, tennis)으로 한다.'], src:37 },
  { ch:'A', en:'I like / I don\'t like', ko:'자기 표현하기', aim:'얼굴 표정 그림을 보고 좋고 싫음 말하기', lang:'I like ~. / I don\'t like ~.', lv:'초3~4', time:'5~10분',
    form:'모둠', prep:['얼굴판 A(군침 흘리는 얼굴)·B(찡그린 얼굴)','음식 그림카드'], mats:['M20','M02'],
    steps:['얼굴판 A와 B를 책상에 놓는다.','교사(또는 리더)가 음식 카드를 A 또는 B 아래에 놓는다.','A 아래면 "I like pizza.", B 아래면 "I don\'t like pizza." 라고 말한다.','차례대로 카드를 놓고 말하기를 반복한다.'],
    talk:[['T','(A 아래 놓으며)'],['S','I like ice cream.'],['T','(B 아래 놓으며)'],['S',"I don't like carrots."]],
    tips:['학생이 직접 카드를 놓고 자기 취향을 말하게 하면 진짜 자기 표현이 된다.'], src:50 },
  { ch:'A', en:'Catch Ball Game', ko:'공 잡기 게임', aim:'자기 카드의 낱말을 듣고 재빨리 반응하기', lang:'듣고 식별', lv:'전학년', time:'10분',
    form:'전체 (원형)', prep:['같은 그림카드 2장씩 (학생 수만큼)','부드러운 공'], mats:['M02'],
    steps:['같은 그림카드(숫자·과일·동물 등)를 2장씩 학생들에게 나누어 준다.','교사가 "Bear!" 하고 외치며 공을 위로 던지면 곰 카드를 가진 두 학생이 빨리 일어나 공을 잡는다.','공을 못 잡은 학생은 자리에 앉는다(탈락).','공을 잡은 학생이 다른 낱말을 부르며 공을 올려 게임을 계속한다.'],
    talk:[['T','Bear!'],['S','(공을 잡고) Rabbit!']],
    tips:['탈락 대신 점수제로 바꾸면 모두가 끝까지 참여한다.','안전을 위해 가볍고 큰 공을 쓴다.'], src:13 },
  { ch:'A', en:'Animal Card Game', ko:'동물 카드 게임', aim:'Are you a ~? 에 자기 카드를 보고 답하기', lang:'Are you a cat? / Yes. / No.', lv:'초3~4', time:'5분',
    form:'모둠 4명', prep:['동물 카드 4장(개·고양이·소·말)'], mats:['M02'],
    steps:['교사와 학생 4명이 원을 만든다. 동물 카드 4장을 각자 앞에 1장씩 엎어 놓는다.','학생은 자기 카드만 확인한다.','교사가 한 사람씩 "Are you a cat?" 하고 묻고 학생은 자기 카드에 따라 답한다.','학생끼리 서로 묻고 답하게 확장한다.'],
    talk:[['T','Are you a cat?'],['S1','No.'],['T','Are you a dog?'],['S1',"Yes, that's right."]],
    tips:['카드를 바꿔 여러 번 하고, 익숙해지면 I\'m a ~. 로 스스로 밝히게 한다.'], src:46 },
  { ch:'A', en:'Guess My Color', ko:'색깔 알아 맞히기', aim:'좋아하는 색을 Do you like ~? 로 묻고 맞히기', lang:'What color do I like? / Do you like blue?', lv:'초3~4', time:'5~10분',
    form:'짝 · 분단', prep:['종이·연필','색깔 카드(선택)'], mats:['M02'],
    steps:['한 학생이 앞에 나와 좋아하는 색을 종이에 몰래 적는다.','"Guess, what color do I like?" 하고 묻는다.','학생들이 "Do you like blue?" 식으로 묻고, 앞 학생은 Yes/No로 답한다.','정답을 맞힌 학생이 다음 출제자가 된다.'],
    talk:[['S1','Guess, what color do I like?'],['S2','Do you like blue?'],['S1',"No, I don't."],['S2','Do you like red?'],['S1','Yes, I do!']],
    tips:['색 대신 과일·동물로 바꾸면 어떤 단원에도 쓸 수 있다.'], src:48 },
  { ch:'A', en:"What's this? (Team Quiz)", ko:'카드 뽑아 묻기', aim:'카드를 뽑아 묻고 팀 대항으로 답하기', lang:"What's this? / It's a ~.", lv:'초3~4', time:'10분',
    form:'A·B 2팀', prep:['그림카드 20장','상자 또는 바구니'], mats:['M02'],
    steps:['그림카드를 상자에 넣는다.','A·B팀에서 1명씩 나와 선다.','A팀 학생이 카드를 뽑아 B팀 학생에게 "What\'s this?" 하고 묻는다.','B팀 학생이 "It\'s a ~." 로 답하면 1점. 역할을 바꾸어 번갈아 한다.','많이 맞힌 팀이 승리.'],
    talk:[['A',"What's this?"],['B',"It's a ruler."]],
    tips:['답을 못 하면 자기 팀원이 도와줄 수 있게 하되 점수는 절반만 준다.'], src:25 },

  // ───────────── B. 추측 게임 ─────────────
  { ch:'B', en:'Twenty Questions', ko:'스무고개', aim:'Yes/No 의문문으로 특징을 좁혀 물건 맞히기', lang:'Is it ~? / Yes. / No.', lv:'초4~6', time:'10~15분',
    form:'2팀', prep:['상자','작은 물건 여러 개(과일·학용품·칫솔·비누 등)','질문 힌트 포스터'], mats:['M19'],
    steps:['교사는 상자에 작은 물건을 넣어 준비하고, 아이들이 궁금해하도록 흔들어 보인다.','두 팀이 번갈아 질문한다. 20번 안에 맞혀야 한다는 것을 알려 준다.','교사는 상자에 손을 넣어 물건 하나를 쥐고 "What\'s in the box?" 로 시작한다.','학생들은 색·모양·크기·재료·장소·용도를 Yes/No 의문문으로 묻는다.','대답은 Yes, No로만 한다. 모든 학생에게 질문 기회를 준다. 먼저 맞힌 팀이 승리.'],
    talk:[['T',"What's in the box?"],['S1','Is it red?'],['S2','Is it big?'],['S3','Is it made of plastic?'],['S4','Can you eat it?'],['S5','Is it an apple?']],
    tips:['M19 포스터를 칠판에 붙여 질문 틀을 보여 주면 저학년도 참여할 수 있다.','질문 횟수를 칠판에 바를 정(正)자로 세어 긴장감을 준다.'], src:1 },
  { ch:'B', en:"What's in the box? (Leader)", ko:'상자 속 물건 맞히기', aim:'리더가 집은 물건을 색·이름 질문으로 맞히기', lang:"What's in the box? / Is it red? / Is it an apple?", lv:'초3~4', time:'10분',
    form:'전체 → 팀 6~7명', prep:['상자','과일·학용품·그림카드·옷 등'], mats:['M02'],
    steps:['리더(교사 또는 학생)가 상자 속 물건 하나를 집어 들고(보이지 않게) 묻는다.','학생들은 먼저 색을 묻고, 그다음 이름을 묻는다.','물건 이름을 완전히 맞힌 학생이 다음 리더가 되어 다시 시작한다.'],
    talk:[['S1',"What's in the box?"],['S2','Is it red / yellow?'],['S1','Yes.'],['S3','Is it an apple?'],['S1',"Yes! You're right."]],
    tips:['색 질문 → 이름 질문의 2단계 규칙을 지키게 하면 형용사·명사가 함께 연습된다.'], src:18 },
  { ch:'B', en:'Magic Basket', ko:'요술 바구니', aim:'눈 감고 꺼낸 물건에 대해 묻고 답하기', lang:"What's this? / Is this a pencil?", lv:'초3~4', time:'10분',
    form:'전체 또는 팀', prep:['바구니','과일·학용품 등 물건 10개 내외'], mats:['M02'],
    steps:['학생 한 명이 앞으로 나와 눈을 감고 바구니에서 물건을 하나 꺼낸다.','물건을 등 뒤에 감춘 채 학생들에게 "What\'s this?" 하고 묻는다.','학생들이 "Is this a pencil?" 로 묻고 꺼낸 학생은 Yes/No로 답한다.','맞힌 학생이 다음 리더가 되어 다시 시작한다.'],
    talk:[['S1',"What's this?"],['S2','Is this a pencil?'],['S1','No.'],['S3','Is this an eraser?'],['S1','Yes!']],
    tips:['원본 자료에서는 Action Chains 제목 아래 실려 있던 내용으로, 내용에 맞게 Magic Basket으로 정리했다.'], src:17 },
  { ch:'B', en:'Dipping Game', ko:'상자에서 꺼내기', aim:'꺼낸 물건을 This is a(n) ~. 로 말하거나 묻고 답하기', lang:'This is a(n) ~. / Is it a ~? / Yes, it is. / No, it isn\'t.', lv:'초3~4', time:'10분',
    form:'분단 (4~6명)', prep:['상자','그림카드 또는 실물'], mats:['M02'],
    steps:['상자 속에 그림카드나 실물을 넣는다.','하나를 꺼내어 "This is a(n) …." 라고 말한다. (또는 다른 학생이 "Is this a dog?" 로 묻고 Yes/No로 답한다.)','학용품을 넣은 경우: 교사가 "What\'s this?" 하고 학생들이 "Is it a pencil?" 로 추측한다.','답을 맞히면 그 카드(물건)를 갖고, 틀리면 다시 넣어 둔다. 많이 가진 사람이 승리.'],
    talk:[['S2','Is this a dog?'],['S1',"Yes, it is. / No, it isn't. It's a cat."],['T',"What's this?"],['S','Is it a notebook?'],['T',"Yes, that's right."]],
    tips:['4~6명씩 그룹을 지어 돌아가면서 해도 된다.'], src:42 },
  { ch:'B', en:'Guess What?', ko:'몸짓으로 맞히기', aim:'몸짓을 보고 동물·사물 이름 말하기', lang:'어휘 말하기', lv:'전학년', time:'10분',
    form:'A·B 2팀', prep:['동물·의복·학용품·과일 그림카드'], mats:['M02'],
    steps:['A·B 팀으로 나누고 각 팀에서 2명씩 나온다.','각 팀 1명에게 그림카드를 한 장씩 주고, 자기 팀이 알아맞힐 수 있게 몸짓으로 설명한다.','동물은 동물 흉내, 의복·물건은 용도나 생김새를 흉내 낸다.','빨리 알아맞히는 팀이 승리.'],
    talk:[['T','No talking! Just act.'],['S',"Is it a monkey? / It's a monkey!"]],
    tips:['제한 시간 30초를 두고 모래시계나 타이머를 쓰면 긴장감이 생긴다.'], src:16 },
  { ch:'B', en:'Mime Game', ko:'직업 무언극 게임', aim:'몸짓을 보고 직업 이름 맞히기', lang:'직업 어휘 / He is a ~.', lv:'초4~6', time:'10분',
    form:'전체 또는 팀 5~6명', prep:['직업 그림카드'], mats:['M02'],
    steps:['교사가 각 팀 주장에게 직업 카드를 보여 주고, 주장은 몸짓으로 설명한다.','직업을 먼저 맞힌 학생이 많은 팀이 승리.'],
    talk:[['T','What is he? / What does he do?'],['S',"He's a doctor! / A cook!"]],
    tips:['교사가 직접 여러 직업을 몸짓으로 설명하고 아동이 맞히게 할 수도 있다.','고학년은 "I want to be a ~." 로 확장한다.'], src:4 },
  { ch:'B', en:'Who am I?', ko:'동물 흉내 삼목 빙고', aim:'동물 흉내를 보고 Are you a ~? 로 묻기 + 삼목 전략', lang:"I'm (어흥). / Are you a tiger? / Yes.", lv:'초3~4', time:'15분',
    form:'2팀 (팀당 4~6명)', prep:['삼목 보드(3×3)','마커 2가지(사과·별 등)'], mats:['M14','M02'],
    steps:['스케치북(또는 M14)에 3×3 빙고판을 그리고 팀 상징(A팀 사과, B팀 별)을 정한다.','가위바위보(Rock, Scissors, Paper)로 먼저 할 팀을 정한다.','이긴 팀이 함께 모여 동물 동작을 정한 뒤 진 팀 앞에 나란히 서서 "I\'m (울음소리)." 하고 흉내 낸다.','진 팀이 "Are you a tiger?" 하고 묻는다. 맞히지 못하면 기회가 상대에게 넘어간다.','맞히면 이긴 팀이 "Yes" 하고, 맞힌 팀이 빙고판에 자기 상징을 그린다.','한 줄로 연속 3개를 먼저 만든 팀이 승리.'],
    talk:[['A팀',"I'm … (어흥!)"],['B팀','Are you a tiger?'],['A팀',"Yes! / No, I'm not."]],
    tips:['삼목 보드는 M14를 쓰거나 칠판에 그린다.'], src:10 },
  { ch:'B', en:'Guessing Game 1', ko:'동물 소리 맞히기', aim:'동물 울음소리를 듣고 동물 이름 말하기', lang:'What am I? / You are a ~.', lv:'초3~4', time:'5분',
    form:'전체', prep:['없음'], mats:[],
    steps:['교사가 동물 소리를 흉내 내며 "What am I?" 하고 묻는다.','학생들이 "You are a pig." 처럼 답한다.','학생이 출제자가 되어 이어 간다.'],
    talk:[['T','Oink oink. What am I?'],['S1','You are a pig.'],['T','Meow meow. What am I?'],['S2','You are a cat.']],
    tips:['영어 의성어(oink, meow, moo, woof, quack, baa)를 함께 가르치면 재미가 배가된다.'], src:42 },
  { ch:'B', en:'Guessing Game 2', ko:'연필 숨기기', aim:'누가 물건을 가졌는지 추측해 말하기', lang:'You have the pencil, ~. / Yes. / No.', lv:'초3~4', time:'5~10분',
    form:'모둠 5~6명', prep:['연필 1자루 (모둠당)'], mats:[],
    steps:['교사가 연필 한 자루를 5~6명 모둠에게 준다.','학생 중 한 명이 연필을 몸 뒤로 숨기고, 나머지도 갖고 있는 것처럼 행동한다.','교사(또는 술래)가 "You have the pencil, Minho." 하고 추측하면 해당 학생이 Yes/No로 답한다.','맞힐 때까지 반복. 교사 대신 학생이 술래를 해도 된다.'],
    talk:[['T','You have the pencil, Minho.'],['Minho','No.'],['T','You have the pencil, Su-mi.'],['Su-mi','Yes!']],
    tips:['고학년은 "Do you have the pencil?" 의문문으로 바꾼다.'], src:43 },
  { ch:'B', en:'What do I have?', ko:'잠깐 보고 맞히기', aim:'짧게 본 그림을 기억해 추측하기', lang:'What do I have? / An apple?', lv:'초3~4', time:'5~10분',
    form:'전체 또는 모둠', prep:['그림카드'], mats:['M02'],
    steps:['교사가 과일 그림카드를 아주 짧은 시간 보여 준 뒤 감춘다.','"What do I have?" 하고 묻는다.','학생들이 "An apple?" 식으로 추측하고 교사는 Yes/No로 답한다.'],
    talk:[['T','What do I have?'],['S1','An apple?'],['T','No.'],['S2','An orange?'],['T',"Yes, that's right."]],
    tips:['카드 2장을 동시에 보여 주면 and 표현("An apple and a banana?")을 연습할 수 있다.'], src:44 },
  { ch:'B', en:"What's it?", ko:'구멍 카드 · 가방 속 맞히기', aim:'일부만 보이는 그림이나 물건을 추측하기', lang:"What's in the bag? / It's a robot in the bag.", lv:'초3~4', time:'10분',
    form:'모둠', prep:['그림카드','구멍 뚫린 덮개 카드','가방'], mats:['M02'],
    steps:['그림카드 위에 구멍만 뚫린 카드를 겹쳐 붙여 보여 주고 추측하게 한다. "We have a mystery game."','(변형) 학생의 눈을 가린 채 자를 상자 밑에 놓고 만져서 추측하게 한다.','(변형) "What\'s in the bag?" 가방 안 물건을 약간만 보여 주고 추측하게 한다.'],
    talk:[['T',"What's it?"],['S',"It's a robot!"],['T',"What's in the bag?"],['S',"It's a robot in the bag."]],
    tips:['몸의 각 부분이나 물체 등에 응용할 수 있다.','덮개 카드는 색지 가운데에 지름 2cm 구멍을 뚫어 만든다.'], src:30 },
  { ch:'B', en:"What is it? (House)", ko:'무엇일까요? (집 평면도)', aim:'집의 방 이름을 부분 그림으로 추측하기', lang:"What's this? / It's the living room.", lv:'초4~6', time:'10분',
    form:'전체 또는 분단', prep:['집 평면도 그림','방마다 가리개 종이'], mats:[],
    steps:['집 전체 모양 그림을 준비한다. (원본은 OHP 필름을 썼으나, 종이 가리개나 태블릿 화면 확대로 대체한다.)','방 하나씩 가리개를 열어 부분을 보여 주며 "What\'s this?" 하고 묻는다.','학생들은 "It\'s the living room." 처럼 답한다.'],
    talk:[['T',"What's this?"],['S',"It's the kitchen."]],
    tips:['원본의 TP·OHP는 현재 교실에 없으므로 그림 위에 포스트잇을 붙였다 떼는 방식을 권장한다.'], src:45 },
  { ch:'B', en:'Smell Game', ko:'향기 게임', aim:'냄새로 사물을 추측해 영어로 말하기', lang:"What's this? / It's vinegar.", lv:'초3~6', time:'10분',
    form:'팀별 7~8명', prep:['종이컵 4~6개','식초·간장·사과 조각·커피·레몬 등','눈가리개'], mats:[],
    steps:['냄새를 맡을 수 있는 것을 컵에 담아 놓는다.','눈을 가리고 팀별로 1명씩 나와 냄새를 맡는다.','교사가 "What\'s this?" 하고 물었을 때 맞힌 학생에게 1점.','각 팀의 다음 학생도 같은 요령으로 하고, 가장 많이 맞힌 팀이 승리.'],
    talk:[['T',"What's this?"],['S',"It's an apple! / It's vinegar."]],
    tips:['알레르기 유무를 미리 확인하고, 자극이 강한 재료는 피한다.'], src:3 },
  { ch:'B', en:'I can see something', ko:'아이 스파이 (I spy)', aim:'색·특징 힌트를 듣고 교실 속 물건 맞히기', lang:'I can see something red. / Is it a ~? / Yes, it is.', lv:'초3~4', time:'5~10분',
    form:'모둠 또는 전체', prep:['카드나 물체 (교실 곳곳에 숨김)'], mats:['M02'],
    steps:['카드나 물건을 교실 곳곳에 숨긴다(또는 교실에 있는 물건을 그대로 쓴다).','교사가 "I can see something red." 하고 힌트를 준다.','학생들이 "Is it a sweater?" 로 추측하고 교사는 Yes/No로 답한다.','맞힌 학생이 다음 출제자가 된다.'],
    talk:[['T','I can see something red.'],['S','Is it a sweater?'],['T',"No, it isn't."],['S','Is it an apple?'],['T','Yes, it is.']],
    tips:['색 외에 big/small, long/short 힌트를 더해 형용사를 넓힌다.'], src:50 },
  { ch:'B', en:'Whisper Game', ko:'귓속말 맞히기', aim:'한 학생에게만 알려 준 물건을 질문으로 맞히기', lang:"Is it a pencil? / No, it isn't. / Yes, that's right.", lv:'초3~4', time:'5~10분',
    form:'전체 또는 모둠', prep:['없음'], mats:[],
    steps:['교사가 학생 한 명(인호)에게 작은 소리로 물건 이름("a bag")을 말해 준다.','다른 학생들이 "Is it a pencil?" 로 묻고 인호가 Yes/No로 답한다.','맞힌 학생이 다음 차례에 귓속말을 듣는 학생이 된다.'],
    talk:[['Su-mi','Is it a pencil?'],['In-ho',"No, it isn't."],['Nam-su','Is it a notebook?'],['In-ho',"No, it isn't."],['Mi-yong','Is it a bag?'],['In-ho',"Yes, that's right."]],
    tips:['범주를 미리 알려 주면(School things) 질문이 빨라진다.'], src:45 },
  { ch:'B', en:'Weather Guessing', ko:'날씨 알아 맞히기 놀이', aim:'소품·마임을 보고 날씨 표현 말하기', lang:"How's the weather? / It's sunny.", lv:'초3~4', time:'10분',
    form:'분단', prep:['우산·선글라스·장갑·모자 등 날씨 소품'], mats:['M02'],
    steps:['교사가 한 명을 대표로 불러내 귓속말로 표현할 날씨를 알려 준다.','대표 학생은 "How\'s the weather?" 하고 묻고 마임이나 소품으로 날씨를 나타낸다.','짐작한 학생은 손을 들고 "It\'s sunny." 처럼 답한다.','맞게 말한 학생이 다음 대표가 되어 계속 진행한다.'],
    talk:[['S1',"How's the weather?"],['S2',"It's rainy! (cloudy, windy, snowy, sunny)"]],
    tips:['날씨 카드(M02)를 뽑아 표현하게 하면 교사가 귓속말할 필요가 없다.'], src:27 },
  { ch:'B', en:'Where is my book?', ko:'위치 짐작하여 말하기 놀이', aim:'그림 속 물건의 위치를 전치사로 말하기', lang:"Where is my book? / It's on the desk.", lv:'초4~6', time:'10분',
    form:'분단', prep:['종이','크레용·색연필','위치 전치사 카드'], mats:['M23'],
    steps:['학생들은 좋아하는 물건·동물을 책상 위(아래), 의자 위(아래), 상자 위(아래·안) 중 한 곳에 그린다.','술래 한 명이 앞에 나오고, 자리에 앉은 학생 중 한 명을 호명해 자기 뒤에 서게 한다.','술래 뒤에 선 학생은 그림을 들어 나머지 학생에게 보여 준 뒤 술래에게 "Where is my book?" 하고 묻는다.','술래가 정답을 말하면 뒤에 선 학생이 술래가 되고, 틀리면 술래가 다른 학생을 호명해 계속한다.'],
    talk:[['S1','Where is my book?'],['술래',"It's on the desk. / It's under the chair. / It's in the box."]],
    tips:['M23 카드로 on / in / under / behind / next to 를 먼저 익힌다.'], src:33 },
  { ch:'B', en:'Hide and Seek', ko:'숨바꼭질 (위치 말하기)', aim:'숨은 친구의 위치를 전치사로 묻고 답하기', lang:'Where is ~? / Under the desk.', lv:'초3~4', time:'10분',
    form:'전체', prep:['없음'], mats:['M23'],
    steps:['교사가 "Let\'s play hide and seek." 하고 술래를 정한다.','술래가 다섯까지 세는 동안 한 학생(또는 인형)이 교실 안에 숨는다.','학생들이 "Where is Su-mi?" 하고 물으면 술래가 "Under the desk." 처럼 추측하고, 학생들은 Yes/No로 반응한다.'],
    talk:[['T',"Let's play hide and seek."],['In-ho','One … five! Ready.'],['Ss','Where is Su-mi?'],['In-ho','Under the desk.'],['Ss','No.'],['In-ho','Under the table.'],['Ss',"Yes, that's right."]],
    tips:['교실이 좁으면 인형을 숨기고 찾는 방식으로 바꾼다.'], src:43 },
  { ch:'B', en:'Ring a number', ko:'숫자 맞추기 (손에 쥔 개수)', aim:'손에 쥔 물건 수를 추측해 수 말하기', lang:'How many coins (do you have)? / Three coins.', lv:'초3~4', time:'5~10분',
    form:'짝', prep:['단추·동전·바둑알 10개 내외','짝 점수표'], mats:['M09'],
    steps:['둘씩 짝을 지어 마주 보고 앉는다.','한 사람이 단추·동전·바둑알을 보이지 않게 손에 쥐고 "How many coins?" 하고 묻는다.','맞히면 맞힌 사람이, 못 맞히면 쥔 사람이 득점한다.','3회씩 번갈아 하고 점수표에 기록한다.'],
    talk:[['S1','Jinho, how many coins do you have?'],['S2','Three coins! (= You have three.)']],
    tips:['M09 짝 점수표(Name / 1회 2회 3회 / 합계)를 쓴다.'], src:51 },
  { ch:'B', en:'Consensus', ko:'몇 개일까? (How many ~?)', aim:'숨긴 숫자 카드를 How many ~? 로 묻고 답하기', lang:'How many apples? / I have three apples.', lv:'초3~4', time:'5~10분',
    form:'분단', prep:['1~10 숫자 카드','상자'], mats:['M01'],
    steps:['1에서 10까지 쓴 숫자 카드를 상자에 넣는다.','A가 카드를 꺼내어 감추고 "How many apples?" 하고 묻는다.','B는 "I have three apples." 또는 "Three." 라고 추측한다.','B가 맞히면 B가 출제자가 되어 다시 시작한다.'],
    talk:[['A','How many apples?'],['B','I have three apples. / Three.'],['A',"Yes! / No, more."]],
    tips:['Up/Down 힌트를 주면 빨리 끝난다.','다른 낱말 그림카드와 함께 사용해 "How many dogs?" 로 바꿀 수 있다.'], src:24 },

  // ───────────── C. TPR · 명령어 ─────────────
  { ch:'C', en:'TPR Game', ko:'전신 반응 게임', aim:'명령을 듣고 즉시 몸으로 반응하기', lang:'Point to ~. / Jump ~ times. / Clap your hands.', lv:'전학년', time:'10분',
    form:'팀별 5~6명', prep:['명령어 카드(선택)'], mats:['M21'],
    steps:['팀별로 주장을 정하고, 팀원들은 주장이 명령하는 대로 행동한다.','주장이 명령할 때마다 가장 늦게 행동한 학생은 탈락한다.','마지막까지 남은 학생이 승자가 되어 다음 주장을 맡는다.','같은 요령으로 계속한다.'],
    talk:[['주장','Point to the door.'],['주장','Jump three times.'],['주장','Clap your hands twice.']],
    tips:['주장은 명령할 말을 미리 생각해 두게 한다. M21 명령어 카드를 뽑아 읽게 하면 부담이 줄어든다.'], src:2 },
  { ch:'C', en:'Commands', ko:'명령 따르기', aim:'리더의 명령을 듣고 빠르게 행동하기', lang:'Open your book. / Stand up.', lv:'전학년', time:'5~10분',
    form:'분단', prep:['명령어 카드(선택)'], mats:['M21'],
    steps:['팀별로 리더를 정한다.','리더가 명령하면 모두 행동하고, 가장 늦게 행동한 사람은 탈락한다.','맨 마지막까지 남은 사람이 다음 리더가 되어 다시 시작한다.'],
    talk:[['S1','Open your book.'],['Ss','(행동)'],['S1','Close your eyes.']],
    tips:['TPR Game의 간이형. 탈락 대신 자리에 앉혀 "심판" 역할을 주면 소외감이 없다.'], src:26 },
  { ch:'C', en:'Please Game', ko:'플리즈 게임 (Simon says)', aim:"'please'가 붙은 명령에만 반응하기", lang:'Please, stand up. / Sit down.', lv:'전학년', time:'10분',
    form:'전체', prep:['없음'], mats:['M21'],
    steps:['교사가 전체 학생을 대상으로 시작한다(다음엔 학생이 리더).','"Please, stand up." 처럼 please가 있으면 행동한다.','"Sit down." 처럼 please가 없으면 그대로 있어야 한다. 움직이면 탈락.','끝까지 남은 학생에게 상을 준다. 틀린 학생은 동물 춤을 추게 한다.'],
    talk:[['T','Please, stand up.'],['Ss','(일어선다)'],['T','Sit down.'],['Ss','(그대로 서 있는다)']],
    tips:["please 대신 'Simon says' 'Tom says'를 써도 된다.", '속도를 점점 올리면 긴장감이 커진다.'], src:25 },
  { ch:'C', en:'Opposite Game', ko:'청개구리 게임', aim:'지시와 반대되는 행동으로 명령문 이해 확인', lang:'Touch your left ear. / Don\'t sit down.', lv:'초4~6', time:'10분',
    form:'모둠 6~7명', prep:['없음'], mats:['M21'],
    steps:['교사가 영어로 지시하면 학생은 그 지시와 반대되는 행동을 한다.','한 모둠(6~7명)씩 앞으로 나오게 한다.','교사가 지시하면 반대 행동을 잘 하는지 살펴 못 하는 학생을 차례로 탈락시킨다.','마지막에 남은 학생이 승자.'],
    talk:[['T','Touch your left ear. → (오른쪽 귀를 만짐)'],['T',"Don't touch your nose. → (코를 만짐)"],['T','Raise your left hand. → (오른손을 듦)'],['T',"Don't sit down. → (앉음)"]],
    tips:['Don\'t ~ 부정 명령문 지도 후에 하면 효과가 크다.'], src:41 },
  { ch:'C', en:'Action Chains', ko:'명령 연쇄 수행', aim:'연속된 여러 지시를 기억해 순서대로 행동하기', lang:'Stand up. → Go to the desk. → Put the book on the desk.', lv:'초4~6', time:'10~15분',
    form:'2~3팀', prep:['책·연필·가방·의자·병 등 단원 주제 소품'], mats:['M21'],
    steps:['팀별로 줄을 서서 순서를 정한다.','교사는 각 팀 앞에 여러 소품을 늘어놓는다.','각 팀의 맨 앞사람이 일어나 교사의 지시 전체를 잘 듣고 그대로 움직인다.','바르게 이해하고 빠르게 행동한 팀에 점수를 주고, 팀원 모두의 점수를 합산해 순위를 정한 뒤 시상한다.'],
    talk:[['T','Stand up. Go to the desk. Put the book on the desk. Put the pencil on the book.']],
    tips:['지시 수를 2개 → 3개 → 4개로 늘려 난이도를 조절한다.','원본에는 Magic basket 제목으로도 중복 수록되어 있어 하나로 통합했다.'], src:8 },
  { ch:'C', en:'Driving Game', ko:'운전 게임', aim:'방향 명령을 신체 신호로 전달하며 이해하기', lang:'Go. / Turn right. / Turn left. / Sit down. / Stand up.', lv:'초4~6', time:'10~15분',
    form:'팀별 7~10명', prep:['눈가리개(팀원 중 맨 뒤 1명만 빼고 모두)'], mats:['M21'],
    steps:['규칙: Go→등 두드리기(전진), Turn right→오른쪽 어깨 치기, Turn left→왼쪽 어깨 치기, Sit down→머리 만지기, Stand up→엉덩이 두드리기.','맨 뒤 사람만 눈을 뜨고 나머지는 눈을 감거나 눈가리개를 한다. 왼손을 앞사람 오른쪽 어깨에 놓고 일렬로 선다.','교사가 맨 뒷사람에게 "Go." 하면 그 사람이 앞사람 등을 두드려 신호를 전달하고, 맨 앞사람까지 전달되면 앞으로 나아간다.','목표 지점에 먼저 도착한 팀이 승리.'],
    talk:[['T','Go! … Turn right! … Stand up!']],
    tips:['M21 Driving 카드로 신호 규칙을 먼저 익힌다.','안전 확보: 책상을 치우고 넓은 공간에서 천천히 진행한다.'], src:4 },
  { ch:'C', en:'This is My Shoe. Game', ko:'거꾸로 말하기 게임', aim:'술래가 가리킨 것과 말한 것을 바꾸어 즉시 답하기', lang:'This is my shoe. / This is my shirt.', lv:'초4~6', time:'10분',
    form:'전체', prep:['없음'], mats:[],
    steps:['학생들을 한 줄로 세우고 자원자 한 명이 술래가 된다.','술래는 줄을 오르내리다 한 학생을 지명한 뒤 자기 shirt를 가리키며 "This is my shoe." 라고 말한다.','지명받은 학생은 즉시 자기 shoe를 가리키며 "This is my shirt." 라고 거꾸로 답한다.','거꾸로 답하지 못한 학생이 술래가 된다.'],
    talk:[['술래','(셔츠를 가리키며) This is my shoe.'],['S','(신발을 가리키며) This is my shirt.']],
    tips:['신체 부위(nose/ear)로 바꾸면 코코코 놀이와 연결된다.'], src:15 },
  { ch:'C', en:'What day is it today?', ko:'요일 명령 게임', aim:'If + 요일 조건문을 듣고 행동하기', lang:"If it's Monday, stand up.", lv:'초4~6', time:'10분',
    form:'전체', prep:['요일이 크게 쓰인 달력 또는 요일 카드'], mats:['M24'],
    steps:['교사는 칠판에 달력(요일 카드)을 붙인다.','요일을 가리키며 "If it\'s Monday, stand up." 하고 지시한다.','가리킨 요일과 말한 요일이 맞으면 행동하고, 다르면 행동하지 않는다.','요일마다 다른 명령을 연결한다.'],
    talk:[['T',"If it's Monday, stand up."],['T',"If it's Tuesday, point to your nose."],['T',"If it's Wednesday, sit down."],['T',"If it's Thursday, sing a song. / Friday – Play basketball. / Saturday – Let's dance."]],
    tips:['"If"의 뜻을 이해시킨 후 실시한다.'], src:19 },
  { ch:'C', en:'Koko-ko Game', ko:'코코코 놀이', aim:'리더가 말한 얼굴 부위를 정확히 가리키기', lang:'Nose, nose, ears!', lv:'전학년', time:'5분',
    form:'분단', prep:['없음'], mats:[],
    steps:['교사나 학생 한 명을 뽑아 앞에서 리드하게 한다.','자기 코를 가리키며 "Nose, nose, nose…" 하다가 갑자기 다른 부위 이름을 말한다(손은 다른 곳을 가리킬 수 있음).','바꿔 말한 얼굴 부위를 제대로 가리키지 못한 학생이 리더를 맡는다.'],
    talk:[['리더','Nose, nose, nose … ears!'],['Ss','(귀를 가리킨다)']],
    tips:['eyes, mouth, chin, cheek 등으로 어휘를 넓힌다.'], src:32 },
  { ch:'C', en:'Basket Game', ko:'바구니 놀이 (Pick up)', aim:'Pick up + 물건 지시를 듣고 꺼내기', lang:'Pick up a ruler. / Pick up a pencil.', lv:'초3~4', time:'10분',
    form:'2팀', prep:['바구니 2개','학용품 여러 개'], mats:['M02'],
    steps:['두 팀으로 나눈다.','바구니 두 개에 같은 학용품을 넣고 물건 이름을 각각 말해 본다.','두 팀 대표가 나와 서로 등을 대고 선 뒤, 교사가 지시하는 물건을 바구니에서 꺼낸다.','꺼낸 물건은 다시 넣고, 맞는 사람에게 점수를 주어 많은 팀이 승리.'],
    talk:[['T','Pick up a ruler.'],['T','Pick up a pencil.']],
    tips:['교사의 시범으로 pick up의 의미를 먼저 이해시킨다.'], src:48 },
  { ch:'C', en:'Speed Game (Objects)', ko:'스피드 게임 (물건 찾기)', aim:'들은 물건을 교실에서 빨리 찾아오기', lang:'Here! / book, pencil …', lv:'전학년', time:'10분',
    form:'그룹 6~7명', prep:['교실 안 물건, 옷, 색연필, 색종이, 가위 등'], mats:[],
    steps:['한 팀을 5~6명 이내로 하여 대표를 뽑는다.','교사가 학용품을 영어로 말하면 각 팀 대표가 그 물건을 찾아낸다. 팀원들이 함께 찾아 주게 해 협동심을 기른다.','찾은 물건을 교사에게 가져간다. 인원이 많아 앞으로 나오기 힘들면 그 자리에서 "Here!" 하며 들어올린다.','빠르고 정확하게 찾은 팀에 점수.'],
    talk:[['T','Bring me a red pencil.'],['S','Here!']],
    tips:['"Bring me something blue." 처럼 색 조건을 붙여 확장한다.'], src:8 },
  { ch:'C', en:'Draw It Here', ko:'표시해 보세요', aim:'위치 지시를 듣고 그림에 표시하기', lang:'Draw a pencil on the desk.', lv:'초4~6', time:'10분',
    form:'짝 또는 팀', prep:['같은 그림 2세트(책상·얼굴·가방·의자)'], mats:['M16','M23'],
    steps:['두 사람에게 똑같은 그림을 나누어 준다.','교사가 간단히 지시하고 학생들은 잘 듣고 지시대로 그림에 표시한다.','교사의 지시대로 바르게 표시한 팀이 승리.'],
    talk:[['T','Draw a pencil on the desk.'],['T','Draw a nose on the face.'],['T','Draw two apples in the bag.'],['T','Draw a banana under the chair.']],
    tips:['짝끼리 서로 지시를 주고받으면 Information Gap 활동이 된다.'], src:9 },
  { ch:'C', en:'Drawing Race', ko:'그리기 경주', aim:'지시를 듣고 칠판에 빠르게 그리기', lang:'Draw a nose. / Draw two eyes.', lv:'초3~4', time:'5~10분',
    form:'전체 (팀 대표 4명씩)', prep:['칠판·분필(마커)'], mats:[],
    steps:['각 팀에서 4명씩 칠판 앞에 나온다.','교사가 5초 간격으로 명령하고 학생들은 지시에 따라 그린다.','제일 빨리, 정확히 그린 사람이 승리.'],
    talk:[['T','Draw a nose. … Draw a mouth. … Draw two eyes. … Draw two ears.']],
    tips:['얼굴이 완성되면 "그림 지우기 놀이"로 이어 간다.'], src:44 },
  { ch:'C', en:'Picture Drawing', ko:'그림 그리기 (칠판)', aim:'교사가 말한 낱말을 그림으로 표현하기', lang:'a face, a nose, an eye, a mouth …', lv:'초3~4', time:'5분',
    form:'모둠', prep:['칠판'], mats:[],
    steps:['3~4명의 학생이 칠판 앞에 서서 교사가 말하는 낱말의 그림을 그린다.','가장 알아보기 쉽게 그린 학생에게 박수.'],
    talk:[['T','Draw a face. Draw a nose. Draw an eye.']],
    tips:['Drawing Race의 간이형. 그릴 낱말을 학생이 부르게 하면 말하기 연습이 된다.'], src:49 },
  { ch:'C', en:'Erase the Picture', ko:'그림 지우기 놀이', aim:'신체 부위 명칭을 듣고 그리고 지우기', lang:'face, two eyes, nose, foot …', lv:'초3~4', time:'10분',
    form:'3팀 (팀별 6~7명)', prep:['칠판·분필·지우개'], mats:[],
    steps:['세 팀으로 나누어 칠판을 보고 일렬로 선다. 맨 앞사람이 분필을 든다.','칠판을 셋으로 나눈 면에 교사가 불러 주는 어휘를 듣고 그린다. "face" 하면 얼굴을, "two eyes" 하면 눈 2개를 그린다.','한 동작이 끝나면 다음 사람에게 분필을 준다.','신체 그림이 완성되면 이번에는 지우는 게임을 한다. 학생들은 칠판을 등지고 종렬로 선다.','교사가 "nose" 하면 코를 지우고 "foot" 하면 발을 지운다. 빨리, 정확히 지운 팀이 승리.'],
    talk:[['T','Face! … Two eyes! … Nose!'],['T','Erase the nose! Erase the foot!']],
    tips:['지우기 단계에서 등지고 서 있다가 돌아서게 하면 듣기 집중도가 높아진다.'], src:7 },
  { ch:'C', en:'Board Race', ko:'칠판 경주하기', aim:'낱말을 듣고 칠판으로 달려가 그리거나 카드 고르기', lang:'단원 어휘', lv:'전학년', time:'10분',
    form:'여러 팀', prep:['그림카드','칠판'], mats:['M02'],
    steps:['아동을 몇 팀으로 나누고 각 팀이 칠판을 향해 선다.','교사가 지시어나 단어를 말하면 각 팀에서 한 명이 칠판으로 달려가 해당하는 행동을 한다.','(방식 1) 교사가 말한 단어를 칠판에 그린다. (방식 2) 칠판 아래에 그림카드를 배열해 두고, 교사가 말한 대상 카드를 골라 든다.','옳은 반응을 한 팀에 1점. 많은 점수를 얻은 팀이 승리.'],
    talk:[['T','Rabbit!'],['S','(카드를 들며) Rabbit!']],
    tips:['달리기 안전을 위해 출발선과 칠판 사이 장애물을 치운다.'], src:40 },
  { ch:'C', en:'Make a mask', ko:'가면 만들기', aim:'지시를 들으며 가면을 만들고 역할놀이로 묘사하기', lang:'Draw an ear and color it. / You have a red nose.', lv:'초3~6', time:'20분',
    form:'모둠', prep:['도화지(가면 도안)','색연필·가위','막대(나무젓가락)·테이프'], mats:['M18'],
    steps:['도화지에 교사의 지시에 따라 그림을 그린다. "Draw an ear and color it." 완성되면 뒤에 막대를 붙인다.','역할놀이: "Put on your face." 가면을 쓰고 짝과 서로 묘사한다. "You have a red nose, black mouth…"','"How many mouths can you see?" "Describe your partner\'s mask." 등으로 확장한다.'],
    talk:[['T','Draw an ear and color it.'],['T','Put on your face.'],['S','You have a red nose and a black mouth.'],['T','Tape your pencil to your mask.']],
    tips:['M18 가면 도안을 쓰면 눈 위치가 맞아 바로 쓸 수 있다.'], src:47 },
  { ch:'C', en:'Whisper Command', ko:'귓속말 전하기 (명령)', aim:'귓속말로 전달된 명령을 마지막 사람이 수행하기', lang:'Stand up, 민호.', lv:'초3~4', time:'10분',
    form:'4분단', prep:['없음'], mats:['M21'],
    steps:['아동들을 4분단으로 나누고 각 분단 맨 앞 학생에게 귓속말로 지시 내용을 알려 준다.','학생들은 자기 뒤 학생에게 귓속말로 내용을 전달한다.','맨 끝 학생이 전달받은 말을 크게 말하면, 그 지시문에 해당하는 학생이 그에 따라 행동한다.'],
    talk:[['T','(아동1에게 귓속말) Stand up, 민호.'],['아동1','(아동2에게 귓속말) Stand up, 민호.'],['마지막 아동','(크게) Stand up, 민호!'],['민호','(일어선다)']],
    tips:['정확히 전달된 분단에 1점. 명령에 이름을 넣어 듣는 사람 모두가 집중하게 한다.'], src:29 },
  { ch:'C', en:"Champion's chair", ko:'챔피언 의자 (Yes/No)', aim:'문장이 참인지 거짓인지 듣고 판단하기', lang:'I have two eyes. (Yes) / I have one nose. (Yes)', lv:'초3~4', time:'10분',
    form:'청·백 2팀', prep:['의자 2개','YES / NO 표지'], mats:['M10'],
    steps:['YES, NO 표지를 의자 2개에 각각 붙인다.','청·백으로 나누어 마주 보고 서고, 선수를 한 명씩 낸다.','두 선수는 의자를 중심으로 빙글빙글 돈다.','교사가 말한 내용이 사실이면 YES 의자에, 사실이 아니면 NO 의자에 먼저 앉는 쪽에 1점.'],
    talk:[['T','I have two eyes. → YES'],['T','I have three noses. → NO']],
    tips:['M10 YES/NO 표지 사용. 문장은 단원 내용(동물 특징, 날씨 등)으로 바꾼다.'], src:52 },
  { ch:'C', en:'O, X Game', ko:'O X 게임', aim:'교사의 말과 동작이 일치하는지 판단해 이동하기', lang:'듣고 판단', lv:'전학년', time:'10분',
    form:'팀별 5~6명', prep:['O · X 표지판'], mats:['M10'],
    steps:['O 지역과 X 지역을 교실의 적당한 곳에 표시한다.','아동들을 조별로 나누어 1명씩 차례로 참가한다.','교사의 말과 동작이 일치하면 O, 일치하지 않으면 X 지역으로 이동한다.','맨 마지막까지 남은 아동들에게 점수. 가장 많은 점수를 얻은 조가 승리.'],
    talk:[['T','(코를 만지며) I touch my nose. → O'],['T','(귀를 만지며) I touch my nose. → X']],
    tips:['야외 학습장이나 운동장에서는 모든 조원이 한꺼번에 참여할 수 있다.'], src:14 },

  // ───────────── D. 기억 · 연쇄 말하기 ─────────────
  { ch:'D', en:'Snowball Game', ko:'눈덩이 게임', aim:'앞사람의 낱말을 기억해 하나씩 덧붙여 말하기', lang:'Apples, bananas and pears.', lv:'초3~4', time:'10분',
    form:'팀별 4~5명', prep:['그림카드(힌트용, 선택)'], mats:['M02'],
    steps:['4~5명씩 짝을 짓는다.','한 학생이 과일 이름이나 동물 이름 하나로 시작한다. "Apples."','다음 학생은 앞말에 새로운 낱말을 하나 덧붙인다. "Apples and bananas."','같은 방법으로 계속한다. 틀리면 처음부터 다시 시작한다.'],
    talk:[['S1','Apples.'],['S2','Apples and bananas.'],['S3','Apples, bananas and pears.']],
    tips:['and 의 위치(마지막 항목 앞)를 자연스럽게 익히게 된다.'], src:6 },
  { ch:'D', en:'Memory chain', ko:'문장 눈덩이 (I want ~)', aim:'문장 속 목적어를 기억해 이어 붙이기', lang:'I want a doll, a robot and a car.', lv:'초3~4', time:'10분',
    form:'분단 (3~4명)', prep:['그림카드'], mats:['M02'],
    steps:['3~4명이 둘러앉는다.','단원에 알맞은 낱말의 그림카드를 보며 말한다.','S1 "I want a doll." → S2 "I want a doll and a robot." → S3 "I want a doll, a robot and a car."','순서를 바꾸어 가며 놀이한다.'],
    talk:[['S1','I want a doll.'],['S2','I want a doll and a robot.'],['S3','I want a doll, a robot and a car.']],
    tips:['I like ~ / I have ~ / I can see ~ 등 단원 패턴으로 바꿔 쓴다.'], src:21 },
  { ch:'D', en:'Add-on Game', ko:'문장 확장 게임', aim:'한 문장을 자기가 아는 표현으로 한마디씩 확장하기', lang:'문장 확장', lv:'초5~6', time:'10분',
    form:'팀별 5~6명', prep:['없음'], mats:[],
    steps:['교사가 한 문장을 말한다. "I have a dog."','학생들은 차례로 아는 지식을 동원해 한마디씩 확대하여 말한다.','"I have a big dog." → "I have a big black dog." → "I have a big black dog in my house."'],
    talk:[['T','I have a dog.'],['S1','I have a big dog.'],['S2','I have a big black dog.'],['S3','I have a big black dog in my house.']],
    tips:['형용사 → 장소 → 시간 순으로 확장 힌트를 주면 어순 감각이 생긴다.'], src:15 },
  { ch:'D', en:'Whisper Chain', ko:'귓속말 숫자 릴레이', aim:'숫자를 귓속말로 정확히 전달하고 칠판에 쓰기', lang:'숫자 듣고 말하기', lv:'전학년', time:'10분',
    form:'일렬 또는 원형 (팀별 7~8명)', prep:['숫자 카드'], mats:['M01'],
    steps:['각 팀의 1번 학생이 앞으로 나온다.','교사는 숫자가 적힌 카드를 1번 학생들에게만 보여 준다.','1번 학생은 자기 팀에 돌아가 다음 학생에게 귓속말로 영어로 숫자를 말해 준다.','맨 마지막 학생이 앞으로 나와 칠판에 숫자를 적는다.','가장 빨리 정확하게 전달한 팀이 승리.'],
    talk:[['T','(카드 17을 보여 주며) Remember the number. Go!'],['S1','(귓속말) Seventeen.'],['마지막 S','(칠판에) 17!'],['T',"Team Apple, seventeen. That's right!"]],
    tips:['인원이 많으면 몇 개 팀으로 나누어 각기 다른 숫자를 준다.','숫자 외에 쉬운 단어를 그림으로 보여 주고 전달하게 할 수도 있다. 수준이 향상되면 그림 상황을 문장으로 전달하게 한다.'], src:2 },
  { ch:'D', en:'Pass the word', ko:'귓속말 낱말 릴레이', aim:'단원 낱말을 귓속말로 전달하고 마지막 사람이 크게 말하기', lang:'단원 어휘 듣고 말하기', lv:'전학년', time:'10분',
    form:'2~3팀 (앞뒤로 10명 정도)', prep:['게임에 이용할 단어를 정해 놓는다 (각 단원의 단어 도입·확인)'], mats:['M02'],
    steps:['팀별로 일렬로 선다.','교사가 맨 처음 학생에게 귓속말로 낱말을 속삭여 준다. 모든 팀에 같은 단어를 준다.','계속 뒷사람에게 귓속말로 전해 준다.','맨 뒤의 학생이 크게 말하여 확인한다.','빨리 정확하게 맞힌 팀이 승리.'],
    talk:[['T','(첫 학생에게 귓속말) Elephant.'],['S','(귓속말로 전달) Elephant… elephant…'],['마지막 S','Elephant!'],['T','Yes! Team Star wins this round.']],
    tips:['단어 → 두 단어(a red apple) → 짧은 문장(I like apples.)으로 전달 단위를 늘린다.','Whisper Chain(숫자 버전)과 같은 뼈대의 게임이다.'], src:19 },
  { ch:'D', en:'Greeting Relay', ko:'반복 레이스 게임 (인사 돌리기)', aim:'시간대별 인사말을 순서대로 돌아가며 말하기', lang:'Good morning → Good afternoon → Good evening → Good night', lv:'초3~4', time:'5분',
    form:'모둠', prep:['없음'], mats:[],
    steps:['Good morning → Good afternoon → Good evening → Good night … 순서대로 한 사람씩 돌아가며 말한다.','"Good night."을 말한 사람은 자는 시늉을 하며 빠진다.','맨 나중에 남는 사람은 벌칙(노래 한 소절 등)을 받는다.'],
    talk:[['S1','Good morning.'],['S2','Good afternoon.'],['S3','Good evening.'],['S4','Good night! (잠자는 시늉)']],
    tips:['요일(Monday → Sunday)이나 숫자로 바꿔도 된다.'], src:46 },
  { ch:'D', en:'Seven Go Game', ko:'세븐 고 (리듬 숫자 게임)', aim:'3박자 리듬에 맞춰 수를 세고 7에서 명령하기', lang:'One, two, three … Go! Back! Jump!', lv:'초4~6', time:'10분',
    form:'원형 (전체)', prep:['없음'], mats:[],
    steps:['아동들은 원으로 앉아 무릎 치고, 손뼉 치고, 주먹 쥐는 3박자 율동을 연습한다.','1, 2, 3 … 차례대로 3박자에 맞추어 숫자를 말한다.','숫자 7 차례의 아동은 7 대신 Go!, Back!, Jump! 중 하나를 외친다.','Go!는 진행 방향 다음 사람, Back!은 뒷사람, Jump!는 앞의 앞 사람이 이어받아 8부터 계속한다.'],
    talk:[['Ss','One, two, three, four, five, six …'],['S7','Jump!'],['S9','Eight!']],
    tips:['7뿐 아니라 7의 배수(14, 21)에서도 명령하게 하면 Buzz Game과 결합된다.'], src:13 },
  { ch:'D', en:'Buzz Game', ko:'버즈 게임', aim:'수를 세며 특정 수의 배수에서 Buzz 외치기', lang:'One, two, Buzz, four, five, Buzz …', lv:'초4~6', time:'5~10분',
    form:'전체', prep:['없음'], mats:[],
    steps:['교사가 임의의 숫자(예: 3)를 말한다.','아동들이 차례로 숫자를 세다가 그 수의 배수마다 숫자 대신 "Buzz"라고 말한다.','틀린 학생은 탈락하거나 다시 1부터 시작한다.'],
    talk:[['T','Buzz number is three!'],['Ss','One, two, Buzz, four, five, Buzz, seven …']],
    tips:['Buzz 대신 다른 단어(단원 어휘)를 써도 좋다.','영어로 수를 20까지 자동화하는 데 효과적이다.'], src:14 },

  // ───────────── E. 숫자 · 시간 ─────────────
  { ch:'E', en:'Up and Down Game', ko:'업 앤 다운', aim:'Up/Down 힌트를 듣고 숫자 추측하기', lang:'Six. / Up! / Nine. / Down!', lv:'초3~4', time:'5~10분',
    form:'팀별 4~5명', prep:['숫자 카드','UP / DOWN 표지'], mats:['M01','M10'],
    steps:['교사가 숫자 카드 중 1장을 선택한다. (예: 7)','학생이 카드의 숫자를 짐작하여 말한다. (S1: Six.)','학생이 말한 숫자(6)가 7보다 아래이므로 교사는 "Up." 하며 팔을 위로 든다.','다른 학생이 다시 짐작한다. (S2: Nine.) 정답보다 위이므로 "Down."','Up/Down을 활용해 숫자를 맞힌다.'],
    talk:[['S1','Six.'],['T','Up!'],['S2','Nine.'],['T','Down!'],['S3','Seven!'],['T',"Yes, that's right!"]],
    tips:['M10 UP/DOWN 표지를 학생이 들게 하면 학생이 출제자가 될 수 있다.'], src:7 },
  { ch:'E', en:'Find the Number', ko:'수 찾기', aim:'들은 숫자를 칠판에서 빨리 찾아 표시하기', lang:'숫자 1~20', lv:'초3~4', time:'5~10분',
    form:'전체 (팀 대표 2명)', prep:['칠판 또는 숫자판','색이 다른 분필(마커) 2개'], mats:['M14'],
    steps:['칠판에 1~10 또는 1~20의 수를 순서 없이 적어 두고 두 팀 대표가 칠판을 향해 선다.','교사가 1~3개의 숫자를 잇달아 영어로 말한다.','각 팀 대표는 서로 다른 색으로 교사가 말한 숫자를 찾아 동그라미를 그린다.','칠판의 모든 숫자가 끝나면 동그라미를 많이 친 팀이 승리.'],
    talk:[['T','Eleven, four, nineteen!']],
    tips:['같은 요령으로 지우는 게임을 할 수도 있다.','M14 숫자판을 인쇄해 짝 활동으로 바꿀 수 있다.'], src:47 },
  { ch:'E', en:'Line Up by Number', ko:'숫자 따라 줄서기 놀이', aim:'How many? 로 묻고 수에 따라 순서대로 서기', lang:'How many? / One. / Ten apples.', lv:'초3~4', time:'10분',
    form:'분단 (10명)', prep:['사과 1~10개 그린 종이 10장'], mats:['M25'],
    steps:['10명을 한 조로 구성한다.','10장의 종이에 사과를 1개부터 10개까지 그린 후 접는다(M25 사용).','각 조원은 종이를 한 장씩 집어 서로에게 개수를 묻는다.','사과 개수에 따라 일렬로 늘어선다.','제대로 늘어서면 다 함께 개수를 말하고 자리로 돌아간다.'],
    talk:[['아동1','How many?'],['아동2','One.'],['Ss','One, two, … ten. Ten apples!']],
    tips:['사과 대신 이미 배운 사물의 이름을 활용해도 좋다.'], src:30 },
  { ch:'E', en:'How old are you?', ko:'나이 묻고 답하기', aim:'숫자 카드를 보고 나이를 묻고 답하기', lang:"How old are you? / I'm nine.", lv:'초3~4', time:'5~10분',
    form:'분단', prep:['숫자 카드 2벌','바구니'], mats:['M01'],
    steps:['숫자 카드를 2벌씩 준비하여 팀별로 바구니에 넣는다.','팀 리더가 나와 카드를 한 장씩 꺼내어 보여 주며 묻는다.','답한 학생이 다음 카드를 꺼내 묻는다.','다음 리더가 나와 다시 시작한다.'],
    talk:[['S1','(카드 9를 보이며) How old are you?'],['S2',"I'm nine. (카드 7을 보이며) How old are you?"],['S1',"I'm seven."]],
    tips:['실제 나이로 바꿔 "I\'m ten years old." 까지 확장한다.'], src:26 },
  { ch:'E', en:'Draw the Clock', ko:'시계그리기 놀이', aim:'시각을 듣고 시계 바늘 그리기', lang:"It's ten. / It's seven. / Breakfast time.", lv:'초3~4', time:'10분',
    form:'짝', prep:['빈 시계 카드','색연필'], mats:['M03'],
    steps:['2명씩 짝을 짓는다.','각자 시계판을 그린다(또는 M03 빈 시계 카드 사용).','한 사람이 시각을 말하면 짝은 시계 카드에 바늘을 그려 넣는다.','두 학생이 번갈아 한다.'],
    talk:[['S1',"It's ten."],['S2','(바늘 그리기)'],['S1',"It's seven."],['S2','Breakfast time!']],
    tips:['"It\'s seven / twelve / six." 라고 말하면 그리는 학생이 "Breakfast time / Lunch time / Dinner time." 이라고 덧붙이게 한다.'], src:5 },
  { ch:'E', en:'Time Matching', ko:'짝 맞추기 게임 (시각 카드)', aim:'시각 문장 카드와 시계 그림 카드를 짝 맞추기', lang:"What time is it? / It's three o'clock.", lv:'초3~4', time:'15분',
    form:'2팀', prep:['시각 문장 카드(번호)','시계 카드(알파벳)','자석'], mats:['M03'],
    steps:['칠판 왼편에 시각이 적힌 카드(번호)를, 오른편에 시계 카드(알파벳)를 뒷면이 보이게 붙인다.','두 팀이 번갈아 한다. 자기 팀 차례에 한 명이 번호를 부른다. (예: 7번 seven)','그 학생이 7번 카드를 뒤집어 보이며 "What\'s the time?" 하고 물으면, 모두 함께 답한 뒤 한 명이 시계 카드에 시각을 그려 넣고 앞면으로 붙인다.','모든 시계 카드에 바늘을 그려 넣으면 다시 뒷면으로 돌린다.','팀별로 시각 카드 번호와 시계 카드 알파벳을 동시에 부른다. (예: 3번, E)','두 카드가 일치하면 점수를 주고 앞면이 보이게 붙여 둔다. 일치하지 않으면 다시 뒤집는다. 모든 카드가 짝지어질 때까지 계속한다.'],
    talk:[['S','Number seven!'],['S',"What time is it?"],['Ss',"It's seven o'clock."],['S','Number three, E!']],
    tips:['M03의 아날로그 시계 카드와 시각 문장 카드를 각각 번호·알파벳 라벨을 붙여 사용한다.'], src:11 },
  { ch:'E', en:'Clock Bingo', ko:'시계 빙고 놀이', aim:'What time is it? 로 묻고 들은 시각으로 빙고 완성하기', lang:"What time is it? / It's ~ o'clock.", lv:'초3~4', time:'10분',
    form:'전체', prep:['종이·연필 또는 3×3 빙고판'], mats:['M04'],
    steps:['가로·세로 3칸씩 9칸으로 된 빙고판을 그린다(M04).','1부터 12까지의 숫자 중 임의로 9개를 골라 빙고판에 쓴다.','학생들이 교사에게 "What time is it?" 하고 물으면 교사는 "It\'s ~ o\'clock." 하고 답한다.','교사가 말한 시각을 찾아 ×표 한다. 가로·세로·대각선 한 줄이 완성되면 "Bingo!"를 외친다.'],
    talk:[['Ss','What time is it?'],['T',"It's five o'clock."],['S','Bingo!']],
    tips:['교사 대신 학생이 시각을 부르게 하면 말하기 연습이 된다.'], src:27 },
  { ch:'E', en:'Time Grid Game', ko:'타임 그리드 게임', aim:'주사위로 이동한 칸의 시각과 하는 일 말하기', lang:"What time is it? / It's seven. / I get up.", lv:'초3~6', time:'15분',
    form:'팀별 4명', prep:['Time Grid 게임판','주사위','말'], mats:['M07'],
    steps:['4명씩 팀을 만들고, 게임판의 칸마다 시각(숫자)이 쓰여 있다(M07).','4명이 차례로 주사위를 던져 그 수만큼 이동하면, 나머지 3명이 그 칸의 시각 또는 그 시각에 하는 일을 묻는다.','대답이 맞으면 이동하고 틀리면 원래 자리로 돌아간다.','마지막 칸을 가장 먼저 통과한 학생이 승리.'],
    talk:[['Ss','What time is it?'],['S',"It's seven o'clock. I get up."]],
    tips:['3학년은 \'시\'만 나타내는 판을 이용하고, 나머지 3명은 질문하지 않고 주사위를 던진 학생이 그림에 맞는 시각을 영어로 말하는지만 판단한다.'], src:12 },
  { ch:'E', en:'Birthday Game', ko:'생일 축하 놀이', aim:'생일 축하 대화와 나이 묻기를 놀이로 반복하기', lang:"Today's my birthday. / Happy birthday! / How old are you? / I'm ~.", lv:'초3~4', time:'10분',
    form:'분단 (10명)', prep:['종이(조원 수만큼)','색연필'], mats:['M17'],
    steps:['10명을 한 조로 구성한다.','1장의 종이에는 ○표와 나이를 나타내는 숫자를 쓰고, 나머지 9장에는 ×표를 한 후 접는다(M17 쪽지 사용).','접힌 종이를 던져 각자 1장씩 집는다.','○표 종이를 집은 학생은 오늘이 자기 생일임을 알리고, 나머지는 축하한 뒤 나이를 묻는다.','대화가 끝나면 종이를 접어 놀이를 다시 시작한다.'],
    talk:[['○ 학생',"Today's my birthday."],['Ss','Happy birthday!'],['○ 학생','Thank you.'],['Ss','How old are you?'],['○ 학생',"I'm ten."]],
    tips:['생일 노래 한 소절을 함께 부르면 분위기가 살아난다.'], src:31 },

  // ───────────── F. 보드 · 주사위 ─────────────
  { ch:'F', en:'Dice Game', ko:"주사위 놀이 (It's a ~)", aim:'주사위 면의 그림을 보고 It\'s a ~. 로 말하기', lang:"It's a ~. / It's ~.", lv:'초3~4', time:'10분',
    form:'팀별 6~7명', prep:['그림 주사위','주사위 점수표'], mats:['M08','M09'],
    steps:['6명씩 한 팀을 만든다.','음식 종류를 그림으로 나타내어 주사위 각 면에 붙인다(전개도 사용).','학생 한 명이 주사위를 던지고 주사위 면에 나타난 그림을 보고 "It\'s ~." 로 말한다.','음식 이름을 정확하게 맞춘 학생은 점수표에 기록하며, 학생들에게 성취감을 갖도록 한다.'],
    talk:[['S1','(던진다) It\'s pizza!'],['T','Good! One point.'],['S2',"It's a hamburger!"]],
    tips:['주사위의 각 면에 가족 구성원 그림이나 물건 이름, 동물이나 과일 이름을 붙여 활용할 수도 있다.'], src:5 },
  { ch:'F', en:'Dice Game 2', ko:'주사위 놀이 (I like ~)', aim:'주사위 면의 그림을 보고 I like ~. 로 말하고 팀 순서 경쟁하기', lang:'I like ~.', lv:'초3~4', time:'10분',
    form:'팀 6~7명', prep:['주사위 점수표','주사위'], mats:['M08','M09'],
    steps:['여섯 명씩 한 팀을 만든다.','주사위 여섯 면에 음식이나 동물 그림을 한 장씩 붙인다.','아동 한 명이 주사위를 던져 나타난 그림을 보고 "I like apples (ice cream, bananas, cake)." 라고 말한다.','여섯 명이 전부 주사위를 던져 말하기를 끝내면 빨리 끝내는 순서대로 팀 점수를 준다.'],
    talk:[['S1','I like ice cream!'],['S2','I like bananas!'],['T','Team Star, finished! Three points.']],
    tips:['팀 전체가 빨리 끝내야 하므로 말이 막히는 친구를 팀원이 도와주게 된다. 협동이 자연스럽게 일어난다.'], src:36 },
  { ch:'F', en:"What's in the box? (Dice)", ko:'상자 속 주사위 맞히기', aim:'상자 안에서 던진 주사위의 그림을 묻고 답하기', lang:"What's in the box? / It's a ball.", lv:'초3~4', time:'10분',
    form:'모둠', prep:['장난감 그림 주사위','상자'], mats:['M08'],
    steps:['그림(train, plane, car, robot, bear, ball)이 그려진 주사위를 학생이 직접 만든다(M08).','주사위를 상자 안에 넣어 던진다.','나온 그림을 가리키며 "What\'s in the box?" 하고 묻고 "It\'s a ball." 로 답한다.'],
    talk:[['S1',"What's in the box?"],['S2',"It's a ball."]],
    tips:['다른 물체로 나타낼 수 있다.','주사위의 사물을 판토마임으로 나타내게 할 수도 있다.'], src:52 },
  { ch:'F', en:'Snakes and Ladders', ko:'뱀과 사다리', aim:'칸의 질문에 답하거나 지시대로 행동하며 말판 전진하기', lang:'단원 질문·지시 종합', lv:'초4~6', time:'15~20분',
    form:'짝 또는 모둠', prep:['게임판','주사위','말'], mats:['M05'],
    steps:['직사각형 판에 칸을 만들고 사다리와 뱀을 그려 넣는다(M05 사용).','조별로 조 이름을 정하고 차례로 1명씩 주사위를 던져 나온 수만큼 이동한다.','도착한 칸의 질문에 답하거나 지시에 알맞게 행동한다. 틀리면 원래 자리로 돌아간다.','사다리 아래에 멈추면 위로 올라가고, 뱀 머리에 멈추면 꼬리로 내려간다.','먼저 끝 칸에 도착한 팀이 승리.'],
    talk:[['S','Six! … "Say three animals." Dog, cat, pig!']],
    tips:['짝 활동(pair work)도 가능하다.','칸의 질문을 단원에 맞게 포스트잇으로 바꿔 붙이면 재사용할 수 있다.'], src:11 },
  { ch:'F', en:'Coin Toss Game', ko:'동전 던지기 게임', aim:'동전 앞뒤에 따라 이동하며 지시문 읽고 따르기', lang:'Go back. / Go ahead 5. / Go back to the start.', lv:'초3~6', time:'10~15분',
    form:'모둠', prep:['놀이판(집→학교)','말','동전'], mats:['M13'],
    steps:['놀이판, 말, 동전을 준비한다(M13).','동전을 던져 앞면(head)이 나오면 두 칸, 뒷면(tail)이 나오면 한 칸 간다.','그림이 그려진 칸에서는 지시대로 숫자만큼 앞뒤로 간다.','학교에 일찍 도착한 사람이 승리.'],
    talk:[['S','Head! Two steps.'],['S','"Go ahead 5." Lucky!']],
    tips:['이동할 때마다 칸의 그림을 영어로 말하게 하면 어휘 연습이 추가된다.'], src:39 },
  { ch:'F', en:'Tic-Tac-Toe', ko:'삼목(三目) 놓기 게임', aim:'질문에 바르게 답해 칸을 차지하고 한 줄 만들기', lang:'단원 질문 종합', lv:'전학년', time:'10분',
    form:'전체 또는 분단 (2팀)', prep:['3×3 숫자 보드'], mats:['M14'],
    steps:['교사가 칠판에 9개의 네모 칸을 그리고 각각에 숫자를 쓴다(M14).','두 팀으로 나누어, 한 팀의 학생에게 교사가 학습한 질문을 한다.','옳게 대답하면 그 팀이 1~9 중 한 숫자를 고르고 그 칸에 ○(또는 ×)를 표시한다.','○나 ×를 한 줄에 3개 먼저 놓은 팀이 승리.'],
    talk:[['T',"What's this?"],['S',"It's a pencil! Number five, please."]],
    tips:['전략 요소가 있어 고학년도 집중한다.'], src:40 },
  { ch:'F', en:'Twenty Boxes Game', ko:'스무 칸 그리기', aim:'칸 번호와 그림을 말로 전달하고 비교하기', lang:'Number 7, a cat.', lv:'초3~4', time:'15분',
    form:'짝 (2~3팀)', prep:['20칸 게임판 2장(짝당)'], mats:['M06'],
    steps:['20개의 칸을 만든 게임판을 짝에게 한 장씩 나누어 준다(M06).','한 학생이 몇 칸에 몰래 그림을 그린 뒤, 칸 번호와 자기가 그린 것을 말한다.','다른 학생은 듣고 자기 판에 받아 그린다.','다 그린 뒤 두 판을 비교해 본다. 한 아동의 순서가 끝나면 역할을 바꾼다.'],
    talk:[['S1','Number seven, a cat.'],['S2','Number seven … a cat. OK!']],
    tips:['Information Gap의 기초 형태. 색을 함께 말하게 하면("a red cat") 어려워진다.'], src:12 },
  { ch:'F', en:'Board Game (Islands)', ko:'보드 게임 (섬 지도)', aim:'좌표(위치)를 말해 그림 위치를 전달하기', lang:'A cat is on island B2.', lv:'초4~6', time:'15분',
    form:'짝', prep:['섬 지도 2장(짝당)'], mats:['M12'],
    steps:['게임판을 복사해 나누어 주고 짝 활동으로 진행한다(M12).','각자 섬에 그리고 싶은 그림(동물·과일·학용품)을 그린다.','차례대로 한 번씩 위치를 말해 자기가 그린 그림을 상대에게 알려 주고, 상대가 알려 준 그림을 자기 섬에 그려 넣는다.','다 그린 후 서로 판을 비교하여 확인한다.'],
    talk:[['S1','A cat is on island B2.'],['S2','B2, a cat. An apple is on island C1.']],
    tips:['좌표(A1~C3) 대신 north/south/east/west 방위로 말하게 하면 원본 취지에 가깝다.'], src:38 },
  { ch:'F', en:'Information Gap', ko:'정보 차 메우기', aim:'서로 다른 그림의 정보를 질문으로 채우기', lang:"Where's the pencil? / It's on the book.", lv:'초4~6', time:'15분',
    form:'짝', prep:['그림 A(장소만)·B(사물 배치 완성) 한 쌍'], mats:['M11','M23'],
    steps:['두 사람이 한 팀이 되어 서로 다른 그림을 하나씩 나누어 갖는다. A 그림: 장소만 그려진 그림, B 그림: 사물이 놓인 완성된 그림.','A 그림을 가진 사람이 주어진 표의 사물(연필·고양이·전화·개)의 위치를 묻는다.','B 그림을 가진 사람이 자기 그림을 보며 위치를 알려 준다.','A는 B의 대답에 따라 자기 그림에 사물을 그려 넣는다.','빠르고 정확하게 그린 팀이 승리.'],
    talk:[['A',"Where's the pencil?"],['B',"It's on the book."],['A',"Where's the cat?"],['B',"It's under the chair."]],
    tips:['원본 p.10의 Information Gap은 본문이 잘못 들어가 있어 p.38 내용을 기준으로 정리했다.'], src:38 },

  // ───────────── G. 대화 · 역할 놀이 ─────────────
  { ch:'G', en:'Restaurant Role-play', ko:'식당에서 주문하기 놀이', aim:'음식을 주문하고 감사 인사 주고받기', lang:"~, please. / Thank you. / You're welcome.", lv:'초3~4', time:'15분',
    form:'4그룹', prep:['음식 그림카드','메뉴판'], mats:['M02','M22'],
    steps:['4그룹으로 나누어 대표(식당 주인)를 정한다.','먹고 싶은 음식을 그리게 한다(또는 M02 음식 카드 사용).','그룹별로 그린 그림을 모아 두고 대표가 음식점 주인 역할을 한다.','한 명씩 나와 먹고 싶은 음식을 가리키며 "(음식 이름), please." 라고 한다.','주인은 그 음식 그림카드를 건네준다. 주문한 사람은 "Thank you.", 주인은 "You\'re welcome." 이라고 말한다.'],
    talk:[['손님','Pizza, please.'],['주인','Here you are.'],['손님','Thank you.'],['주인',"You're welcome."]],
    tips:['M22 메뉴판을 두면 "How much is it?" 가격 묻기까지 확장할 수 있다.'], src:6 },
  { ch:'G', en:'Nice to meet you.', ko:'만나서 반가워요', aim:'처음 만난 사람과 이름을 말하며 인사하기', lang:"Hi, I'm ~. Nice to meet you. / Nice to meet you, too.", lv:'초3~4', time:'5~10분',
    form:'2팀 (마주 보기)', prep:['없음'], mats:[],
    steps:['두 팀이 서로 마주 보고 늘어선다.','앞사람부터 마주 보고 걸어가서 인사한 후, 맨 뒤로 가서 선다.','모두 한 번씩 인사할 때까지 계속한다.'],
    talk:[['A',"Hi, I'm Minho."],['B',"Hi, I'm Jenny. Nice to meet you."],['A','Nice to meet you, too.'],['A, B','Good-bye.']],
    tips:['영어 이름 카드를 목에 걸고 하면 이름을 바꿔 가며 반복할 수 있다.'], src:22 },
  { ch:'G', en:'Greeting Groups', ko:'인사말 주고 받기', aim:'조 이름을 부르며 상황에 맞는 인사말 주고받기', lang:'How are you, Mom? / Fine, thank you. / Good night, Mike.', lv:'초3~4', time:'10분',
    form:'4조 (Mom · Dad · Min-ho · Mike)', prep:['없음'], mats:[],
    steps:['학급을 4조로 나누어 각 조에 Mom, Dad, Min-ho, Mike라는 조 이름을 붙인다.','아동들은 주먹을 쥐고 리듬감 있게 앞뒤로 흔든다.','처음에는 교사가 인사하며 조 이름을 부른다.','호명된 조는 그 인사에 적절한 말로 대답하고, 조 대표는 인사말을 바꿔 다른 조 이름을 부른다.'],
    talk:[['T','How are you, Mom?'],['Mom조','Fine, thank you.'],['Mom조 대표','Good night, Mike.'],['Mike조','Good night.'],['Mike조 대표','Good afternoon, Dad.'],['Dad조','Good afternoon.']],
    tips:['리듬(박수 2번 → 인사)을 유지하면 집중도가 올라간다.'], src:28 },
  { ch:'G', en:"Doll's family", ko:'인형 가족 인사', aim:'손가락 인형으로 가족을 소개하고 인사하기', lang:'Hello. / Good morning. / Good-bye.', lv:'초3~4', time:'15분',
    form:'전체 → 분단', prep:['손가락 인형(장갑·종이로 제작)','가족·친구 명칭 카드'], mats:['M02'],
    steps:['각자 인형으로 자기 가족 모양을 만든다.','번갈아 손가락에 끼우고 알맞은 인사를 한다. (전체 → 분단)','Hello, Hi. / Good morning, afternoon, evening. / Good-bye.'],
    talk:[['S1','(아빠 인형) Hello, I\'m Dad.'],['S2','(엄마 인형) Good morning, Dad.'],['S1','Good-bye!']],
    tips:['M02 가족 카드를 막대에 붙여 막대 인형으로 대신할 수 있다.'], src:21 },
  { ch:'G', en:'Family Talk', ko:'가족관계 말하기 놀이', aim:'가족 그림을 보고 관계를 묻고 답하기', lang:"Who's he/she? / He's my dad. / She's my sister.", lv:'초3~4', time:'10분',
    form:'4분단', prep:['칠판'], mats:['M02'],
    steps:['아동들을 4등분하고 각 분단에서 한 명씩 칠판 앞으로 나오게 한다.','자기 가족 중 한 사람을 칠판에 그리고 자리로 돌아가 앉는다.','교사가 그림을 하나씩 가리키면 반 아동들은 그림을 그린 아동에게 질문한다. "Who\'s he/she?"','그림을 그린 아동은 일어나 자신과의 관계를 대답한다. "He/She\'s my dad (mom, brother, sister…)."','활동이 끝나면 교사가 그린 아동에게 질문하고 형제의 이름까지 함께 대답하게 한다.'],
    talk:[['Ss',"Who's he?"],['S',"He's my brother."],['T',"Who's she?"],['S',"She's my sister, Mina."]],
    tips:['가족 사진을 가져오게 하면 실제성이 높아진다.'], src:29 },
  { ch:'G', en:'Find Your Family', ko:'가족찾기 놀이', aim:'이름을 묻고 답하며 같은 그룹(형제) 찾기', lang:"I'm Min-ho. What's your name? / I'm Min-yeong.", lv:'초3~4', time:'10분',
    form:'분단 (10명)', prep:['이름 쪽지 10장'], mats:['M17'],
    steps:['10명 정도를 한 조로 구성한다.','5장의 종이에는 한국 이름을, 나머지 5장에는 외국 이름을 쓴다(M17).','각 종이의 이름 중 하나를 골라 ○표 하고 종이를 접어 책상 위에 놓는다.','조원들이 종이를 하나씩 집은 다음 다른 사람에게 이름을 물으며 형제를 찾는다. 한국 이름은 한국 이름끼리, 외국 이름은 외국 이름끼리 형제라고 생각한다.','형제를 찾으면 서로 껴안은 다음 제자리에 앉는다. 5명 모두 먼저 앉는 쪽이 이기고, 각자 자기 이름을 소개한다.'],
    talk:[['S1',"I'm Min-ho. What's your name?"],['S2',"I'm Min-yeong. We're family!"],['S',"I'm Min-ho. I'm Min-hyeok."]],
    tips:['형제를 찾는 것도 중요하지만 정확한 표현을 사용해 말하도록 한다.','다른 낱말 그림카드와 같이 사용하기도 한다.'], src:34 },
  { ch:'G', en:'Find your partner', ko:'짝 찾기 묻고 답하기', aim:'그림카드를 이용해 짝과 다양한 질문 주고받기', lang:'Do you like ~? / Can you ~? / Is this your ~? / Who is he?', lv:'초3~6', time:'10분',
    form:'분단 (짝 활동)', prep:['그림카드','사진·일기도(선택)'], mats:['M02'],
    steps:['짝과 묻고 대답한다.','그림카드를 이용하여 묻고 대답할 수 있다.','물건을 집고 "Is this your ~?", 사진을 보며 "Who is he/she?", 그림카드를 보며 "What do you like?", "Can you ~?", 일기도를 보며 "How\'s the weather?" 등으로 확장한다.'],
    talk:[['S1','Do you like fish?'],['S2','Yes, I do. I like fish.'],['S2','Do you like swimming?'],['S1','Yes, I do. I like swimming.']],
    tips:['단원에서 배운 질문 3개를 칠판에 적어 두고 짝을 바꿔 가며 반복한다.'], src:20 },
  { ch:'G', en:"I'm hungry.", ko:'배고파요 (I want an apple)', aim:'원하는 음식을 말하고 카드를 보이며 응답하기', lang:"I'm hungry. I want an apple. / I have an apple.", lv:'초3~4', time:'5~10분',
    form:'분단', prep:['과일 그림카드'], mats:['M02'],
    steps:['각자 과일 그림카드를 준비한다.','교사가 먼저 시범을 보인다. "I\'m hungry. I want an apple."','해당 카드를 가진 학생이 "Apple." 또는 "I have an apple." 이라고 카드를 보이며 말한다.','S1이 출제자가 되어 다시 시작한다.'],
    talk:[['T',"I'm hungry. I want an apple."],['S1','Apple! / I have an apple.'],['S1',"I'm hungry. I want a banana."]],
    tips:['카드를 건네주며 "Here you are." "Thank you." 를 덧붙이면 대화가 완성된다.'], src:24 },
  { ch:'G', en:'Bean bag Game', ko:'콩주머니 게임', aim:'콩주머니를 던지며 배운 질문과 대답 주고받기', lang:'What do you like? / Can you swim? / What day is it today?', lv:'초3~6', time:'10분',
    form:'전체', prep:['콩주머니(크고 부드럽게)'], mats:[],
    steps:['학급 전체가 실시한다.','교사가 먼저 학생에게 콩주머니를 던지며 묻는다.','받은 학생이 답한 뒤 다른 학생에게 콩주머니를 던지며 새 질문을 한다.','틀린 학생은 재미있는 벌을 받도록 한다.'],
    talk:[['T','What do you like?'],['S1','I like bananas. Can you swim?'],['S2','Yes, I can. What day is it today?'],['S3',"It's Monday."]],
    tips:['질문 목록을 칠판에 적어 두면 저학년도 질문을 고를 수 있다.'], src:18 },
  { ch:'G', en:'Musical Chairs Talk', ko:'대화 · 음악의자 앉기', aim:'음악에 맞춰 돌며 옆 친구와 배운 표현으로 대화하기', lang:'단원 표현 종합', lv:'전학년', time:'10~15분',
    form:'전체', prep:['의자(학생 수 − 1)','음악'], mats:[],
    steps:['의자를 두 줄로 등이 맞닿게 배열한다. 의자 수는 학생 수보다 하나 적게 한다.','음악이 흐르는 동안 학생들은 의자 주변을 돌며 옆 학생과 배운 표현으로 말을 주고받는다.','음악이 멈추면 의자에 앉는다. 의자를 못 차지한 학생은 게임에서 빠진다.','의자 한 개를 치우고 반복하다 의자 1개와 학생 2명이 남으면 끝낸다.'],
    talk:[['S1','Hi! How are you?'],['S2',"I'm fine. Do you like music?"]],
    tips:['의자는 교실 가장자리를 따라 배열해도 된다.','빠진 학생에게 "대화 심판" 역할을 주어 끝까지 참여시킨다.'], src:39 },
  { ch:'G', en:'Sit-Stand Song Game', ko:'노래에 맞춰 앉고 일어서기 놀이', aim:'노래가 끝날 때 서 있는 두 학생이 짝 대화하기', lang:"Thank you. / You're welcome. / I'm sorry. / That's OK. / Are you OK? / Yes, I'm OK.", lv:'초3~4', time:'10분',
    form:'2조', prep:['배운 노래 또는 챈트'], mats:[],
    steps:['학생들을 두 조로 나눈다.','전체가 배운 노래나 챈트를 부르며 각 조에서 한 명씩 차례로 일어섰다 앉는다.','노래가 끝났을 때 일어서 있는 두 학생이 가위바위보로 누가 먼저 말을 건넬지 정한다.','제대로 대화를 주고받은 조에 점수. 일정 시간 후 점수가 많은 조가 승리.'],
    talk:[['이긴 학생',"Thank you. / I'm sorry. / Are you OK?"],['진 학생',"You're welcome. / That's OK. / Yes, I'm OK."]],
    tips:['대화 쌍을 칠판에 세 개 적어 두고 그중 하나를 골라 쓰게 한다.'], src:31 },
  { ch:'G', en:'East Gate Game', ko:'동대문 놀이', aim:'아치를 통과하다 잡힌 학생과 영어로 인사 주고받기', lang:'Hi. / Hello. / Good morning. / Bye. / Good-bye.', lv:'초3~4', time:'10분',
    form:'분단 (10명)', prep:['없음'], mats:[],
    steps:['10명 정도를 한 조로 구성한다.','그중 두 사람이 손을 맞잡은 채 들어올려 아치를 만든다.','나머지는 손을 잡고 "동동 동대문을 열어라" 또는 "London Bridge" 노래를 하며 차례로 아치를 지난다.','노래가 끝날 때 들어올렸던 손을 내려 지나던 아동 한 명을 가둔다.','아치를 만든 아동 중 한 명이 갇힌 아동과 영어로 인사를 주고받는다.','제대로 인사하면 풀어 주고, 그렇지 않으면 아치를 만든 아동과 교대한다.'],
    talk:[['아치','Good morning!'],['갇힌 아동','Good morning! How are you?'],['아치',"I'm fine. Bye!"]],
    tips:['London Bridge is falling down 노래를 영어로 부르면 노래 학습도 된다.'], src:34 },
  { ch:'G', en:'Mimic Game', ko:'흉내내기 놀이', aim:'현재진행형 동작을 말하고 조원이 함께 흉내 내기', lang:"What's Min-ho doing? / He's singing.", lv:'초5~6', time:'10분',
    form:'4조 (Min-ho · Min-ji · Annie · Johnny)', prep:['동작 그림카드(선택)'], mats:['M02'],
    steps:['아동들을 4조로 나누어 민호·민지·애니·조니조로 이름 붙이고 각 조의 대표를 뽑는다.','교사는 조 이름을 넣어 질문을 던진다. "What\'s Min-ho doing?"','각 조의 대표가 임의로 자기 조의 동작을 대답하면 조원 전체는 그 동작을 흉내 낸다.'],
    talk:[['T',"What's Min-ho doing?"],['민호조 대표',"He's singing! (dancing, cooking, reading a book …)"],['민호조','(노래하는 흉내)']],
    tips:['M02 동작 카드를 뽑아 대답하게 하면 어휘 범위가 통제된다.'], src:32 },
  { ch:'G', en:'Animal dance', ko:'동물 춤', aim:'동물의 몸짓과 울음소리로 동물 이름 맞히기', lang:"It's a cat. / It's a dog.", lv:'초3~4', time:'10분',
    form:'전체 → 분단', prep:['동물 그림카드'], mats:['M02'],
    steps:['그림카드 중 한 장을 엎어 놓고(본 학생만 알게), 특징을 살린 몸짓과 울음소리를 낸다.','학생들이 "It\'s a cat." "It\'s a dog." 처럼 알아맞힌다.','맞힌 사람이 앞에 나와 다시 시작한다.'],
    talk:[['S1','(네 발로 기며) Meow~'],['Ss',"It's a cat!"]],
    tips:['Guess What?(B)와 달리 소리를 낼 수 있어 저학년에 적합하다.'], src:22 },
  { ch:'G', en:'Scramble Game', ko:'스크램블 (자리 바꾸기)', aim:'자기 낱말을 듣고 재빨리 자리 바꾸기', lang:'단원 어휘', lv:'전학년', time:'10분',
    form:'분단 (원형 의자)', prep:['의자','낱말 카드(배정용)'], mats:['M02'],
    steps:['아동들을 빙 둘러 의자에 앉힌다. 학급 규모가 크면 몇 그룹으로 나눈다.','교사는 모든 아동에게 각각 낱말 하나씩을 배정한다.','교사가 두 낱말을 말하고 나서 "Scramble!" 이라고 하면 그 두 낱말을 배정받은 두 아동은 일어서서 재빨리 상대방이 앉아 있던 곳으로 뛰어가 앉는다.','교사는 늦게 앉은 아동의 의자를 빼앗고, 그 아동은 가운데에 서 있게 한다. 가운데 선 아동이 다음 낱말을 부르게 한다.'],
    talk:[['T','Apple, banana … Scramble!'],['가운데 S','Tiger, lion … Scramble!']],
    tips:['Fruit salad 게임의 변형. "Fruits!" 라고 범주를 외치면 모두 자리를 바꾸는 규칙을 추가한다.'], src:41 },
  ],
};
