// 게임별 보강 데이터: ex(예시 진행), check(관찰 포인트), mats(전용 머트리얼 사양) — en(영문명) 기준으로 기본 데이터와 합친다.
// mats 사양: ['cards',{cat|items,copies}] ['nums',{from,to}] ['clocks','analog'|'blank'|'sentence'] ['bingo',{size,words?,boards}]
//   ['board','snakes'|'timegrid'|'twenty'|'islands'|'coin'|'ttt'|'numboard'] ['dice',faces|null] ['score','team'|'pair'|'dice']
//   ['signs',[[text,color,sub],[...]]] ['scene','gapA'|'gapB'|'drawit'] ['labels',[[emoji,en,ko]]] ['slips','names'|'ox']
//   ['mask'] ['poster20q'] ['faces'] ['menu'] ['preps'] ['days'] ['apples'] ['cue',{title,lines:[[en,ko,emoji]]}]
//   ['dialog',{title,lines:[[who,en,ko]]}] ['roles',[[emoji,name,ko]]] ['puzzle',{emoji,word,ko}] ['truefalse',{title,lines:[[en,ok]]}]
//   ['sounds',[[emoji,animal,sound]]] ['peek'] ['house'] ['faceposter'] ['worksheet','memory'|'position'|'family'|'addon'|'clockdraw']
const F = { // 자주 쓰는 카드 묶음
  animals4: [['dog','개','🐶'],['cat','고양이','🐱'],['cow','소','🐮'],['horse','말','🐴']],
  school4x4: [['pencil','연필','✏️'],['book','책','📘'],['ruler','자','📏'],['bag','가방','🎒']],
  objects20q: [['apple','사과','🍎'],['ball','공','⚽'],['pencil','연필','✏️'],['toothbrush','칫솔','🪥'],['soap','비누','🧼'],['key','열쇠','🔑'],['spoon','숟가락','🥄'],['cup','컵','🥤'],['scissors','가위','✂️'],['book','책','📘'],['coin','동전','🪙'],['sock','양말','🧦']],
  smells: [['vinegar','식초','🧪'],['soy sauce','간장','🫙'],['apple','사과','🍎'],['lemon','레몬','🍋'],['coffee','커피','☕'],['soap','비누','🧼'],['onion','양파','🧅'],['chocolate','초콜릿','🍫']],
  sounds: [['🐷','pig','Oink oink'],['🐱','cat','Meow meow'],['🐶','dog','Woof woof'],['🐮','cow','Moo moo'],['🦆','duck','Quack quack'],['🐑','sheep','Baa baa'],['🐔','chicken','Cluck cluck'],['🦁','lion','Roar!']],
  names: [['🧒','민호','Min-ho'],['👧','서연','Seo-yeon'],['🧒','지호','Ji-ho'],['👧','하은','Ha-eun'],['🧒','도윤','Do-yun'],['👧','예린','Ye-rin']],
};
module.exports = {
// ───────── A ─────────
'Word Family Game': {
  ex:{set:'초3 8명 · 두 팀(사과팀·별팀) · 동물·과일·운동·음식 복습', lines:[
    ['상황','팀마다 카드 24장과 분류 봉투 4개. 칠판에 Animals / Fruits / Sports / Food 라벨.'],
    ['T','Look at the board. Four groups. Put the cards in the right bag. Three minutes. Ready, go!'],
    ['민수','(카드를 넘기며) Banana… fruit! Soccer… sport!'],
    ['서연','Tiger is an animal. Here!'],
    ['T','(3분 뒤) Stop! Apple team, open the Animals bag.'],
    ['사과팀','Dog, cat, tiger, pig… and apple!'],
    ['T','Is an apple an animal? No! Minus one. Fruits bag?'],
    ['결과','사과팀 17점, 별팀 19점 → 별팀 승리. 틀린 카드는 다 함께 다시 분류하며 마무리.']]},
  check:['카드를 넣을 때 낱말을 소리 내어 말하는가 (말하지 않고 넣으면 점수 없음).','범주 이름(Animals, Fruits …)을 영어로 읽을 수 있는가.'],
  mats:[['cards',{cat:'Animals'}],['cards',{cat:'Fruits'}],['cards',{cat:'Sports'}],['cards',{cat:'Food'}],['labels',[['🐾','Animals','동물'],['🍎','Fruits','과일'],['⚽','Sports','운동'],['🍔','Food','음식']]],['score','team']] },
"What's missing?": {
  ex:{set:'초3 10명 · 전체 · 동물 카드 8장', lines:[
    ['T','(카드를 하나씩 붙이며) Dog, cat, pig, cow, lion, bear, rabbit, duck. Repeat!'],
    ['Ss','Dog, cat, pig …'],
    ['T','Close your eyes! (rabbit 카드를 뗀다) Open your eyes. What\'s missing?'],
    ['지호','(손을 들고) Rabbit!'],
    ['T','Yes! Rabbit is missing. One point, Ji-ho. Now, Ji-ho, you take one.'],
    ['지호','Close your eyes! … Open your eyes. What\'s missing?'],
    ['하은','Bear and duck!'],
    ['결과','학생이 출제자가 되는 순간부터 질문 "What\'s missing?"을 아이들이 스스로 말하게 된다.']]},
  check:['빠진 카드를 "The ___ is missing." 문장으로 말할 수 있는가.','두 장을 뺐을 때 and로 연결하는가.'],
  mats:[['cards',{cat:'Animals'}],['cards',{cat:'School things'}]] },
'Memory Game 1': {
  ex:{set:'초3 4명 모둠 · 과일 카드 8쌍(16장)', lines:[
    ['상황','카드 16장을 4×4로 뒷면이 보이게 놓는다.'],
    ['민수','(한 장 뒤집으며) A banana. (또 한 장) A peach. Not the same.'],
    ['T','OK, turn them over. Next!'],
    ['서연','An apple… an apple! Same!'],
    ['T','Great! Keep them and go again.'],
    ['서연','Grapes… a pear. No.'],
    ['결과','카드를 뒤집을 때마다 낱말을 말하므로 한 판에 낱말을 40번 이상 듣고 말하게 된다.']]},
  check:['뒤집은 두 장을 모두 영어로 말한 뒤 가져가는가.','Same / Not the same을 스스로 판단해 말하는가.'],
  mats:[['cards',{cat:'Fruits'}],['cards',{cat:'Fruits'}],['score','dice']] },
'Memory Game 2': {
  ex:{set:'초4 12명 · 2팀 · 숫자 카드 6장', lines:[
    ['상황','책상 위 보자기 아래 숫자 카드 6장(3, 7, 12, 15, 9, 20).'],
    ['T','Team Apple, come here. Look carefully. One, two… cover!'],
    ['사과팀','(자리로 돌아가 종이에 쓴다)'],
    ['T','What did you see?'],
    ['민수','Three, seven, twelve… fifteen!'],
    ['T','Four numbers! Team Star, your turn.'],
    ['결과','별팀은 5개를 기억해 승리. 2라운드는 동물 카드로 바꾸어 영어 단어 쓰기로 진행.']]},
  check:['기억한 수를 영어로 말하는가(한국어로 말하면 반 점).','쓰기 활동에서 철자를 보고 베끼지 않고 쓰는가.'],
  mats:[['nums',{from:0,to:20}],['worksheet','memory']] },
'Speed Game (Cards)': {
  ex:{set:'초3 10명 · 2팀 · 동물·과일 카드 20장', lines:[
    ['상황','카드 20장을 바닥 가운데 펼친다. 팀마다 한 명씩 카드 앞에 무릎을 꿇고 앉는다.'],
    ['T','Hands on your head! Ready… Elephant!'],
    ['지호','(카드를 집으며) Elephant!'],
    ['T','Ji-ho, one point! Next two. Hands on your head… Strawberry!'],
    ['하은·민수','(동시에 집는다)'],
    ['T','Both? Rock, scissors, paper!'],
    ['결과','카드가 다 없어지면 각 팀이 모은 카드를 세며 함께 낱말을 복습한다.']]},
  check:['집은 카드의 낱말을 다시 말하는가.','"Hands on your head" 규칙을 지켜 먼저 손을 뻗지 않는가.'],
  mats:[['cards',{cat:'Animals'}],['cards',{cat:'Fruits'}],['score','team']] },
'Snap Cards': {
  ex:{set:'초4 6명 모둠 · 학용품 카드 2벌(16장)', lines:[
    ['상황','1벌은 그림이 보이게 책상에 펼치고, 1벌은 뒤집어 쌓아 둔다.'],
    ['도윤','(더미 맨 위 카드를 뒤집어 외친다) Scissors!'],
    ['모두','(펼쳐진 가위 카드를 향해 손바닥을 뻗는다)'],
    ['예린','(먼저 덮으며) Scissors!'],
    ['T','Ye-rin got it! Do-yun, put your card under the pile.'],
    ['결과','외치는 사람을 돌아가며 맡게 하면 모두가 8번씩 낱말을 외친다.']]},
  check:['덮은 뒤 낱말을 말해야 가져갈 수 있다는 규칙을 지키는가.','손이 아닌 카드를 보며 집중해서 듣는가.'],
  mats:[['cards',{cat:'School things'}],['cards',{cat:'School things'}],['score','dice']] },
'Vocabulary Game': {
  ex:{set:'초3 8명 · 2팀 · 옷·학용품 카드', lines:[
    ['T','(워밍업) Everyone, draw a cat. … Good. Now look at the clothesline.'],
    ['상황','칠판 앞에 고무줄을 걸고 집게로 카드 10장을 매단다.'],
    ['T','Team Apple, Min-su. Point to the socks.'],
    ['민수','(양말 카드를 떼어 팀에 가져간다) Socks!'],
    ['T','Team Star, Seo-yeon. Point to the pencil.'],
    ['서연','(지우개 카드를 뗀다)'],
    ['T','Hmm, is this a pencil? No, it\'s an eraser. Put it back.'],
    ['결과','카드가 다 없어졌을 때 사과팀 6장, 별팀 4장. 각 팀이 모은 카드를 영어로 세어 본다.']]},
  check:['Point to의 뜻을 몸으로 이해하는가.','잘못 뗀 카드를 교사가 바로잡을 때 다시 말해 보는가.'],
  mats:[['cards',{cat:'Clothes'}],['cards',{cat:'School things'}],['cue',{title:'교사 지시 카드 — Point to the ~.',lines:[['Point to the socks.','양말을 가리키세요','🧦'],['Point to the shirt.','셔츠를 가리키세요','👕'],['Point to the hat.','모자를 가리키세요','🧢'],['Point to the pencil.','연필을 가리키세요','✏️'],['Point to the bag.','가방을 가리키세요','🎒'],['Point to the book.','책을 가리키세요','📘'],['Point to the shoes.','신발을 가리키세요','👟'],['Point to the ruler.','자를 가리키세요','📏']]}]] },
'Picture Puzzle': {
  ex:{set:'초3 10명 · 분단 · 호랑이 조각 그림 6조각', lines:[
    ['T','(귀 조각 하나를 붙이며) What\'s this?'],
    ['지호','It\'s a… cat?'],
    ['T','Maybe! One more piece. (줄무늬 조각) What\'s this?'],
    ['하은','It\'s a tiger!'],
    ['T','Yes! It\'s a tiger. Ha-eun, two points. Next puzzle!'],
    ['결과','조각 2개에 맞히면 2점, 4개 이후 맞히면 1점으로 하면 추측을 과감하게 하게 된다.']]},
  check:['It\'s a ~. 문장으로 답하는가.','틀렸을 때 다시 도전하는가(틀려도 감점하지 않음).'],
  mats:[['puzzle',{emoji:'🐯',word:'tiger',ko:'호랑이'}],['puzzle',{emoji:'🚂',word:'train',ko:'기차'}],['puzzle',{emoji:'🍉',word:'watermelon',ko:'수박'}]] },
'Collect Three Foods': {
  ex:{set:'초3 12명 · 전체 · 햄버거·피자·치킨 카드 각 3장씩 배부', lines:[
    ['상황','민수는 햄버거 3장, 서연은 피자 3장을 들고 교실을 돌아다닌다.'],
    ['민수','Do you like hamburgers?'],
    ['서연','(햄버거 카드가 없으므로) Yes, I do. (카드를 교환)'],
    ['민수','(다음 친구에게) Do you like hamburgers?'],
    ['지호','(햄버거를 갖고 있으므로) No, I don\'t.'],
    ['T','Stop! Who has three different cards?'],
    ['하은','Me! Hamburger, pizza, chicken!'],
    ['결과','3종류를 모은 하은이 승리. 가진 카드를 "I like pizza." 로 발표하며 끝.']]},
  check:['Yes, I do. 일 때만 카드를 바꾸는 규칙을 이해하는가.','묻는 문장에 자기 카드의 음식 이름(복수형)을 넣는가.'],
  mats:[['cards',{cat:'Food'}],['cards',{cat:'Food'}],['dialog',{title:'대화 카드 — Do you like ~?',lines:[['A','Do you like hamburgers?','햄버거 좋아해?'],['B','Yes, I do. (카드를 바꾼다)','응, 좋아해.'],['B',"No, I don't. (바꾸지 않는다)",'아니, 안 좋아해.'],['A','Thank you! Bye!','고마워! 안녕!']]}]] },
'Card Collecting': {
  ex:{set:'초5 4명 모둠 · 연필·책·자·가방 카드 각 4장(16장)', lines:[
    ['상황','리더가 섞어 4장씩 나눠 준다. 민수: 연필 2, 책 1, 자 1.'],
    ['민수','Seo-yeon, can I have a pencil?'],
    ['서연','Yes, here you are. (연필 카드를 건넨다)'],
    ['민수','Thank you. Ji-ho, can I have a pencil?'],
    ['지호','No, I haven\'t. Sorry.'],
    ['상황','민수 차례 끝. 지호가 묻는다.'],
    ['지호','Min-su, can I have a bag?'],
    ['결과','민수가 연필 4장을 먼저 모아 "I have four pencils!" 하고 승리.']]},
  check:['Can I have a ~? / Here you are / Thank you 세 문장이 한 묶음으로 나오는가.','없을 때 No, I haven\'t.(또는 Sorry, I don\'t have one.)로 답하는가.'],
  mats:[['cards',{items:F.school4x4.concat(F.school4x4,F.school4x4,F.school4x4),title:'카드 놀이용 학용품 카드 (4종×4장)'}],['dialog',{title:'대화 카드 — Can I have ~?',lines:[['A','Can I have a pencil?','연필 한 자루 줄 수 있어?'],['B','Yes, here you are.','응, 여기 있어.'],['B',"No, I haven't.",'아니, 없어.'],['A','Thank you.','고마워.'],['B',"You're welcome.",'천만에.']]}]] },
'Find Your Sport': {
  ex:{set:'초4 12명 · 운동 그림 쪽지 6종×2장', lines:[
    ['상황','접힌 쪽지를 한 장씩 뽑는다. 하은은 축구공.'],
    ['하은','Do you like soccer?'],
    ['도윤','No, I don\'t. I like tennis.'],
    ['하은','(다음 친구에게) Do you like soccer?'],
    ['예린','Yes, I do! I like soccer!'],
    ['하은·예린','(교사에게 쪽지를 내며) Let\'s play soccer!'],
    ['T','Great! Let\'s play outside! (둘은 어깨동무하고 자리로)'],
    ['결과','6쌍이 모두 짝을 찾을 때까지 진행. 마지막 쌍에게도 박수.']]},
  check:['No, I don\'t. 뒤에 I like ~. 를 덧붙여 정보를 주는가.','짝을 찾은 뒤 Let\'s play ~. 로 마무리하는가.'],
  mats:[['cards',{cat:'Sports'}],['cards',{cat:'Sports'}],['dialog',{title:'대화 카드 — 짝 찾기',lines:[['A','Do you like soccer?','축구 좋아해?'],['B',"No, I don't. I like tennis.",'아니. 나는 테니스 좋아해.'],['B','Yes, I do! I like soccer!','응! 나도 축구 좋아해!'],['A+B',"Let's play soccer!",'축구하자!']]}]] },
"I like / I don't like": {
  ex:{set:'초3 6명 모둠 · 얼굴판 A/B · 음식 카드 8장', lines:[
    ['상황','책상에 😋(A)와 😖(B) 얼굴판을 놓는다.'],
    ['T','(피자 카드를 A 아래에 놓으며) Look!'],
    ['Ss','I like pizza!'],
    ['T','(당근 카드를 B 아래에) And this?'],
    ['Ss','I don\'t like carrots!'],
    ['T','Now you. Seo-yeon, put a card.'],
    ['서연','(아이스크림을 A 아래에) I like ice cream!'],
    ['결과','학생이 자기 취향대로 놓으면서 "진짜 내 말"을 하게 된다. 반 친구들은 "Me too!"로 반응.']]},
  check:['don\'t 를 빼먹지 않고 부정문을 말하는가.','Me too / Me neither 같은 반응을 덧붙이는가(선택).'],
  mats:[['faces'],['cards',{cat:'Food'}]] },
'Catch Ball Game': {
  ex:{set:'초3 12명 · 원형 · 동물 카드 6종×2장', lines:[
    ['상황','모두 카드를 받아 자기 동물을 확인한다. 교사가 가운데 선다.'],
    ['T','Bear! (공을 높이 던진다)'],
    ['지호·하은','(곰 카드를 가진 둘이 달려 나와 공을 잡으려 함)'],
    ['상황','지호가 잡았다. 하은은 자리에 앉아 심판 역할.'],
    ['지호','Rabbit! (공을 던진다)'],
    ['결과','마지막까지 남은 2명이 결승. 탈락한 학생은 "Yes! / No!" 판정을 외치며 참여.']]},
  check:['자기 카드의 동물 이름을 듣고 0.5초 안에 반응하는가.','공을 잡은 뒤 새 낱말을 또렷하게 외치는가.'],
  mats:[['cards',{cat:'Animals'}],['cards',{cat:'Animals'}]] },
'Animal Card Game': {
  ex:{set:'초3 4명 모둠 · 개·고양이·소·말 카드', lines:[
    ['상황','카드 4장을 엎어 각자 앞에 놓고 자기 것만 본다.'],
    ['T','Min-su, are you a cat?'],
    ['민수','No.'],
    ['T','Are you a dog?'],
    ['민수','Yes, that\'s right.'],
    ['T','Now you ask. Seo-yeon?'],
    ['민수','Seo-yeon, are you a horse?'],
    ['결과','한 바퀴 돌면 카드를 걷어 다시 섞는다. 3라운드 후 I\'m a ~. 로 스스로 밝히기.']]},
  check:['Are you a ~? 의 억양이 올라가는가.','Yes, I am. / No, I\'m not. 까지 확장할 수 있는가.'],
  mats:[['cards',{items:F.animals4.concat(F.animals4),title:'동물 카드 4종×2장 (모둠 2개분)'}],['dialog',{title:'대화 카드 — Are you a ~?',lines:[['A','Are you a cat?','너는 고양이니?'],['B','No. / No, I\'m not.','아니.'],['A','Are you a dog?','너는 개니?'],['B',"Yes, that's right. / Yes, I am.",'응, 맞아.']]}]] },
'Guess My Color': {
  ex:{set:'초3 8명 · 분단', lines:[
    ['상황','민수가 앞에 나와 종이에 red를 적어 접는다.'],
    ['민수','Guess, what color do I like?'],
    ['서연','Do you like blue?'],
    ['민수','No, I don\'t.'],
    ['지호','Do you like red?'],
    ['민수','Yes, I do! (종이를 펼쳐 보인다)'],
    ['T','Ji-ho, your turn. Write your color.'],
    ['결과','색 8개를 칠판에 붙여 두면 저학년도 질문을 고를 수 있다.']]},
  check:['Do you like ~? 로 묻고 Yes, I do / No, I don\'t 로 답하는가.','자기 차례가 아닐 때도 끝까지 듣는가.'],
  mats:[['cards',{cat:'Colors'}],['dialog',{title:'대화 카드 — What color do I like?',lines:[['A','Guess, what color do I like?','내가 좋아하는 색을 맞혀 봐.'],['B','Do you like blue?','파란색 좋아해?'],['A',"No, I don't.",'아니.'],['B','Do you like red?','빨간색 좋아해?'],['A','Yes, I do!','응!']]}]] },
"What's this? (Team Quiz)": {
  ex:{set:'초3 10명 · A·B팀 · 학용품·장난감 카드 16장', lines:[
    ['상황','카드를 상자에 넣고 A팀 민수, B팀 서연이 앞에 선다.'],
    ['민수','(카드를 뽑아 들며) What\'s this?'],
    ['서연','It\'s a ruler!'],
    ['T','B team, one point. Now Seo-yeon asks.'],
    ['서연','What\'s this?'],
    ['민수','It\'s a… (팀을 돌아본다)'],
    ['A팀','Robot!'],
    ['민수','It\'s a robot!'],
    ['T','Team help — half point. OK!'],
    ['결과','16장을 다 뽑으면 끝. 7:6으로 B팀 승리.']]},
  check:['관사 a/an을 붙여 답하는가(an eraser).','팀 도움 반 점 규칙을 이해하고 스스로 답하려 하는가.'],
  mats:[['cards',{cat:'School things'}],['cards',{cat:'Toys'}],['score','team']] },

// ───────── B ─────────
'Twenty Questions': {
  ex:{set:'초5 10명 · 2팀 · 상자 속 물건: 칫솔', lines:[
    ['T','(상자를 흔들며) What\'s in the box? Twenty questions. Team Apple first.'],
    ['민수','Is it big?'],
    ['T','No. (칠판에 正 한 획)'],
    ['서연','Is it made of plastic?'],
    ['T','Yes.'],
    ['지호','Can you eat it?'],
    ['T','No.'],
    ['하은','Is it in the bathroom?'],
    ['T','Yes!'],
    ['도윤','Is it a toothbrush?'],
    ['T','Yes! Six questions. Team Star wins!'],
    ['결과','포스터(M19)의 질문 틀을 보며 색→크기→재료→장소→용도 순으로 좁히는 전략을 익힌다.']]},
  check:['Yes/No로 답할 수 있는 의문문만 쓰는가(What is it? 금지).','앞 사람의 답을 기억해 질문을 좁혀 가는가.'],
  mats:[['poster20q'],['cards',{items:F.objects20q,title:'상자 속 물건 예시 카드 (실물이 없을 때 대신 사용)'}],['score','team']] },
"What's in the box? (Leader)": {
  ex:{set:'초3 7명 팀 · 상자 속 과일 실물', lines:[
    ['상황','리더 민수가 상자에서 바나나를 보이지 않게 집는다.'],
    ['민수','What\'s in the box?'],
    ['서연','Is it red?'],
    ['민수','No.'],
    ['지호','Is it yellow?'],
    ['민수','Yes!'],
    ['하은','Is it a banana?'],
    ['민수','Yes! You\'re right. (하은이 다음 리더)'],
    ['결과','색 질문 → 이름 질문의 2단계를 지키면 형용사·명사가 함께 연습된다.']]},
  check:['색을 먼저 묻고 이름을 묻는 순서를 지키는가.','리더가 Yes/No 외의 힌트를 주지 않는가.'],
  mats:[['cards',{cat:'Fruits'}],['cards',{cat:'Colors'}],['dialog',{title:'대화 카드 — What\'s in the box?',lines:[['리더',"What's in the box?",'상자 안에 뭐가 있을까?'],['S','Is it red? / yellow?','빨간색이야? 노란색이야?'],['리더','Yes. / No.','응. / 아니.'],['S','Is it an apple?','사과야?'],['리더',"Yes! You're right.",'응! 맞았어.']]}]] },
'Magic Basket': {
  ex:{set:'초3 8명 · 전체 · 바구니 속 학용품 8개', lines:[
    ['T','Seo-yeon, come here. Close your eyes and pick one.'],
    ['서연','(눈을 감고 꺼내 등 뒤에 숨긴다) What\'s this?'],
    ['민수','Is this a pencil?'],
    ['서연','No.'],
    ['지호','Is this a ruler?'],
    ['서연','Yes! (자를 보여 준다)'],
    ['T','Ji-ho, your turn. Close your eyes.'],
    ['결과','8개를 다 꺼낼 때까지 진행. 꺼낸 물건은 책상에 늘어놓고 마지막에 다 같이 이름 말하기.']]},
  check:['Is this a ~? 로 묻는가(Is it ~? 도 허용).','꺼낸 학생이 물건을 보여 주기 전에 끝까지 질문을 받는가.'],
  mats:[['cards',{cat:'School things'}],['dialog',{title:'대화 카드 — Magic Basket',lines:[['리더',"What's this?",'이게 뭘까?'],['S','Is this a pencil?','연필이야?'],['리더','No.','아니.'],['S','Is this an eraser?','지우개야?'],['리더','Yes!','응!']]}]] },
'Dipping Game': {
  ex:{set:'초3 5명 모둠 · 상자 속 동물 카드 10장', lines:[
    ['민수','(카드를 꺼내 들며) This is a dog.'],
    ['T','Good! Keep it. Next, Seo-yeon.'],
    ['서연','(꺼내서 보지 않고) Is this a cat?'],
    ['모둠','No, it isn\'t. It\'s a pig!'],
    ['T','Put it back. Ji-ho?'],
    ['지호','This is a lion!'],
    ['결과','맞게 말한 카드만 가져가므로 끝나면 자연스럽게 개인 점수가 된다. 하은 3장으로 승리.']]},
  check:['This is a(n) ~. 에서 관사를 맞게 쓰는가.','틀린 친구에게 No, it isn\'t. It\'s a ~. 로 바로잡아 주는가.'],
  mats:[['cards',{cat:'Animals'}],['dialog',{title:'대화 카드 — Dipping Game',lines:[['S1','This is a dog.','이것은 개야.'],['S2','Is this a cat?','이거 고양이야?'],['Ss',"No, it isn't. It's a pig.",'아니, 돼지야.'],['Ss','Yes, it is!','응, 맞아!']]}],['score','dice']] },
'Guess What?': {
  ex:{set:'초3 10명 · A·B팀 · 동물·옷 카드', lines:[
    ['상황','A팀 민수가 원숭이 카드를 받는다. 말은 금지.'],
    ['민수','(겨드랑이를 긁으며 뛰어다닌다)'],
    ['A팀','Monkey!'],
    ['T','Yes! Ten seconds. One point!'],
    ['상황','B팀 서연은 모자 카드. 머리에 무언가 쓰는 시늉.'],
    ['B팀','Hat! … Cap!'],
    ['T','Hat! Right!'],
    ['결과','30초 모래시계를 쓰면 긴장감이 생긴다. 10번 하고 6:4로 A팀 승리.']]},
  check:['설명하는 학생이 소리를 내지 않는가.','맞히는 팀이 It\'s a ~! 문장으로 답하는가.'],
  mats:[['cards',{cat:'Animals'}],['cards',{cat:'Clothes'}],['score','team']] },
'Mime Game': {
  ex:{set:'초5 8명 · 2팀 · 직업 카드 8장', lines:[
    ['상황','A팀 주장 민수에게 doctor 카드를 보여 준다.'],
    ['민수','(청진기를 대는 시늉, 주사 놓는 시늉)'],
    ['A팀','Doctor!'],
    ['T','What is he?'],
    ['A팀','He\'s a doctor!'],
    ['상황','B팀 주장 서연: firefighter. 호스로 물 뿌리는 시늉.'],
    ['B팀','Firefighter!'],
    ['결과','고학년은 맞힌 뒤 "I want to be a doctor." 로 한 문장씩 더 말하게 한다.']]},
  check:['He\'s a ~. / She\'s a ~. 문장으로 답하는가.','몸짓 힌트 카드 없이도 직업 특징을 떠올리는가.'],
  mats:[['cards',{cat:'Jobs'}],['cue',{title:'몸짓 힌트 카드 (주장용)',lines:[['doctor','청진기 대기 · 주사 놓기','👨‍⚕️'],['teacher','칠판에 쓰기 · 출석 부르기','👩‍🏫'],['cook','프라이팬 흔들기 · 간 보기','👨‍🍳'],['police officer','호루라기 · 교통 정리','👮'],['firefighter','호스로 물 뿌리기','👩‍🚒'],['farmer','씨 뿌리기 · 괭이질','👨‍🌾'],['singer','마이크 잡고 노래','👩‍🎤'],['pilot','조종간 잡기 · 경례','👨‍✈️']]}]] },
'Who am I?': {
  ex:{set:'초3 10명 · 2팀(사과·별) · 3×3 보드', lines:[
    ['T','Rock, scissors, paper! Apple team first.'],
    ['사과팀','(모여서 동물을 정한 뒤 나란히 서서) I\'m… (어흥!)'],
    ['별팀','Are you a tiger?'],
    ['사과팀','Yes!'],
    ['T','Star team got it! Draw a star. Which number?'],
    ['별팀','Number five!'],
    ['상황','별팀 차례. 네 발로 기며 Meow.'],
    ['사과팀','Are you a dog?'],
    ['별팀','No, I\'m not!'],
    ['T','Chance goes to Star team. Draw another star!'],
    ['결과','별팀이 5-1-9 대각선 완성으로 승리.']]},
  check:['Are you a ~? / Yes. / No, I\'m not. 교환이 이루어지는가.','보드의 칸 번호를 영어로 말하는가.'],
  mats:[['board','ttt'],['sounds',F.sounds],['roles',[['🍎','Apple Team','사과팀'],['⭐','Star Team','별팀']]]] },
'Guessing Game 1': {
  ex:{set:'초3 10명 · 전체', lines:[
    ['T','Oink oink. What am I?'],
    ['Ss','You are a pig!'],
    ['T','Meow meow. What am I?'],
    ['Ss','You are a cat!'],
    ['T','Now, Ha-eun, you try.'],
    ['하은','Quack quack. What am I?'],
    ['Ss','You are a duck!'],
    ['결과','영어 의성어(oink, meow, woof, moo, quack, baa)를 카드로 보여 주면 한국어 의성어와 비교하며 즐거워한다.']]},
  check:['You are a ~. 문장으로 답하는가.','영어 의성어를 따라 말하는가.'],
  mats:[['sounds',F.sounds]] },
'Guessing Game 2': {
  ex:{set:'초3 6명 모둠 · 연필 1자루', lines:[
    ['상황','모두 손을 등 뒤로. 민수가 연필을 숨긴다. 나머지도 가진 척한다.'],
    ['T','You have the pencil, Seo-yeon.'],
    ['서연','No.'],
    ['T','You have the pencil, Ji-ho.'],
    ['지호','No!'],
    ['T','You have the pencil, Min-su.'],
    ['민수','Yes! (연필을 보여 준다)'],
    ['T','Min-su, you are the guesser now.'],
    ['결과','고학년은 "Do you have the pencil?" 의문문으로 바꾼다. 포커페이스 연습이 재미 포인트.']]},
  check:['이름을 넣어 You have the pencil, ___. 를 또렷이 말하는가.','Yes/No 뒤에 I have it. / I don\'t have it. 까지 말할 수 있는가.'],
  mats:[['roles',F.names],['dialog',{title:'대화 카드 — 연필 숨기기',lines:[['술래','You have the pencil, Min-ho.','민호, 네가 연필 가졌지.'],['S','No. / No, I don\'t.','아니.'],['술래','You have the pencil, Seo-yeon.','서연, 네가 연필 가졌지.'],['S','Yes! / Yes, I do.','응!']]}]] },
'What do I have?': {
  ex:{set:'초3 10명 · 전체 · 과일 카드', lines:[
    ['T','(오렌지 카드를 1초만 보여 주고 감춘다) What do I have?'],
    ['민수','An apple?'],
    ['T','No.'],
    ['서연','A peach?'],
    ['T','No.'],
    ['지호','An orange?'],
    ['T','Yes, that\'s right! (카드를 보여 준다)'],
    ['결과','카드 2장을 동시에 보여 주면 "An apple and a banana?" 로 and 연습이 된다.']]},
  check:['a/an을 구분해 말하는가.','본 것을 기억해 추측하는가(아무거나 말하지 않기).'],
  mats:[['cards',{cat:'Fruits'}]] },
"What's it?": {
  ex:{set:'초3 8명 · 모둠 · 구멍 덮개 카드 + 장난감 카드', lines:[
    ['T','We have a mystery game! (덮개 카드 아래 로봇 카드를 끼운다) What\'s it?'],
    ['민수','(구멍으로 보이는 은색 부분을 보고) It\'s a… car?'],
    ['T','No. Move the window. (덮개를 조금 민다)'],
    ['서연','It\'s a robot!'],
    ['T','Yes! Now, bag time. What\'s in the bag? (가방을 살짝 벌린다)'],
    ['지호','It\'s a ball in the bag!'],
    ['결과','덮개 카드는 색지에 지름 2cm 구멍을 뚫어 만든다(M 덮개 도안 포함).']]},
  check:['It\'s a ~. 로 추측을 말하는가.','It\'s a robot in the bag. 처럼 위치구를 덧붙일 수 있는가.'],
  mats:[['peek'],['cards',{cat:'Toys'}]] },
'What is it? (House)': {
  ex:{set:'초4 10명 · 전체 · 집 평면도 + 포스트잇', lines:[
    ['상황','평면도 각 방을 포스트잇으로 가려 둔다.'],
    ['T','(부엌 포스트잇을 반만 떼며) What\'s this?'],
    ['민수','It\'s the… bathroom?'],
    ['T','Look again. (냉장고가 보인다)'],
    ['서연','It\'s the kitchen!'],
    ['T','Right! Next room.'],
    ['결과','방 이름 카드 6장을 평면도에 붙이는 활동으로 마무리.']]},
  check:['방 이름 앞에 the를 붙여 말하는가.','방 안 물건(bed, sofa, fridge)으로 추론하는가.'],
  mats:[['house']] },
'Smell Game': {
  ex:{set:'초4 14명 · 2팀 · 컵 4개(식초·사과·커피·비누)', lines:[
    ['T','Team Apple, Min-su. Put on the blindfold. Smell this.'],
    ['민수','(냄새를 맡는다)'],
    ['T','What\'s this?'],
    ['민수','It\'s… vinegar!'],
    ['T','Yes! One point. Team Star, Seo-yeon.'],
    ['서연','It\'s an apple!'],
    ['결과','알레르기를 미리 확인하고 자극적인 재료는 피한다. 4라운드 후 점수 합산.']]},
  check:['It\'s ~. 문장으로 답하는가.','냄새 맡는 친구를 조용히 기다리는가.'],
  mats:[['cards',{items:F.smells,title:'냄새 재료 카드 (준비·정답 확인용)'}],['score','team']] },
'I can see something': {
  ex:{set:'초3 8명 · 모둠', lines:[
    ['T','I can see something red.'],
    ['민수','Is it a sweater?'],
    ['T','No, it isn\'t.'],
    ['서연','Is it an apple?'],
    ['T','Yes, it is! Seo-yeon, you spy now.'],
    ['서연','I can see something blue.'],
    ['지호','Is it the door?'],
    ['결과','색 카드를 뽑아 그 색의 물건을 찾게 하면 교실 어디서나 가능.']]},
  check:['something + 색 어순을 지키는가.','Is it ~? / Yes, it is. / No, it isn\'t. 세트가 자연스러운가.'],
  mats:[['cards',{cat:'Colors'}],['dialog',{title:'대화 카드 — I spy',lines:[['A','I can see something red.','빨간 무언가가 보여.'],['B','Is it a sweater?','스웨터야?'],['A',"No, it isn't.",'아니.'],['B','Is it an apple?','사과야?'],['A','Yes, it is!','응!']]}]] },
'Whisper Game': {
  ex:{set:'초3 10명 · 전체', lines:[
    ['T','(인호에게 귓속말) A bag.'],
    ['수미','Is it a pencil?'],
    ['인호','No, it isn\'t.'],
    ['남수','Is it a notebook?'],
    ['인호','No, it isn\'t.'],
    ['미영','Is it a bag?'],
    ['인호','Yes, that\'s right!'],
    ['T','Mi-yong, come here. (귓속말) A ruler.'],
    ['결과','범주(School things)를 미리 알려 주면 질문이 빨라진다.']]},
  check:['Is it a ~? 로 묻는가.','귓속말을 들은 학생이 표정으로 힌트를 주지 않는가.'],
  mats:[['cards',{cat:'School things'}],['dialog',{title:'대화 카드 — Whisper Game',lines:[['S','Is it a pencil?','연필이야?'],['리더',"No, it isn't.",'아니.'],['S','Is it a bag?','가방이야?'],['리더',"Yes, that's right.",'응, 맞아.']]}]] },
'Weather Guessing': {
  ex:{set:'초3 10명 · 분단 · 우산·선글라스·장갑', lines:[
    ['T','(민수에게 귓속말) Rainy.'],
    ['민수','How\'s the weather? (우산을 펴고 떨어지는 빗방울을 피하는 시늉)'],
    ['서연','It\'s rainy!'],
    ['T','Yes! Seo-yeon, come here. (귓속말) Windy.'],
    ['서연','How\'s the weather? (머리카락이 날리는 시늉)'],
    ['지호','It\'s windy!'],
    ['결과','날씨 카드를 뽑아 표현하게 하면 교사가 귓속말할 필요가 없다.']]},
  check:['It\'s + 날씨 형용사 형태로 답하는가.','How\'s the weather? 질문을 대표 학생이 먼저 하는가.'],
  mats:[['cards',{cat:'Weather'}],['dialog',{title:'대화 카드 — How\'s the weather?',lines:[['대표',"How's the weather?",'날씨가 어때?'],['S',"It's sunny!",'맑아!'],['S',"It's rainy! / cloudy! / windy! / snowy!",'비 와! / 흐려! / 바람 불어! / 눈 와!']]}]] },
'Where is my book?': {
  ex:{set:'초4 10명 · 분단 · 그림 종이', lines:[
    ['상황','각자 좋아하는 물건을 책상 위/아래, 의자 위/아래, 상자 위/안 중 한 곳에 그린다.'],
    ['T','Min-su, you are "it". Come here. Seo-yeon, stand behind him.'],
    ['서연','(그림을 들어 반 친구들에게 보인 뒤) Where is my book?'],
    ['민수','It\'s on the desk.'],
    ['Ss','No!'],
    ['민수','It\'s under the chair.'],
    ['Ss','Yes!'],
    ['T','Seo-yeon is "it" now.'],
    ['결과','전치사 카드(on/in/under)를 먼저 익힌 뒤 하면 답이 빨라진다.']]},
  check:['It\'s on/in/under the ~. 어순을 지키는가.','그림을 그릴 때 위치를 분명하게 그리는가.'],
  mats:[['preps'],['worksheet','position'],['dialog',{title:'대화 카드 — Where is my ~?',lines:[['S','Where is my book?','내 책이 어디 있어?'],['술래',"It's on the desk.",'책상 위에 있어.'],['Ss','No! / Yes!','아니! / 맞아!'],['술래',"It's under the chair.",'의자 아래에 있어.']]}]] },
'Hide and Seek': {
  ex:{set:'초3 10명 · 전체 · 교실', lines:[
    ['T','Let\'s play hide and seek. In-ho, you count.'],
    ['인호','(눈을 감고) One, two, three, four, five! Ready.'],
    ['상황','수미가 책상 아래에 숨었다.'],
    ['Ss','Where is Su-mi?'],
    ['인호','Under the desk.'],
    ['Ss','Yes, that\'s right!'],
    ['결과','교실이 좁으면 인형을 숨기고 찾는다. 숨은 곳을 말로만 추측하게 하면 전치사가 반복된다.']]},
  check:['Under/behind/in 등 전치사를 정확히 쓰는가.','다섯까지 영어로 세는가.'],
  mats:[['preps'],['dialog',{title:'대화 카드 — Hide and Seek',lines:[['T',"Let's play hide and seek.",'숨바꼭질하자.'],['술래','One, two, three, four, five! Ready.','하나, 둘… 다섯! 준비.'],['Ss','Where is Su-mi?','수미는 어디 있어?'],['술래','Under the desk. / Behind the door.','책상 아래. / 문 뒤.'],['Ss',"No. / Yes, that's right!",'아니. / 맞아!']]}]] },
'Ring a number': {
  ex:{set:'초3 짝 활동 · 바둑알 10개', lines:[
    ['진호','(바둑알 3개를 쥐고) Na-ri, how many coins do you have… I mean, how many?'],
    ['나리','Five!'],
    ['진호','No. (손을 펴며) Three coins. My point!'],
    ['나리','(이번엔 나리가 쥔다) How many?'],
    ['진호','Two?'],
    ['나리','Yes! Two coins. Your point.'],
    ['결과','3회씩 번갈아 하고 점수표에 기록. 1~10 수를 자동으로 말하게 된다.']]},
  check:['How many ~? 뒤에 복수 명사를 쓰는가(coins).','수를 영어로 즉시 말하는가.'],
  mats:[['score','pair'],['nums',{from:1,to:12}]] },
'Consensus': {
  ex:{set:'초3 8명 · 분단 · 1~10 숫자 카드', lines:[
    ['A','(카드를 꺼내 감추고) How many apples?'],
    ['B','I have three apples.'],
    ['A','No. Up!'],
    ['B','Seven!'],
    ['A','Down!'],
    ['B','Five apples!'],
    ['A','Yes! (카드 5를 보여 준다)'],
    ['결과','맞힌 B가 출제자가 된다. Up/Down 힌트를 주면 빨리 끝난다.']]},
  check:['I have + 수 + 복수 명사 문장을 말하는가.','Up/Down 힌트를 듣고 수를 조정하는가.'],
  mats:[['nums',{from:1,to:12}],['dialog',{title:'대화 카드 — How many apples?',lines:[['A','How many apples?','사과가 몇 개야?'],['B','I have three apples. / Three.','세 개야.'],['A','Up! / Down!','더 많아! / 더 적어!'],['A','Yes! That\'s right.','응! 맞았어.']]}]] },
// ───────── C ─────────
'TPR Game': {
  ex:{set:'초3 6명 팀 · 주장 1명', lines:[
    ['상황','주장 민수가 명령어 카드 더미를 들고 팀 앞에 선다.'],
    ['민수','(카드를 보고) Point to the door!'],
    ['팀원','(모두 문을 가리킨다. 지호가 가장 늦다)'],
    ['민수','Ji-ho, out! … Jump three times!'],
    ['팀원','(세 번 뛴다)'],
    ['민수','Clap your hands twice!'],
    ['상황','마지막까지 남은 서연이 다음 주장이 된다.'],
    ['결과','탈락한 학생은 "심판"이 되어 누가 늦었는지 판정하며 끝까지 참여.']]},
  check:['명령을 듣고 1초 안에 몸이 움직이는가(이해 확인).','주장이 카드를 또렷하게 읽는가.'],
  mats:[['cue',{title:'명령어 카드 1 — TPR',lines:[['Stand up.','일어서세요','🧍'],['Sit down.','앉으세요','🪑'],['Point to the door.','문을 가리키세요','🚪'],['Jump three times.','세 번 뛰세요','🦘'],['Clap your hands twice.','손뼉 두 번','👏'],['Touch your nose.','코를 만지세요','👃'],['Raise your left hand.','왼손을 드세요','✋'],['Turn around.','한 바퀴 도세요','🔄']]}],['cue',{title:'명령어 카드 2 — TPR',lines:[['Open your book.','책을 펴세요','📖'],['Close your eyes.','눈을 감으세요','🙈'],['Go to the desk.','책상으로 가세요','🚶'],['Put the book on the desk.','책을 책상 위에','📘'],['Sing a song.','노래하세요','🎵'],['Walk slowly.','천천히 걸으세요','🐢'],['Shake hands.','악수하세요','🤝'],['Say hello.','인사하세요','👋']]}]] },
'Commands': {
  ex:{set:'초3 분단 5명 · 리더 1명', lines:[
    ['서연','(리더) Open your book.'],
    ['Ss','(책을 편다)'],
    ['서연','Close your book. … Stand up!'],
    ['Ss','(일어선다. 도윤이 가장 늦음)'],
    ['서연','Do-yun, out!'],
    ['도윤','(심판석으로 가서 앉는다)'],
    ['결과','맨 마지막까지 남은 하은이 리더가 되어 다시 시작.']]},
  check:['Open/Close, Stand/Sit 짝 명령을 구분해 듣는가.','리더가 속도를 점점 올리는가.'],
  mats:[['cue',{title:'교실 명령어 카드',lines:[['Open your book.','책을 펴세요','📖'],['Close your book.','책을 덮으세요','📕'],['Stand up.','일어서세요','🧍'],['Sit down.','앉으세요','🪑'],['Raise your hand.','손을 드세요','✋'],['Clap your hands.','손뼉 치세요','👏'],['Turn around.','돌아서세요','🔄'],['Touch your head.','머리를 만지세요','🙆']]}]] },
'Please Game': {
  ex:{set:'초3 10명 · 전체', lines:[
    ['T','Please, stand up.'],
    ['Ss','(일어선다)'],
    ['T','Sit down.'],
    ['민수','(앉는다)'],
    ['T','Min-su, no "please"! You\'re out. Please, touch your nose.'],
    ['Ss','(코를 만진다)'],
    ['T','Jump!'],
    ['Ss','(아무도 움직이지 않는다) Yes!'],
    ['결과','끝까지 남은 3명에게 스티커. 틀린 학생은 동물 춤 한 번.']]},
  check:['please 유무를 듣고 움직임을 멈출 수 있는가(억제력).','Simon says 버전으로 바꾸어도 규칙을 이해하는가.'],
  mats:[['cue',{title:'Please 게임 명령어 카드 (please 있음 ✔ / 없음 ✖ 섞어 읽기)',lines:[['Please, stand up.','일어서세요 ✔','✅'],['Sit down.','앉으세요 ✖ (움직이면 탈락)','⛔'],['Please, touch your nose.','코를 만지세요 ✔','✅'],['Jump!','뛰세요 ✖','⛔'],['Please, clap your hands.','손뼉 치세요 ✔','✅'],['Turn around.','돌아서세요 ✖','⛔'],['Please, raise your hand.','손을 드세요 ✔','✅'],['Close your eyes.','눈을 감으세요 ✖','⛔']]}],['roles',[['🎩','Simon','사이먼(리더)'],['🧢','Tom','톰(리더)']]]] },
'Opposite Game': {
  ex:{set:'초5 7명 모둠 · 전체 앞에서', lines:[
    ['T','Touch your left ear.'],
    ['Ss','(오른쪽 귀를 만진다. 민수만 왼쪽 귀)'],
    ['T','Min-su, out! Don\'t touch your nose.'],
    ['Ss','(코를 만진다)'],
    ['T','Raise your left hand.'],
    ['Ss','(오른손을 든다)'],
    ['T','Don\'t sit down!'],
    ['Ss','(앉는다)'],
    ['결과','부정 명령문 Don\'t ~ 를 배운 직후에 하면 "반대로 하기"가 곧 이해 확인이 된다.']]},
  check:['left/right를 구분하는가.','Don\'t ~ 명령을 긍정 행동으로 바꾸는가.'],
  mats:[['cue',{title:'청개구리 명령어 카드 (왼쪽: 교사가 말함 → 오른쪽: 학생이 할 행동)',lines:[['Touch your left ear.','→ 오른쪽 귀 만지기','👂'],["Don't touch your nose.",'→ 코 만지기','👃'],['Raise your left hand.','→ 오른손 들기','🖐️'],["Don't sit down.",'→ 앉기','🪑'],['Stand up.','→ 앉아 있기','🧍'],['Open your eyes.','→ 눈 감기','🙈'],["Don't clap.",'→ 손뼉 치기','👏'],['Look up.','→ 아래 보기','👇']]}]] },
'Action Chains': {
  ex:{set:'초5 2팀 · 책상 앞에 책·연필·가방·병', lines:[
    ['T','Team Apple, Min-su. Listen. Stand up. Go to the desk. Put the book on the desk. Put the pencil on the book.'],
    ['민수','(일어나서 책상으로 가 책을 놓고 그 위에 연필을 놓는다)'],
    ['T','Perfect! Four actions, four points. Team Star, Seo-yeon.'],
    ['T','Stand up. Go to the desk. Put the bag under the desk. Open the book.'],
    ['서연','(가방을 책상 위에 놓는다)'],
    ['T','Under the desk! Three points.'],
    ['결과','팀원 모두의 점수를 합산해 순위를 정한 뒤 시상.']]},
  check:['지시 3~4개를 순서대로 기억하는가(작업 기억).','on/under/in 전치사를 행동으로 구분하는가.'],
  mats:[['cue',{title:'명령 연쇄 카드 (한 장에 한 묶음)',lines:[['Stand up. → Go to the desk. → Put the book on the desk.','일어나 → 책상으로 → 책을 책상 위에','1️⃣'],['Stand up. → Go to the desk. → Put the pencil on the book.','일어나 → 책상으로 → 연필을 책 위에','2️⃣'],['Stand up. → Go to the chair. → Put the bag under the chair.','일어나 → 의자로 → 가방을 의자 아래에','3️⃣'],['Go to the desk. → Open the book. → Close the book. → Sit down.','책상으로 → 책 펴기 → 덮기 → 앉기','4️⃣'],['Take the bottle. → Put it in the bag. → Give the bag to me.','병을 들어 → 가방에 넣어 → 나에게 줘','5️⃣'],['Touch the desk. → Touch the chair. → Touch the door. → Come back.','책상 → 의자 → 문 만지기 → 돌아오기','6️⃣'],['Pick up the pencil. → Put it on the chair. → Jump twice.','연필을 집어 → 의자 위에 → 두 번 뛰기','7️⃣'],['Stand up. → Turn around. → Sit down. → Say "Done!"','일어나 → 돌아 → 앉아 → "Done!"','8️⃣']]}],['score','team']] },
'Driving Game': {
  ex:{set:'초5 8명 팀 · 책상을 치운 넓은 공간', lines:[
    ['상황','8명이 일렬로 서서 왼손을 앞사람 오른쪽 어깨에 올린다. 맨 뒤 민수만 눈을 뜬다.'],
    ['T','(민수에게) Go.'],
    ['민수','(앞사람 등을 두드린다 → 앞으로 전달 → 맨 앞사람이 걷기 시작)'],
    ['T','Turn right!'],
    ['민수','(앞사람 오른쪽 어깨를 친다 → 전달 → 맨 앞이 오른쪽으로)'],
    ['T','Sit down!'],
    ['상황','머리 만지기 신호가 전달되어 모두 앉는다.'],
    ['결과','목표 지점(GOAL 표지)에 먼저 닿은 팀 승리. 반드시 천천히, 책상 없는 공간에서.']]},
  check:['신호 규칙 5개를 몸으로 정확히 전달하는가.','소리를 내지 않고 신호만으로 전달하는가.'],
  mats:[['cue',{title:'Driving Game 신호 카드',lines:[['Go!','앞으로 전진 → 신호: 등 두드리기','🚗'],['Turn right!','오른쪽으로 → 신호: 오른쪽 어깨 치기','➡️'],['Turn left!','왼쪽으로 → 신호: 왼쪽 어깨 치기','⬅️'],['Sit down!','앉기 → 신호: 머리 만지기','⬇️'],['Stand up!','서기 → 신호: 엉덩이 두드리기','⬆️'],['Stop!','멈추기 → 신호: 어깨 꽉 잡기','✋']]}],['signs',[['START','#3f9a48','출발선'],['GOAL','#c9507a','도착 지점']]]] },
'This is My Shoe. Game': {
  ex:{set:'초5 10명 · 한 줄', lines:[
    ['상황','술래 민수가 줄 앞을 오가다 서연을 지명.'],
    ['민수','(자기 셔츠를 가리키며) This is my shoe.'],
    ['서연','(신발을 가리키며) This is my shirt!'],
    ['T','Correct! Next.'],
    ['민수','(모자를 가리키며) This is my sock.'],
    ['지호','(양말을 가리키며) This is my… hat!'],
    ['상황','3초 안에 못 하면 술래 교체. 지호 성공.'],
    ['결과','신체 부위(nose/ear)로 바꾸면 코코코 놀이와 연결된다.']]},
  check:['가리키는 것과 말하는 것을 바꾸어 즉시 반응하는가.','my + 옷 이름을 정확히 말하는가.'],
  mats:[['cards',{cat:'Clothes'}],['dialog',{title:'대화 카드 — 거꾸로 말하기',lines:[['술래','(셔츠를 가리키며) This is my shoe.','이건 내 신발이야.'],['S','(신발을 가리키며) This is my shirt.','이건 내 셔츠야.'],['술래','(모자를 가리키며) This is my sock.','이건 내 양말이야.'],['S','(양말을 가리키며) This is my hat.','이건 내 모자야.']]}]] },
'What day is it today?': {
  ex:{set:'초4 10명 · 전체 · 칠판에 요일 카드 7장', lines:[
    ['T','(Monday를 가리키며) If it\'s Monday, stand up.'],
    ['Ss','(일어선다)'],
    ['T','(Tuesday를 가리키며) If it\'s Tuesday, point to your nose.'],
    ['Ss','(코를 가리킨다)'],
    ['T','(Wednesday를 가리키며) If it\'s Thursday, sing a song.'],
    ['민수','(노래를 시작한다)'],
    ['T','Oh! I pointed to Wednesday. Min-su, out!'],
    ['결과','"If"의 뜻을 먼저 이해시킨다. 가리킨 요일과 말한 요일이 다르면 움직이지 않는 것이 핵심.']]},
  check:['요일 7개를 듣고 구분하는가.','조건이 맞지 않을 때 움직임을 멈추는가.'],
  mats:[['days'],['cue',{title:'요일 조건 명령 카드',lines:[["If it's Monday, stand up.",'월요일이면 일어서기','🌙'],["If it's Tuesday, point to your nose.",'화요일이면 코 가리키기','🔥'],["If it's Wednesday, sit down.",'수요일이면 앉기','💧'],["If it's Thursday, sing a song.",'목요일이면 노래하기','🌳'],["If it's Friday, play basketball.",'금요일이면 농구 시늉','⭐'],["If it's Saturday, let's dance.",'토요일이면 춤추기','🏔️'],["If it's Sunday, sleep.",'일요일이면 자는 시늉','☀️'],['What day is it today?','오늘은 무슨 요일?','📅']]}]] },
'Koko-ko Game': {
  ex:{set:'초3 분단 · 리더 1명', lines:[
    ['서연','(코를 가리키며) Nose, nose, nose… ears!'],
    ['Ss','(귀를 가리킨다. 민수는 눈을 가리킴)'],
    ['서연','Min-su, you\'re the leader!'],
    ['민수','Nose, nose, nose… (눈을 가리키며) mouth!'],
    ['Ss','(입을 가리킨다)'],
    ['결과','리더가 손으로는 다른 곳을 가리키며 말하면 난이도가 올라간다.']]},
  check:['말한 부위(소리)를 따라가고 손(시각)에 속지 않는가.','eyes, ears 복수형을 들을 수 있는가.'],
  mats:[['faceposter']] },
'Basket Game': {
  ex:{set:'초3 10명 · 2팀 · 바구니 2개', lines:[
    ['T','(시범) Pick up a ruler. (자를 집는다) Pick up!'],
    ['상황','두 팀 대표가 등을 대고 선다. 각자 앞에 바구니.'],
    ['T','Pick up a pencil.'],
    ['민수·서연','(각자 바구니에서 연필을 꺼내 든다)'],
    ['T','Min-su first! One point. Put it back. Pick up an eraser.'],
    ['결과','꺼낸 물건은 다시 넣고 다음 대표로 교체. 10라운드 후 합산.']]},
  check:['pick up의 뜻을 행동으로 이해하는가.','a/an 뒤의 물건 이름을 정확히 듣는가.'],
  mats:[['cards',{cat:'School things'}],['cue',{title:'Pick up 지시 카드',lines:[['Pick up a ruler.','자를 집으세요','📏'],['Pick up a pencil.','연필을 집으세요','✏️'],['Pick up a book.','책을 집으세요','📘'],['Pick up a bag.','가방을 집으세요','🎒'],['Pick up a crayon.','크레용을 집으세요','🖍️'],['Pick up a notebook.','공책을 집으세요','📓'],['Pick up a pen.','펜을 집으세요','🖊️'],['Pick up the scissors.','가위를 집으세요','✂️']]}],['score','team']] },
'Speed Game (Objects)': {
  ex:{set:'초3 12명 · 2팀(6명) · 교실 전체', lines:[
    ['T','Bring me a red pencil!'],
    ['상황','각 팀 대표가 팀원들과 함께 교실을 뒤진다.'],
    ['민수','Here! (빨간 색연필을 들어 올린다)'],
    ['T','Team Apple, one point! Bring me something blue!'],
    ['서연','Here! (파란 색종이)'],
    ['결과','"Bring me something + 색" 으로 바꾸면 어떤 교실에서도 가능. 달리기 안전 주의.']]},
  check:['물건 이름과 색을 함께 듣는가.','Here! 하고 보여 주며 영어로 말하는가.'],
  mats:[['cue',{title:'Bring me ~ 지시 카드',lines:[['Bring me a red pencil.','빨간 연필','✏️'],['Bring me a book.','책','📘'],['Bring me something blue.','파란 것 아무거나','🟦'],['Bring me a pair of scissors.','가위','✂️'],['Bring me a bag.','가방','🎒'],['Bring me something round.','둥근 것','⚪'],['Bring me a ruler.','자','📏'],['Bring me something yellow.','노란 것','🟨']]}],['score','team']] },
'Draw It Here': {
  ex:{set:'초4 짝 활동 · 같은 그림 1장씩', lines:[
    ['T','Draw a pencil on the desk.'],
    ['Ss','(책상 위에 연필을 그린다)'],
    ['T','Draw a nose on the face.'],
    ['T','Draw two apples in the bag.'],
    ['민수','(가방 옆에 사과를 그린다)'],
    ['T','In the bag! Inside! Draw a banana under the chair.'],
    ['T','Compare with your partner. Same?'],
    ['결과','짝끼리 서로 지시를 주고받으면 Information Gap 활동이 된다.']]},
  check:['on/in/under를 그림 위치로 구분하는가.','two apples 처럼 수량을 듣고 그리는가.'],
  mats:[['scene','drawit'],['cue',{title:'Draw ~ 지시 카드',lines:[['Draw a pencil on the desk.','책상 위에 연필','✏️'],['Draw a nose on the face.','얼굴에 코','👃'],['Draw two apples in the bag.','가방 안에 사과 2개','🍎'],['Draw a banana under the chair.','의자 아래 바나나','🍌'],['Draw a book under the desk.','책상 아래 책','📘'],['Draw two eyes on the face.','얼굴에 눈 2개','👀'],['Draw a cat on the chair.','의자 위에 고양이','🐱'],['Draw a ball in the bag.','가방 안에 공','⚽']]}]] },
'Drawing Race': {
  ex:{set:'초3 8명 · 2팀 대표 4명씩 칠판 앞', lines:[
    ['T','Draw a face. (5초 뒤) Draw a nose.'],
    ['Ss','(각자 칠판에 그린다)'],
    ['T','Draw two eyes. … Draw a mouth. … Draw two ears.'],
    ['T','Stop! Let\'s look. Min-su\'s face has… one ear!'],
    ['Ss','(웃음)'],
    ['결과','제일 빨리 정확히 그린 사람이 승리. 완성된 얼굴로 "그림 지우기 놀이"로 이어 간다.']]},
  check:['two eyes / two ears 수량을 지키는가.','5초 간격을 따라가는 집중력.'],
  mats:[['cue',{title:'Drawing Race 지시 카드 (5초 간격)',lines:[['Draw a face.','얼굴 윤곽','🙂'],['Draw a nose.','코','👃'],['Draw two eyes.','눈 2개','👀'],['Draw a mouth.','입','👄'],['Draw two ears.','귀 2개','👂'],['Draw hair.','머리카락','💇'],['Draw a hat.','모자','🧢'],['Draw a neck.','목','🧣']]}],['faceposter']] },
'Picture Drawing': {
  ex:{set:'초3 4명 칠판 앞', lines:[
    ['T','Draw a face.'],
    ['Ss','(그린다)'],
    ['T','Draw a nose. Draw an eye. Draw a mouth.'],
    ['T','Who has the funniest face? (반 아이들이 투표)'],
    ['결과','그릴 낱말을 학생이 부르게 하면 말하기 연습이 된다.']]},
  check:['a face / an eye 관사 구분을 듣는가.','낱말을 듣고 그림으로 옮기는가.'],
  mats:[['cue',{title:'그릴 낱말 카드',lines:[['a face','얼굴','🙂'],['a nose','코','👃'],['an eye','눈','👁️'],['a mouth','입','👄'],['an ear','귀','👂'],['hair','머리카락','💇'],['a hand','손','✋'],['a foot','발','🦶']]}],['score','team']] },
'Erase the Picture': {
  ex:{set:'초3 3팀(6명) · 칠판 3등분', lines:[
    ['T','Face!'],
    ['상황','각 팀 맨 앞사람이 얼굴 윤곽을 그리고 분필을 넘긴다.'],
    ['T','Two eyes! … Nose! … Mouth! … Two ears! … Hair!'],
    ['T','Done! Now turn around. Back to the board.'],
    ['T','Erase the nose!'],
    ['Ss','(돌아서서 코를 지운다)'],
    ['T','Erase the foot!'],
    ['민수','There is no foot!'],
    ['결과','빨리, 정확히 지운 팀이 승리. 없는 부위를 불러 함정을 만들면 집중도가 올라간다.']]},
  check:['신체 부위 낱말을 듣고 그리고 지우는가.','등지고 있다가 돌아서서 찾는 집중력.'],
  mats:[['cue',{title:'신체 부위 카드 (그리기 → 지우기)',lines:[['face','얼굴','🙂'],['two eyes','눈 2개','👀'],['nose','코','👃'],['mouth','입','👄'],['two ears','귀 2개','👂'],['hair','머리카락','💇'],['two arms','팔 2개','💪'],['two legs / a foot','다리 2개 / 발','🦵']]}],['faceposter']] },
'Board Race': {
  ex:{set:'초3 12명 · 3팀 · 칠판 아래 그림카드 12장', lines:[
    ['T','Rabbit!'],
    ['상황','각 팀 첫 번째 학생이 칠판으로 달려가 토끼 카드를 든다.'],
    ['지호','(가장 먼저) Rabbit!'],
    ['T','Team Star, one point! Next. Watermelon!'],
    ['결과','방식 2(카드 고르기)가 저학년에 쉽고, 방식 1(그리기)은 고학년에 재미있다.']]},
  check:['달려가기 전에 낱말을 끝까지 듣는가.','카드를 들고 낱말을 말하는가.'],
  mats:[['cards',{cat:'Animals'}],['cards',{cat:'Fruits'}],['score','team']] },
'Make a mask': {
  ex:{set:'초4 모둠 · 도화지(가면 도안)', lines:[
    ['T','Draw two ears and color them.'],
    ['Ss','(귀를 그리고 칠한다)'],
    ['T','Draw a red nose. Draw a black mouth.'],
    ['T','Now, cut the eyes. Put on your face!'],
    ['민수','(가면을 쓰고 짝에게) You have a red nose and a black mouth!'],
    ['서연','You have yellow hair! How many ears can you see?'],
    ['민수','Two!'],
    ['결과','"Tape your pencil to your mask." 로 손잡이를 만들면 역할놀이에 바로 쓸 수 있다.']]},
  check:['색 + 신체 부위 어순(a red nose)을 지키는가.','You have ~. 로 짝의 가면을 묘사하는가.'],
  mats:[['mask'],['cue',{title:'가면 만들기 지시 카드',lines:[['Draw two ears and color them.','귀 2개 그리고 색칠','👂'],['Draw a red nose.','빨간 코','🔴'],['Draw a black mouth.','검은 입','⚫'],['Draw yellow hair.','노란 머리','💛'],['Cut the eyes.','눈 오려내기','✂️'],['Put on your face.','가면 쓰기','🎭'],["Describe your partner's mask.",'짝의 가면 묘사하기','💬'],['Tape your pencil to your mask.','연필을 가면에 붙이기','📎']]}]] },
'Whisper Command': {
  ex:{set:'초3 4분단 · 분단당 5명', lines:[
    ['T','(각 분단 첫 학생에게 귓속말) Stand up, Min-ho.'],
    ['상황','뒤로 귓속말이 전달된다.'],
    ['마지막 S','(크게) Stand up, Min-ho!'],
    ['민호','(일어선다)'],
    ['T','Team 2, what did you hear?'],
    ['마지막 S','Sit down, Min-ho?'],
    ['T','Oh no! Team 1, one point.'],
    ['결과','명령에 이름을 넣어 듣는 사람 모두가 집중하게 한다.']]},
  check:['귓속말을 정확히 복창하는가.','이름이 불린 학생이 즉시 행동하는가.'],
  mats:[['cue',{title:'귓속말 명령 카드 (이름 칸에 반 학생 이름 넣기)',lines:[['Stand up, ______.','___, 일어서','🧍'],['Sit down, ______.','___, 앉아','🪑'],['Touch your nose, ______.','___, 코 만져','👃'],['Clap three times, ______.','___, 세 번 손뼉','👏'],['Open the door, ______.','___, 문 열어','🚪'],['Jump twice, ______.','___, 두 번 뛰어','🦘'],['Turn around, ______.','___, 돌아','🔄'],['Say hello, ______.','___, 인사해','👋']]}]] },
"Champion's chair": {
  ex:{set:'초3 10명 · 청·백 2팀 · YES/NO 의자', lines:[
    ['상황','민수(청)와 서연(백)이 의자 둘레를 빙글빙글 돈다.'],
    ['T','I have two eyes.'],
    ['민수','(YES 의자에 먼저 앉는다)'],
    ['T','Yes! Blue team, one point. Next players.'],
    ['T','I have three noses.'],
    ['지호','(NO 의자에 앉는다)'],
    ['T','Right! White team, one point.'],
    ['결과','문장은 단원 내용(동물 특징, 날씨)으로 바꾼다. 참/거짓 문장 카드 12장 포함.']]},
  check:['문장을 끝까지 듣고 판단하는가(two/three 등 수).','의자에 앉은 뒤 문장을 따라 말하게 하면 더 좋다.'],
  mats:[['signs',[['YES','#3f9a48','사실이에요'],['NO','#c9507a','사실이 아니에요']]],['truefalse',{title:'참·거짓 문장 카드 (교사용)',lines:[['I have two eyes.',true],['I have three noses.',false],['A cat says "Moo."',false],['A dog has four legs.',true],['An apple is a fruit.',true],['A banana is blue.',false],['We go to school on Sunday.',false],['Fish can swim.',true],['A rabbit has long ears.',true],['The sun is cold.',false],['Pigs can fly.',false],['Monday comes after Sunday.',true]]}]] },
'O, X Game': {
  ex:{set:'초3 12명 · 3조 · 교실 양쪽에 O/X 표지', lines:[
    ['T','(코를 만지며) I touch my nose.'],
    ['Ss','(O 쪽으로 이동)'],
    ['T','(귀를 만지며) I touch my nose.'],
    ['민수','(O 쪽으로 간다)'],
    ['T','Look! Ear! It\'s X. Min-su, sit down.'],
    ['T','(뛰며) I jump!'],
    ['결과','맨 마지막까지 남은 아동들에게 점수. 야외에서는 모든 조원이 한꺼번에 참여.']]},
  check:['말과 동작이 다를 때 X를 고르는가(듣기 우선).','I touch my ~. 문장을 따라 말할 수 있는가.'],
  mats:[['signs',[['O','#2f6fcb','맞아요 Right!'],['X','#c9507a','틀려요 Wrong!']]],['truefalse',{title:'말·동작 문장 카드 (교사용 — 동작을 일부러 다르게)',lines:[['I touch my nose.',true],['I touch my ear.',true],['I clap my hands.',true],['I jump.',true],['I open my book.',true],['I close my eyes.',true],['I raise my left hand.',true],['I sit down.',true],['I point to the door.',true],['I touch my head.',true],['I stand up.',true],['I turn around.',true]]}]] },

// ───────── D ─────────
'Snowball Game': {
  ex:{set:'초3 5명 모둠 · 과일 카드 힌트', lines:[
    ['민수','Apples.'],
    ['서연','Apples and bananas.'],
    ['지호','Apples, bananas and pears.'],
    ['하은','Apples, bananas, pears and… grapes!'],
    ['도윤','Apples, bananas, pears, grapes and peaches!'],
    ['민수','Apples, bananas, grapes… (막힘)'],
    ['모둠','Pears!'],
    ['결과','6개를 넘기면 박수. 틀리면 처음부터 다시 시작하되 벌칙은 없다.']]},
  check:['and의 위치(마지막 항목 앞)를 지키는가.','복수형(-s)을 붙이는가.'],
  mats:[['cards',{cat:'Fruits'}],['cards',{cat:'Animals'}]] },
'Memory chain': {
  ex:{set:'초3 4명 분단 · 장난감 카드', lines:[
    ['민수','I want a doll.'],
    ['서연','I want a doll and a robot.'],
    ['지호','I want a doll, a robot and a car.'],
    ['하은','I want a doll, a robot, a car and a ball.'],
    ['민수','I want a doll, a robot, a car, a ball and a train!'],
    ['결과','순서를 바꾸어 다시 시작. I like ~ / I have ~ 패턴으로도 바꾼다.']]},
  check:['I want a ~. 문장 틀을 유지하며 목적어만 늘리는가.','관사 a를 매 명사 앞에 붙이는가.'],
  mats:[['cards',{cat:'Toys'}],['dialog',{title:'문장 카드 — I want ~',lines:[['S1','I want a doll.','나는 인형을 원해.'],['S2','I want a doll and a robot.','인형과 로봇'],['S3','I want a doll, a robot and a car.','인형, 로봇, 자동차'],['S4','I want a doll, a robot, a car and a ball.','…그리고 공']]}]] },
'Add-on Game': {
  ex:{set:'초6 5명 팀', lines:[
    ['T','I have a dog.'],
    ['민수','I have a big dog.'],
    ['서연','I have a big black dog.'],
    ['지호','I have a big black dog in my house.'],
    ['하은','I have a big black dog in my house, and his name is Max.'],
    ['T','Wow, five words to fifteen words!'],
    ['결과','형용사 → 장소 → 시간 순으로 확장 힌트를 주면 어순 감각이 생긴다.']]},
  check:['형용사를 명사 앞에 넣는가(big black dog).','덧붙인 뒤에도 문장이 문법적으로 맞는가.'],
  mats:[['cue',{title:'시작 문장 카드',lines:[['I have a dog.','나는 개가 있다','🐶'],['I like pizza.','나는 피자를 좋아한다','🍕'],['She is a teacher.','그녀는 선생님이다','👩‍🏫'],['We play soccer.','우리는 축구를 한다','⚽'],['He can swim.','그는 수영할 수 있다','🏊'],['It is a cat.','그것은 고양이다','🐱'],['I go to school.','나는 학교에 간다','🏫'],['They eat lunch.','그들은 점심을 먹는다','🍱']]}],['worksheet','addon']] },
'Whisper Chain': {
  ex:{set:'초3 2팀(7명) · 숫자 카드', lines:[
    ['T','(1번 학생들에게 카드 17을 보여 준다) Go!'],
    ['민수','(자기 팀 2번에게 귓속말) Seventeen.'],
    ['상황','7번까지 전달. 마지막 학생이 칠판으로 달려간다.'],
    ['마지막 S','(칠판에) 17'],
    ['T','Team Apple, seventeen. Correct! Team Star?'],
    ['마지막 S','(칠판에) 70'],
    ['T','Seventy? Oh, seventeen! Listen carefully next time.'],
    ['결과','-teen / -ty 혼동이 자연스럽게 드러나 지도 포인트가 된다.']]},
  check:['thirteen/thirty 등 -teen/-ty를 구분해 발음하는가.','귓속말을 또렷하게 하되 옆 팀에 들리지 않게 하는가.'],
  mats:[['nums',{from:0,to:20}]] },
'Pass the word': {
  ex:{set:'초3 2팀(8명) · 동물 낱말', lines:[
    ['T','(두 팀 첫 학생에게 귓속말) Elephant.'],
    ['상황','뒤로 귓속말 전달.'],
    ['마지막 S','Elephant!'],
    ['T','Team Star first! One point. Next word… (귓속말) A red apple.'],
    ['마지막 S','A red apple!'],
    ['결과','단어 → 두 단어 → 짧은 문장으로 전달 단위를 늘린다.']]},
  check:['낱말을 정확히 발음하여 전달하는가.','마지막 학생이 크고 또렷하게 말하는가.'],
  mats:[['cards',{cat:'Animals'}]] },
'Greeting Relay': {
  ex:{set:'초3 6명 모둠 · 원형', lines:[
    ['민수','Good morning.'],
    ['서연','Good afternoon.'],
    ['지호','Good evening.'],
    ['하은','Good night! (잠자는 시늉, 빠진다)'],
    ['도윤','Good morning.'],
    ['예린','Good afternoon.'],
    ['민수','Good evening.'],
    ['서연','Good night! (빠진다)'],
    ['결과','마지막에 남은 1명이 벌칙(노래 한 소절). 요일·숫자로 바꿔도 된다.']]},
  check:['네 인사의 순서를 틀리지 않는가.','시간대와 인사를 연결해 이해하는가.'],
  mats:[['cue',{title:'인사 순서 카드',lines:[['Good morning.','아침 인사','🌅'],['Good afternoon.','오후 인사','☀️'],['Good evening.','저녁 인사','🌆'],['Good night.','밤 인사 (잠자기 → 빠짐)','🌙']]}]] },
'Seven Go Game': {
  ex:{set:'초4 10명 · 원형', lines:[
    ['상황','무릎–손뼉–주먹 3박자 연습 후 시작.'],
    ['Ss','(박자에 맞춰) One, two, three, four, five, six…'],
    ['7번 학생','Jump!'],
    ['상황','앞의 앞 사람(9번 자리)이 이어받는다.'],
    ['9번 학생','Eight!'],
    ['Ss','Nine, ten, eleven, twelve, thirteen…'],
    ['14번 차례','Back!'],
    ['결과','7과 7의 배수(14, 21)에서 명령하면 Buzz Game과 결합된다. 박자를 놓친 사람이 탈락.']]},
  check:['3박자 리듬을 유지하며 수를 세는가.','Go/Back/Jump에 따라 순서가 바뀌는 것을 이해하는가.'],
  mats:[['cue',{title:'Seven Go 명령 카드',lines:[['Go!','진행 방향 다음 사람이 이어받기','➡️'],['Back!','뒷사람(반대 방향)이 이어받기','⬅️'],['Jump!','앞의 앞 사람이 이어받기','⏭️'],['Seven! (금지)','7은 말하지 않고 명령으로 바꾸기','7️⃣']]}]] },
'Buzz Game': {
  ex:{set:'초4 10명 · 전체 · Buzz 수 = 3', lines:[
    ['T','Buzz number is three!'],
    ['Ss','One, two, Buzz, four, five, Buzz, seven, eight, Buzz, ten…'],
    ['민수','Eleven.'],
    ['서연','Twelve!'],
    ['T','Twelve is three times four. Buzz! Seo-yeon, out.'],
    ['결과','Buzz 수를 4, 5로 바꾸거나 Buzz 대신 단원 낱말을 쓴다.']]},
  check:['1~20을 영어로 끊김 없이 세는가.','배수에서 Buzz로 바꾸는가(수 감각).'],
  mats:[['board','numboard'],['cue',{title:'Buzz 수 카드',lines:[['Buzz number: 3','3, 6, 9, 12, 15, 18','3️⃣'],['Buzz number: 4','4, 8, 12, 16, 20','4️⃣'],['Buzz number: 5','5, 10, 15, 20','5️⃣'],['Buzz number: 7','7, 14, 21','7️⃣']]}]] },
// ───────── E ─────────
'Up and Down Game': {
  ex:{set:'초3 5명 팀 · 숫자 카드 0~20', lines:[
    ['T','(카드 7을 뽑아 감춘다) Guess the number.'],
    ['민수','Six.'],
    ['T','Up! (팔을 위로)'],
    ['서연','Nine.'],
    ['T','Down! (팔을 아래로)'],
    ['지호','Seven!'],
    ['T','Yes, that\'s right! Ji-ho, you pick a card.'],
    ['결과','학생이 UP/DOWN 표지를 들고 출제자가 되면 교사는 관찰에 집중할 수 있다.']]},
  check:['Up/Down 힌트를 듣고 범위를 좁히는가.','20까지의 수를 영어로 말하는가.'],
  mats:[['nums',{from:0,to:20}],['signs',[['UP ↑','#e07b2a','더 큰 수!'],['DOWN ↓','#7a57c9','더 작은 수!']]]] },
'Find the Number': {
  ex:{set:'초3 10명 · 2팀 대표 · 숫자판 1~20', lines:[
    ['T','Eleven, four, nineteen!'],
    ['민수·서연','(각자 색이 다른 마커로 숫자를 찾아 동그라미)'],
    ['T','Min-su: eleven, four… nineteen! Three. Seo-yeon: two. Next players!'],
    ['T','Twenty, one!'],
    ['결과','숫자가 다 끝났을 때 동그라미가 많은 팀이 승리. 지우기 게임으로 한 번 더.']]},
  check:['-teen과 -ty를 듣고 구분하는가(13/30).','1~3개의 숫자를 순서대로 기억하는가.'],
  mats:[['board','numboard'],['cue',{title:'숫자 낱말 카드 11~20',lines:[['eleven','11','1️⃣1️⃣'],['twelve','12','1️⃣2️⃣'],['thirteen','13','1️⃣3️⃣'],['fourteen','14','1️⃣4️⃣'],['fifteen','15','1️⃣5️⃣'],['sixteen','16','1️⃣6️⃣'],['seventeen','17','1️⃣7️⃣'],['eighteen · nineteen · twenty','18 · 19 · 20','2️⃣0️⃣']]}]] },
'Line Up by Number': {
  ex:{set:'초3 10명 한 조 · 사과 개수 카드 1~10', lines:[
    ['상황','접힌 카드를 한 장씩 집는다.'],
    ['민수','(서연에게) How many?'],
    ['서연','Four. How many?'],
    ['민수','Seven. You go there. (서연을 자기 앞쪽으로 보낸다)'],
    ['상황','1부터 10까지 일렬로 선다.'],
    ['Ss','(차례로) One, two, three … ten!'],
    ['Ss','(다 함께) Ten apples!'],
    ['결과','사과 대신 이미 배운 사물 이름을 활용해도 좋다.']]},
  check:['How many? 에 수로 답하는가.','수의 크기를 비교해 자리를 찾는가.'],
  mats:[['apples']] },
'How old are you?': {
  ex:{set:'초3 분단 · 숫자 카드 2벌(5~16)', lines:[
    ['민수','(카드 9를 들어 보이며) How old are you?'],
    ['서연','I\'m nine. (카드 7을 꺼내며) How old are you?'],
    ['지호','I\'m seven. How old are you?'],
    ['하은','I\'m twelve.'],
    ['T','Now, your real age! Min-su, how old are you?'],
    ['민수','I\'m ten years old.'],
    ['결과','카드 연습 후 실제 나이로 바꾸면 자기 소개로 연결된다.']]},
  check:['I\'m + 수. 로 답하는가.','years old까지 확장할 수 있는가.'],
  mats:[['nums',{from:5,to:16}],['dialog',{title:'대화 카드 — How old are you?',lines:[['A','How old are you?','몇 살이야?'],['B',"I'm nine.",'아홉 살이야.'],['B',"I'm ten years old.",'열 살이야.'],['A','Me too! / Oh, I\'m eleven.','나도! / 아, 나는 열한 살.']]}]] },
'Draw the Clock': {
  ex:{set:'초3 짝 활동 · 빈 시계 카드', lines:[
    ['민수','It\'s ten.'],
    ['서연','(바늘을 10시에 그린다) Ten o\'clock!'],
    ['서연','It\'s seven.'],
    ['민수','(바늘을 그리며) Breakfast time!'],
    ['서연','It\'s twelve.'],
    ['민수','Lunch time!'],
    ['결과','7·12·6시에는 Breakfast / Lunch / Dinner time을 덧붙이게 하면 생활과 연결된다.']]},
  check:['시침을 정확한 숫자에 그리는가.','It\'s ~ o\'clock 과 ~ time을 연결하는가.'],
  mats:[['clocks','blank'],['clocks','sentence']] },
'Time Matching': {
  ex:{set:'초3 2팀 · 시각 카드(1~12번) · 시계 카드(A~L)', lines:[
    ['상황','칠판 왼쪽에 시각 카드 12장(뒷면), 오른쪽에 빈 시계 카드 12장(뒷면).'],
    ['민수','Number seven!'],
    ['민수','(7번을 뒤집어 보이며) What time is it?'],
    ['Ss','It\'s seven o\'clock.'],
    ['서연','(시계 카드 C에 7시 바늘을 그려 앞면으로 붙인다)'],
    ['상황','모든 시계에 바늘을 그린 뒤 전부 뒤집는다. 짝 맞추기 시작.'],
    ['사과팀','Number three, E!'],
    ['T','(뒤집어 보이며) Three o\'clock… and E is three o\'clock! Match! One point.'],
    ['결과','모든 카드가 짝지어질 때까지 진행. 기억력과 시각 읽기가 동시에 연습된다.']]},
  check:['What time is it? / It\'s ~ o\'clock. 을 모두가 합창하는가.','번호·알파벳을 영어로 부르는가.'],
  mats:[['clocks','analog'],['clocks','sentence'],['score','team']] },
'Clock Bingo': {
  ex:{set:'초3 10명 · 전체 · 3×3 빙고판', lines:[
    ['상황','1~12 중 9개 숫자를 골라 빙고판에 쓴다(또는 미리 채워진 판 사용).'],
    ['Ss','What time is it?'],
    ['T','It\'s five o\'clock.'],
    ['Ss','(5에 ×표)'],
    ['Ss','What time is it?'],
    ['T','It\'s eleven o\'clock.'],
    ['민수','Bingo!'],
    ['T','Show me. Five, eleven, two… Bingo! Min-su, you call the time now.'],
    ['결과','교사 대신 학생이 시각을 부르게 하면 말하기 연습이 된다.']]},
  check:['질문을 학생이 먼저 하는가(What time is it?).','시각을 듣고 숫자를 찾는가.'],
  mats:[['bingo',{size:3,words:['1','2','3','4','5','6','7','8','9','10','11','12'],boards:4,title:'시계 빙고판 (미리 채운 4종)'}],['bingo',{size:3,blank:true}]] },
'Time Grid Game': {
  ex:{set:'초4 4명 팀 · Time Grid 게임판', lines:[
    ['민수','(주사위 3) One, two, three. (9:00 칸)'],
    ['나머지','What time is it?'],
    ['민수','It\'s nine o\'clock. I study.'],
    ['나머지','OK!'],
    ['서연','(주사위 5 → 2:00 칸)'],
    ['나머지','What time is it?'],
    ['서연','It\'s… two o\'clock. I… read a book!'],
    ['결과','틀리면 원래 자리로. 3학년은 시각만 말해도 인정.']]},
  check:['It\'s ~ o\'clock 뒤에 하는 일을 덧붙이는가.','나머지 학생이 질문자 역할을 하는가.'],
  mats:[['board','timegrid']] },
'Birthday Game': {
  ex:{set:'초3 10명 한 조 · ○× 쪽지', lines:[
    ['상황','접힌 쪽지를 각자 한 장씩 집는다. 하은이 ○.'],
    ['하은','Today\'s my birthday!'],
    ['Ss','Happy birthday!'],
    ['하은','Thank you.'],
    ['Ss','How old are you?'],
    ['하은','I\'m ten.'],
    ['Ss','(생일 노래 한 소절)'],
    ['결과','쪽지를 다시 접어 던지고 반복. 5라운드면 10분.']]},
  check:['Happy birthday! → Thank you. 응답이 자연스러운가.','How old are you? / I\'m ~. 를 주고받는가.'],
  mats:[['slips','ox'],['dialog',{title:'대화 카드 — 생일 축하',lines:[['○ 학생',"Today's my birthday!",'오늘 내 생일이야!'],['Ss','Happy birthday!','생일 축하해!'],['○ 학생','Thank you.','고마워.'],['Ss','How old are you?','몇 살이야?'],['○ 학생',"I'm ten.",'열 살이야.']]}]] },

// ───────── F ─────────
'Dice Game': {
  ex:{set:'초3 6명 팀 · 음식 주사위', lines:[
    ['민수','(던진다) It\'s pizza!'],
    ['T','Good! One point.'],
    ['서연','(던진다) It\'s a… hamburger!'],
    ['지호','It\'s ice cream!'],
    ['하은','(던진다) It\'s… (막힘)'],
    ['팀','Cake!'],
    ['하은','It\'s a cake!'],
    ['결과','점수표에 ○표. 2라운드는 동물 주사위로 바꾼다.']]},
  check:['셀 수 없는 음식(pizza, ice cream)에 a를 붙이지 않는가.','It\'s ~. 를 또렷하게 말하는가.'],
  mats:[['dice',[['🍔','hamburger'],['🍕','pizza'],['🍦','ice cream'],['🎂','cake'],['🍎','apple'],['🥛','milk']]],['dice',[['🐶','dog'],['🐱','cat'],['🐷','pig'],['🐮','cow'],['🐰','rabbit'],['🐯','tiger']]],['score','dice']] },
'Dice Game 2': {
  ex:{set:'초3 2팀(6명) · 음식 주사위', lines:[
    ['T','Ready… go!'],
    ['민수','(던진다) I like ice cream!'],
    ['서연','I like bananas!'],
    ['지호','I like… apples!'],
    ['상황','6명이 차례로 빠르게 던지고 말한다.'],
    ['사과팀','Finished!'],
    ['T','Team Apple first! Three points. Team Star, two points.'],
    ['결과','팀 전체가 빨리 끝내야 하므로 막히는 친구를 팀원이 도와준다.']]},
  check:['I like + 복수형(bananas)을 말하는가.','차례를 지키며 빠르게 이어 가는가.'],
  mats:[['dice',[['🍦','ice cream'],['🍌','bananas'],['🍎','apples'],['🎂','cake'],['🍕','pizza'],['🍗','chicken']]],['dice',null],['score','team']] },
"What's in the box? (Dice)": {
  ex:{set:'초3 모둠 · 장난감 주사위 · 상자', lines:[
    ['상황','학생이 전개도로 주사위를 직접 만든다.'],
    ['민수','(상자 안에 던지고 나온 면을 가리키며) What\'s in the box?'],
    ['서연','It\'s a ball!'],
    ['서연','(던진다) What\'s in the box?'],
    ['지호','It\'s a robot!'],
    ['결과','주사위의 사물을 판토마임으로 나타내게 할 수도 있다.']]},
  check:['What\'s in the box? 질문을 던진 학생이 하는가.','It\'s a + 장난감 이름.'],
  mats:[['dice',[['🚂','train'],['✈️','plane'],['🚗','car'],['🤖','robot'],['🧸','bear'],['🏐','ball']]],['dice',null]] },
'Snakes and Ladders': {
  ex:{set:'초4 2~4명 · 게임판 · 주사위', lines:[
    ['민수','(주사위 2) One, two. "Say 3 animals." Dog, cat, pig!'],
    ['T','OK, stay there.'],
    ['서연','(주사위 4) … number 4. Ladder! Up to 14!'],
    ['지호','(주사위 6 → 6칸) "Touch your nose." (코를 만진다)'],
    ['하은','(26에 도착) Oh no, snake! Down to 15.'],
    ['결과','과제 칸에서 영어로 말해야 머물 수 있다. 과제는 포스트잇으로 단원에 맞게 교체.']]},
  check:['칸의 과제를 영어로 수행하는가.','사다리·뱀 규칙(up/down)을 영어로 말하는가.'],
  mats:[['board','snakes']] },
'Coin Toss Game': {
  ex:{set:'초3 2~4명 · 놀이판 · 동전', lines:[
    ['민수','(동전) Head! Two steps. One, two.'],
    ['서연','Tail! One step.'],
    ['민수','Head! … Number 5. "Go back 1." Oh no!'],
    ['서연','Head! Two steps… Number 9. "Go ahead 2!" Yes!'],
    ['결과','학교(24번)에 먼저 도착하면 승리. 칸의 그림을 영어로 말하게 하면 어휘 연습이 추가된다.']]},
  check:['Head/Tail을 구분해 말하는가.','Go back / Go ahead + 수를 읽고 따르는가.'],
  mats:[['board','coin']] },
'Tic-Tac-Toe': {
  ex:{set:'초3 2팀 · 3×3 보드 · 질문 카드', lines:[
    ['T','Team Apple. (연필 카드) What\'s this?'],
    ['사과팀','It\'s a pencil!'],
    ['T','Right. Which number?'],
    ['사과팀','Number five! (가운데 ○)'],
    ['T','Team Star. How\'s the weather today?'],
    ['별팀','It\'s sunny!'],
    ['별팀','Number one! (×)'],
    ['결과','한 줄 3개를 먼저 만든 팀 승리. 전략 요소가 있어 고학년도 집중한다.']]},
  check:['질문에 완전한 문장으로 답하는가.','칸 번호를 영어로 말하는가.'],
  mats:[['board','ttt'],['cue',{title:'질문 카드 (교사용 · 단원에 맞게 교체)',lines:[["What's this? (그림카드)",'이게 뭐야?','❓'],["How's the weather today?",'오늘 날씨는?','🌤️'],['What day is it today?','오늘 무슨 요일?','📅'],['How old are you?','몇 살이야?','🎂'],['What time is it? (시계 카드)','몇 시야?','⏰'],['Do you like apples?','사과 좋아해?','🍎'],['Can you swim?','수영할 수 있어?','🏊'],["What's your name?",'이름이 뭐야?','🏷️']]}]] },
'Twenty Boxes Game': {
  ex:{set:'초3 짝 활동 · 20칸 게임판 2장', lines:[
    ['상황','민수가 몰래 4칸에 그림을 그린다.'],
    ['민수','Number seven, a cat.'],
    ['서연','(7번 칸에 고양이를 그린다) Number seven, a cat. OK.'],
    ['민수','Number twelve, an apple.'],
    ['민수','Number three, a red car.'],
    ['상황','다 그린 뒤 두 판을 나란히 놓고 비교.'],
    ['서연','Same! Same! … Different! I drew a blue car.'],
    ['결과','역할을 바꾸어 한 번 더. 색을 함께 말하게 하면 어려워진다.']]},
  check:['칸 번호 1~20을 영어로 말하는가.','a/an + 명사를 듣고 그리는가.'],
  mats:[['board','twenty'],['board','twenty'],['dialog',{title:'대화 카드 — Twenty Boxes',lines:[['A','Number seven, a cat.','7번 칸, 고양이.'],['B','Number seven, a cat. OK.','7번, 고양이. 알았어.'],['A','Number twelve, a red apple.','12번, 빨간 사과.'],['B','Again, please.','다시 말해 줘.']]}]] },
'Board Game (Islands)': {
  ex:{set:'초4 짝 활동 · 섬 지도 2장', lines:[
    ['상황','각자 섬 3곳에 그림을 그린다(짝에게 보이지 않게).'],
    ['민수','A cat is on island B2.'],
    ['서연','B2, a cat. (그린다) An apple is on island C1.'],
    ['민수','C1, an apple. A pencil is on island A3.'],
    ['상황','다 그린 뒤 지도를 비교.'],
    ['서연','Same! Three islands, all correct!'],
    ['결과','고학년은 north/south/east/west 방위로 말하게 하면 원본 취지에 가깝다.']]},
  check:['좌표(A1~C3)를 영어로 말하는가.','There is a ~ on island ~. 로 확장할 수 있는가.'],
  mats:[['board','islands'],['board','islands']] },
'Information Gap': {
  ex:{set:'초4 짝 활동 · 그림 A(장소만)·B(완성)', lines:[
    ['A(민수)','Where\'s the pencil?'],
    ['B(서연)','It\'s on the book.'],
    ['A','(책 위에 연필을 그린다) Where\'s the cat?'],
    ['B','It\'s under the chair.'],
    ['A','Where\'s the phone?'],
    ['B','It\'s on the table.'],
    ['A','Where\'s the dog?'],
    ['B','It\'s in the box.'],
    ['결과','다 그린 뒤 그림 B와 비교. 빠르고 정확하게 그린 짝이 승리.']]},
  check:['Where\'s the ~? / It\'s on/under/in the ~. 를 정확히 쓰는가.','그림을 보여 주지 않고 말로만 전달하는가.'],
  mats:[['scene','gapA'],['scene','gapB'],['preps']] },

// ───────── G ─────────
'Restaurant Role-play': {
  ex:{set:'초3 4그룹 · 음식 카드 · 메뉴판', lines:[
    ['상황','그룹 대표 서연이 주인. 음식 카드를 책상에 늘어놓는다.'],
    ['민수','(메뉴판을 가리키며) Pizza, please.'],
    ['서연','Here you are. (피자 카드를 건넨다)'],
    ['민수','Thank you.'],
    ['서연','You\'re welcome.'],
    ['지호','Chicken, please.'],
    ['서연','Here you are.'],
    ['결과','확장: "How much is it?" — "It\'s four thousand won." 가격 묻기까지.']]},
  check:['~, please. 로 공손하게 주문하는가.','Thank you → You\'re welcome 짝을 이루는가.'],
  mats:[['menu'],['cards',{cat:'Food'}],['roles',[['👩‍🍳','Owner','주인'],['🧑','Customer','손님']]],['dialog',{title:'대화 카드 — 식당에서',lines:[['손님','Pizza, please.','피자 주세요.'],['주인','Here you are.','여기 있어요.'],['손님','Thank you.','감사합니다.'],['주인',"You're welcome.",'천만에요.'],['손님','How much is it?','얼마예요?'],['주인',"It's four thousand won.",'4천 원이에요.']]}]] },
'Nice to meet you.': {
  ex:{set:'초3 10명 · 2팀 마주 보기 · 영어 이름표', lines:[
    ['A(민수)','Hi, I\'m Tom.'],
    ['B(서연)','Hi, I\'m Jenny. Nice to meet you.'],
    ['A','Nice to meet you, too.'],
    ['A·B','Good-bye! (각자 줄 맨 뒤로)'],
    ['상황','다음 두 사람이 마주 걸어 나온다.'],
    ['결과','영어 이름표를 목에 걸고 하면 이름을 바꿔 가며 반복할 수 있다.']]},
  check:['Nice to meet you. / Nice to meet you, too. 응답을 구분하는가.','악수·눈맞춤 등 인사 예절을 함께 하는가.'],
  mats:[['roles',[['🧒','Tom','톰'],['👧','Jenny','제니'],['🧒','Mike','마이크'],['👧','Mary','메리'],['🧒','Ben','벤'],['👧','Amy','에이미']]],['dialog',{title:'대화 카드 — Nice to meet you',lines:[['A',"Hi, I'm Tom.",'안녕, 나는 톰이야.'],['B',"Hi, I'm Jenny. Nice to meet you.",'안녕, 나는 제니야. 만나서 반가워.'],['A','Nice to meet you, too.','나도 만나서 반가워.'],['A+B','Good-bye!','잘 가!']]}]] },
'Greeting Groups': {
  ex:{set:'초3 4조(Mom·Dad·Min-ho·Mike) · 리듬 박수', lines:[
    ['T','(박수 2번) How are you, Mom?'],
    ['Mom조','Fine, thank you.'],
    ['Mom조 대표','(박수 2번) Good night, Mike.'],
    ['Mike조','Good night.'],
    ['Mike조 대표','Good afternoon, Dad.'],
    ['Dad조','Good afternoon.'],
    ['Dad조 대표','Hello, Min-ho!'],
    ['Min-ho조','Hello!'],
    ['결과','리듬(박수 2번 → 인사)을 유지하면 집중도가 올라간다. 박자를 놓친 조는 1점 감점.']]},
  check:['인사말과 응답을 짝지어 말하는가.','조 이름을 듣고 자기 조일 때만 반응하는가.'],
  mats:[['roles',[['👩','Mom','엄마조'],['👨','Dad','아빠조'],['🧒','Min-ho','민호조'],['🧒','Mike','마이크조']]],['dialog',{title:'인사 짝 카드',lines:[['Q','How are you?','어떻게 지내?'],['A','Fine, thank you.','잘 지내, 고마워.'],['Q','Good morning. / Good afternoon.','좋은 아침 / 좋은 오후'],['A','Good morning. / Good afternoon.','(같은 인사로 답)'],['Q','Good night.','잘 자.'],['A','Good night.','잘 자.'],['Q','Hello! / Hi!','안녕!'],['A','Hello! / Hi!','안녕!']]}]] },
"Doll's family": {
  ex:{set:'초3 분단 · 손가락 인형(가족 카드를 막대에 붙임)', lines:[
    ['민수','(아빠 인형) Hello, I\'m Dad.'],
    ['서연','(엄마 인형) Good morning, Dad.'],
    ['민수','Good morning, Mom. How are you?'],
    ['서연','Fine, thank you.'],
    ['지호','(동생 인형) Hi, Mom! Hi, Dad!'],
    ['민수·서연','Hi!'],
    ['모두','Good-bye!'],
    ['결과','가족 카드를 막대에 붙여 막대 인형으로 대신할 수 있다.']]},
  check:['가족 호칭(Mom, Dad, brother…)을 정확히 쓰는가.','상황에 맞는 인사를 고르는가.'],
  mats:[['cards',{cat:'Family'}],['dialog',{title:'인형극 대사 카드',lines:[['아빠',"Hello, I'm Dad.",'안녕, 나는 아빠야.'],['엄마','Good morning, Dad.','좋은 아침이에요, 여보.'],['아빠','Good morning, Mom. How are you?','좋은 아침. 어떻게 지내요?'],['엄마','Fine, thank you.','잘 지내요, 고마워요.'],['아이','Hi, Mom! Hi, Dad!','엄마, 아빠 안녕!'],['모두','Good-bye!','잘 가!']]}]] },
'Family Talk': {
  ex:{set:'초3 4분단 · 칠판 그림', lines:[
    ['상황','각 분단 한 명이 가족 한 사람을 칠판에 그리고 자리로.'],
    ['T','(민수의 그림을 가리키며)'],
    ['Ss','Who\'s he?'],
    ['민수','(일어나) He\'s my brother.'],
    ['Ss','(서연의 그림) Who\'s she?'],
    ['서연','She\'s my grandma.'],
    ['T','Seo-yeon, what\'s her name?'],
    ['서연','Her name is Kim Young-hee.'],
    ['결과','가족 사진을 가져오게 하면 실제성이 높아진다. 워크시트에 가족 그리기로 확장.']]},
  check:['he/she를 구분하는가.','He\'s my ~. / She\'s my ~. 로 답하는가.'],
  mats:[['worksheet','family'],['cards',{cat:'Family'}]] },
'Find Your Family': {
  ex:{set:'초3 10명 한 조 · 이름 쪽지', lines:[
    ['상황','쪽지를 하나씩 집는다. 민호에 ○가 된 쪽지를 지호가 가졌다.'],
    ['지호','I\'m Min-ho. What\'s your name?'],
    ['하은','I\'m Mary.'],
    ['지호','(외국 이름 → 가족 아님) Bye! … I\'m Min-ho. What\'s your name?'],
    ['도윤','I\'m Min-yeong!'],
    ['지호·도윤','We\'re family! (껴안고 자리에 앉는다)'],
    ['상황','한국 이름 5명이 먼저 모두 앉았다.'],
    ['T','Korean family wins! Now, introduce yourselves.'],
    ['Ss','I\'m Min-ho. I\'m Min-su. I\'m Min-hyeok …'],
    ['결과','가족을 찾는 것도 중요하지만 정확한 표현을 사용하도록 한다.']]},
  check:['I\'m ~. What\'s your name? 을 묶어 말하는가.','이름을 듣고 한국/외국 이름을 분류하는가.'],
  mats:[['slips','names'],['dialog',{title:'대화 카드 — 가족 찾기',lines:[['A',"I'm Min-ho. What's your name?",'나는 민호야. 네 이름은?'],['B',"I'm Mary.",'나는 메리야.'],['A','Bye!','안녕!'],['B',"I'm Min-yeong!",'나는 민영이야!'],['A+B',"We're family!",'우리는 가족이야!']]}]] },
'Find your partner': {
  ex:{set:'초4 짝 활동 · 질문 카드 3장', lines:[
    ['T','Question one: Do you like ~? Question two: Can you ~? Go!'],
    ['민수','Do you like fish?'],
    ['서연','Yes, I do. I like fish. Do you like swimming?'],
    ['민수','Yes, I do. I like swimming. Can you swim?'],
    ['서연','No, I can\'t. (사진을 보며) Who is he?'],
    ['민수','He\'s my brother.'],
    ['T','Change partners!'],
    ['결과','칠판에 질문 3개를 적어 두고 짝을 바꿔 가며 반복한다.']]},
  check:['질문에 맞는 대답 형태(do/can)를 고르는가.','대답 뒤에 되묻는가(And you?).'],
  mats:[['cue',{title:'짝 질문 카드',lines:[['Do you like fish?','생선 좋아해?','🐟'],['Do you like swimming?','수영 좋아해?','🏊'],['Can you swim?','수영할 수 있어?','💦'],['Can you ride a bike?','자전거 탈 수 있어?','🚲'],['Is this your pencil?','이거 네 연필이야?','✏️'],['Who is he / she?','이 사람은 누구야?','👨‍👩‍👧'],['What do you like?','뭐 좋아해?','❤️'],["How's the weather?",'날씨 어때?','🌤️']]}],['cards',{cat:'Sports'}]] },
"I'm hungry.": {
  ex:{set:'초3 분단 · 과일 카드 1장씩', lines:[
    ['T','I\'m hungry. I want an apple.'],
    ['민수','(사과 카드를 들며) Apple! I have an apple. Here you are.'],
    ['T','Thank you! Now, Min-su.'],
    ['민수','I\'m hungry. I want a banana.'],
    ['서연','I have a banana! Here you are.'],
    ['민수','Thank you.'],
    ['결과','카드를 건네며 Here you are / Thank you 를 덧붙이면 대화가 완성된다.']]},
  check:['I want a/an ~. 에서 관사를 맞게 쓰는가.','I have a ~. 로 응답하며 카드를 보여 주는가.'],
  mats:[['cards',{cat:'Fruits'}],['dialog',{title:'대화 카드 — I\'m hungry',lines:[['A',"I'm hungry. I want an apple.",'배고파. 사과 먹고 싶어.'],['B','I have an apple. Here you are.','나 사과 있어. 여기.'],['A','Thank you!','고마워!'],['B',"You're welcome.",'천만에.']]}]] },
'Bean bag Game': {
  ex:{set:'초4 10명 · 전체 · 콩주머니', lines:[
    ['T','(콩주머니를 던지며) What do you like?'],
    ['민수','I like bananas. (던지며) Can you swim?'],
    ['서연','Yes, I can. (던지며) What day is it today?'],
    ['지호','It\'s Monday. (던지며) How old are you?'],
    ['하은','I\'m ten. (던지며) How\'s the weather?'],
    ['도윤','It\'s… (막힘)'],
    ['T','Funny penalty! Animal dance!'],
    ['결과','질문 목록을 칠판에 적어 두면 저학년도 질문을 고를 수 있다.']]},
  check:['받자마자 답하고 새 질문을 하는가(2단계).','질문 종류를 다양하게 바꾸는가.'],
  mats:[['cue',{title:'콩주머니 질문 카드',lines:[['What do you like?','뭐 좋아해?','❤️'],['Can you swim?','수영할 수 있어?','🏊'],['What day is it today?','오늘 무슨 요일?','📅'],['How old are you?','몇 살이야?','🎂'],["How's the weather?",'날씨 어때?','🌤️'],["What's your name?",'이름이 뭐야?','🏷️'],['Do you like pizza?','피자 좋아해?','🍕'],['What time is it?','몇 시야?','⏰']]}]] },
'Musical Chairs Talk': {
  ex:{set:'초3 12명 · 의자 11개 · 음악', lines:[
    ['상황','음악이 흐르는 동안 의자 주위를 돌며 옆 친구와 대화.'],
    ['민수','Hi! How are you?'],
    ['서연','I\'m fine. Do you like music?'],
    ['민수','Yes, I do!'],
    ['T','(음악 멈춤)'],
    ['Ss','(의자에 앉는다. 지호가 못 앉음)'],
    ['T','Ji-ho, you are the judge now. Listen to their English!'],
    ['결과','빠진 학생에게 "대화 심판" 역할을 주어 끝까지 참여시킨다.']]},
  check:['음악 중 영어로 말하는가(한국어 사용 시 심판이 체크).','배운 표현을 돌아가며 다양하게 쓰는가.'],
  mats:[['cue',{title:'대화 시작 문장 카드 (의자 등받이에 붙이기)',lines:[['Hi! How are you?','안녕! 어떻게 지내?','👋'],['Do you like music?','음악 좋아해?','🎵'],["What's your name?",'이름이 뭐야?','🏷️'],['How old are you?','몇 살이야?','🎂'],['Can you dance?','춤출 수 있어?','💃'],['What do you like?','뭐 좋아해?','❤️'],["How's the weather?",'날씨 어때?','🌤️'],['Nice to meet you.','만나서 반가워.','🤝']]}]] },
'Sit-Stand Song Game': {
  ex:{set:'초3 2조 · 챈트', lines:[
    ['Ss','(챈트를 부르며 조마다 한 명씩 일어섰다 앉는다)'],
    ['상황','챈트가 끝났을 때 민수(1조)와 서연(2조)이 서 있다.'],
    ['민수·서연','Rock, scissors, paper!'],
    ['민수','(이김) I\'m sorry!'],
    ['서연','That\'s OK.'],
    ['T','Good! One point each team.'],
    ['상황','다음 판: 지호 "Thank you." — 하은 "You\'re welcome."'],
    ['결과','대화 쌍 3개를 칠판에 적어 두고 그중 하나를 골라 쓰게 한다.']]},
  check:['첫 말에 맞는 응답 쌍을 고르는가.','챈트 박자에 맞춰 앉고 서는가.'],
  mats:[['dialog',{title:'대화 짝 카드 (3쌍)',lines:[['A','Thank you.','고마워.'],['B',"You're welcome.",'천만에.'],['A',"I'm sorry. / Sorry, I'm late.",'미안해. / 늦어서 미안.'],['B',"That's OK.",'괜찮아.'],['A','Are you OK?','괜찮아?'],['B',"Yes, I'm OK.",'응, 괜찮아.']]}],['score','team']] },
'East Gate Game': {
  ex:{set:'초3 10명 한 조 · 노래', lines:[
    ['상황','민수·서연이 손을 맞잡아 아치를 만든다.'],
    ['Ss','(London Bridge를 부르며 차례로 아치를 지난다)'],
    ['상황','노래 끝. 아치가 내려와 지호가 갇힌다.'],
    ['민수','Good morning!'],
    ['지호','Good morning! How are you?'],
    ['민수','I\'m fine. Bye!'],
    ['지호','Bye! (풀려난다)'],
    ['상황','다음에 갇힌 하은이 인사를 못 하면 아치와 교대.'],
    ['결과','London Bridge is falling down 노래를 영어로 부르면 노래 학습도 된다.']]},
  check:['인사와 응답을 끊김 없이 주고받는가.','노래 가사를 따라 부르는가.'],
  mats:[['dialog',{title:'인사 카드 + 노래 가사',lines:[['아치','Hi! / Hello!','안녕!'],['갇힌 S','Hi! How are you?','안녕! 어떻게 지내?'],['아치','Good morning. / Good-bye.','좋은 아침. / 잘 가.'],['갇힌 S','Good morning. / Bye!','좋은 아침. / 안녕!'],['노래','London Bridge is falling down, falling down, falling down.','런던 다리가 무너져요'],['노래','London Bridge is falling down, my fair lady.','런던 다리가 무너져요, 아가씨']]}]] },
'Mimic Game': {
  ex:{set:'초5 4조(민호·민지·애니·조니) · 동작 카드', lines:[
    ['T','What\'s Min-ho doing?'],
    ['민호조 대표','(카드를 뽑고) He\'s singing!'],
    ['민호조','(모두 노래하는 흉내)'],
    ['T','What\'s Annie doing?'],
    ['애니조 대표','She\'s cooking!'],
    ['애니조','(프라이팬 흔드는 흉내)'],
    ['결과','동작 카드를 뽑아 대답하게 하면 어휘 범위가 통제된다. He/She 구분이 핵심.']]},
  check:['He\'s / She\'s + -ing 형태로 답하는가.','조원 전체가 동작을 함께 하는가.'],
  mats:[['cards',{cat:'Actions'}],['roles',[['🧒','Min-ho','민호조'],['👧','Min-ji','민지조'],['👧','Annie','애니조'],['🧒','Johnny','조니조']]],['dialog',{title:'대화 카드 — What\'s ~ doing?',lines:[['T',"What's Min-ho doing?",'민호는 뭐 하고 있어?'],['대표',"He's singing.",'노래하고 있어.'],['T',"What's Annie doing?",'애니는 뭐 하고 있어?'],['대표',"She's cooking.",'요리하고 있어.']]}]] },
'Animal dance': {
  ex:{set:'초3 분단 · 동물 카드', lines:[
    ['상황','서연이 카드 한 장을 뽑아 엎어 둔다(고양이).'],
    ['서연','(네 발로 기며) Meow~ Meow~'],
    ['Ss','It\'s a cat!'],
    ['서연','Yes! (카드를 보여 준다)'],
    ['민수','(카드를 뽑고 코를 길게 늘이는 시늉) Pawoo~'],
    ['Ss','It\'s an elephant!'],
    ['결과','Guess What?(몸짓만)과 달리 소리를 낼 수 있어 저학년에 적합하다.']]},
  check:['It\'s a/an + 동물. 로 답하는가.','동물 특징을 몸과 소리로 표현하는가.'],
  mats:[['cards',{cat:'Animals'}],['sounds',F.sounds]] },
'Scramble Game': {
  ex:{set:'초3 10명 · 원형 의자 9개 · 과일 카드 배정', lines:[
    ['상황','각자 과일 카드 1장씩 받는다. 민수 apple, 서연 banana.'],
    ['T','Apple, banana… Scramble!'],
    ['민수·서연','(일어나 서로의 자리로 달려가 앉는다)'],
    ['T','Seo-yeon is late! (의자를 하나 뺀다) Seo-yeon, you call.'],
    ['서연','(가운데 서서) Grapes, peach… Scramble!'],
    ['T','Fruit salad!'],
    ['Ss','(모두 자리를 바꾼다)'],
    ['결과','"Fruit salad!"(범주 외치기)로 전원 이동 규칙을 추가하면 흥미가 커진다.']]},
  check:['자기 낱말을 듣고 즉시 반응하는가.','가운데 선 학생이 낱말 두 개를 또렷이 부르는가.'],
  mats:[['cards',{cat:'Fruits'}],['cue',{title:'Scramble 외치기 카드',lines:[['Apple, banana… Scramble!','사과·바나나 자리 바꾸기','🍎'],['Grapes, peach… Scramble!','포도·복숭아','🍇'],['Orange, pear… Scramble!','오렌지·배','🍊'],['Fruit salad!','모두 자리 바꾸기!','🥗']]}]] },
};
