// 서술형 문항 데이터. 모든 영어 문장은 원문을 바탕으로 새로 쓴 재진술문(창작)이다.
// type: arr = <보기> 어구 배열 / form = 어형 변화 1단어 / find = 본문에서 찾아 쓰기
module.exports = [
  // ───────── 교과서 L1 ─────────
  { id:'l1p1', type:'form', kind:'어형 변화', text:'The two women went from home to home (collect) samples from the sick children by lamplight.', answer:'collecting', note:'분사구문(연속 동작)' },
  { id:'l1p2', type:'arr', kind:'재진술 배열', lead:'Although', tail:'in 1906, every vaccine developed over the next 20 years proved ineffective.', chunks:['the cause','of pertussis','had been','identified'], note:'과거완료 수동태(언어 형식 ①)' },
  { id:'l1p3', type:'arr', kind:'재진술 배열', lead:'Although funding was scarce,', tail:'.', chunks:['the hardships','they faced','never kept','them from','pursuing their goal'], note:'keep A from v-ing' },
  { id:'l1p4', type:'arr', kind:'재진술 배열', lead:'To make sure the vaccine was safe,', tail:'.', chunks:['they tested','it on themselves','before','any clinical trial'], note:'재귀대명사(재귀용법)' },
  { id:'l1p5', type:'arr', kind:'대화문 배열', lead:'A: How did they finally run a large-scale trial? — B: Thanks to the First Lady, the two scientists', tail:'.', chunks:['obtained','enough funds','to run','a large-scale trial'], note:'enough + 명사 + to-v' },
  { id:'l1p6', type:'find', kind:'본문에서 찾아 쓰기', text:'Soon after the vaccine was added to the list of recommended immunizations, there was a dramatic (d______) in whooping cough infections.', answer:'decline', note:'p.20' },
  { id:'l1p7', type:'arr', kind:'재진술 배열', lead:'Had they taken out a patent,', tail:', but they chose not to.', chunks:['the two','could have','made','a fortune'], note:'가정법 과거완료(if 생략 도치)' },
  // ───────── 교과서 L2 ─────────
  { id:'l2p1', type:'arr', kind:'재진술 배열', lead:'Contrary to common perception,', tail:'.', chunks:['ordinary people','are able','to contribute','to scientific progress'], note:'be able to-v' },
  { id:'l2p2', type:'form', kind:'어형 변화', text:'It took Schawinski a whole week (classify) just 50,000 galaxies.', answer:'to classify', note:'It takes A 시간 to-v' },
  { id:'l2p3', type:'form', kind:'어형 변화', text:'Lintott suggested that Schawinski (turn) to the Internet for help.', answer:'turn', note:'제안 동사 + that + S + (should) 동사원형 — turned ×' },
  { id:'l2p4', type:'arr', kind:'재진술 배열', lead:'Without the help of those participants,', tail:'to finish the job.', chunks:['it would','have taken','Schawinski','decades'], note:'Without = If it had not been for(언어 형식 ②)' },
  { id:'l2p5', type:'arr', kind:'재진술 배열', lead:'Not knowing what the lights were,', tail:'.', chunks:['the group','named','the phenomenon','after a movie scene'], note:'name A after B' },
  { id:'l2p6', type:'arr', kind:'재진술 배열', lead:'Experts agree that', tail:'for the discovery.', chunks:['it is','the aurora chasers','that deserve','the credit'], note:'It is ~ that 강조(언어 형식 ①), 복수 → deserve' },
  { id:'l2p7', type:'arr', kind:'재진술 배열', lead:'Even without a science degree,', tail:'.', chunks:['anyone','who is curious','can contribute','to science'], note:'주격 관계대명사' },
  // ───────── Booster 11 ─────────
  { id:'b111', type:'arr', kind:'재진술 배열', lead:'What researchers want to know is', tail:'.', chunks:['how','the two abilities','complement','each other'], note:'간접의문문 보어' },
  { id:'b112', type:'arr', kind:'재진술 배열', lead:'Intimacy fails to develop', tail:'.', chunks:['when','only one person','reveals','personal information'], note:'reveal = disclose' },
  { id:'b113', type:'arr', kind:'재진술 배열', lead:'Hotter summers', tail:'after a fire.', chunks:['make it','harder','for young spruce','to take root'], note:'가목적어 it + 의미상 주어' },
  { id:'b114', type:'arr', kind:'재진술 배열', lead:'Doctors', tail:', yet he lived for several more years.', chunks:['never expected','him','to survive','the accident'], note:'expect + O + to-v' },
  // ───────── Booster 12 ─────────
  { id:'b121', type:'arr', kind:'도치 배열', lead:'Only by boat or seaplane', tail:'.', chunks:['can','visitors','reach','the remote park'], note:'Only + 부사구 도치' },
  { id:'b122', type:'arr', kind:'재진술 배열', lead:'When threatened, the toad turns its body', tail:'.', chunks:['so that','the venom glands behind its eyes','directly face','the enemy'], note:'so that + S + V' },
  { id:'b123', type:'arr', kind:'재진술 배열', lead:'Her father’s belief in equality', tail:'.', chunks:['allowed her','to grow up','free from','traditional expectations'], note:'allow + O + to-v' },
  { id:'b124', type:'arr', kind:'재진술 배열', lead:'Because', tail:', steenboks seldom drink.', chunks:['they get','most of','the moisture they need','from their food'], note:'목적격 관계대명사 생략' },
  // ───────── Booster 14 ─────────
  { id:'b141', type:'arr', kind:'재진술 배열', lead:'Once content went digital,', tail:'.', chunks:['it','could be','delivered','in thousands of ways'], note:'조동사 수동태' },
  { id:'b142', type:'arr', kind:'재진술 배열', lead:'Sarcasm lets people', tail:'.', chunks:['express displeasure','without','being criticized','for it'], note:'동명사 수동형' },
  { id:'b143', type:'arr', kind:'재진술 배열', lead:'Rising demand for dairy in China', tail:'.', chunks:['could','cause','prices in other countries','to rise'], note:'cause + O + to-v, rise(자동사)' },
  { id:'b144', type:'arr', kind:'재진술 배열', lead:'To shrink demand, marketers may', tail:'.', chunks:['move','a product','to a shelf','where it is','less visible'], note:'관계부사 where' },
  // ───────── Booster 15 ─────────
  { id:'b151', type:'arr', kind:'재진술 배열 ★분석지 1순위', lead:'The host family felt insulted because', tail:'.', chunks:['knives stand for','ending a relationship','rather than','beginning one'], note:'부정대명사 one' },
  { id:'b152', type:'arr', kind:'재진술 배열', lead:'Sharks have survived', tail:'.', chunks:['because their brains','are','perfectly suited','to how they live'], note:'how + 완전한 절(what ×)' },
  { id:'b153', type:'arr', kind:'도치 전환 ★분석지 1순위', lead:'Not until 1500 BCE', tail:'.', chunks:['did','most of their food','come','from farming'], note:'It was not until A that B → Not until A + 도치' },
  { id:'b154', type:'arr', kind:'재진술 배열 ★분석지 1순위', lead:'The membrane acts as', tail:'.', chunks:['a gateway','through which','only selected molecules','can pass'], note:'전치사 + 관계대명사 + 완전한 절' },
  // ───────── 모의 ─────────
  { id:'m20', type:'arr', kind:'도치 배열', lead:'Only when you are satisfied with your story', tail:'.', chunks:['should','you show','it','to others'], note:'Only + 부사절 도치' },
  { id:'m21', type:'arr', kind:'재진술 배열', lead:'What seemed urgent last week', tail:'.', chunks:['is not','necessarily','the priority','now'], note:'What 주어절 + 단수 동사, 부분 부정' },
  { id:'m22', type:'arr', kind:'재진술 배열', lead:'Texting while eating can', tail:'.', chunks:['lead to','a misunderstood','message and','an upset stomach'], note:'과거분사 수식' },
  { id:'m23', type:'arr', kind:'재진술 배열', lead:'In a prelude,', tail:'.', chunks:['tension','is created','by the ambiguity','of the rhythm'], note:'수동태' },
  { id:'m24', type:'arr', kind:'재진술 배열', lead:'Attention literacy helps', tail:'.', chunks:['students','turn from','passive consumers','into critical users'], note:'help + O + (to) 동사원형' },
  { id:'m29', type:'arr', kind:'재진술 배열', lead:'In the end, inequality leads to crises', tail:'.', chunks:['of the kind','we have seen','cause','populist protests'], note:'지각동사 see + O + 동사원형' },
  { id:'m30', type:'arr', kind:'재진술 배열', lead:'People who feel eco-guilt', tail:'.', chunks:['seek','green actions','to make up for','their guilt'], note:'make up for = compensate for' },
  { id:'m31', type:'arr', kind:'재진술 배열 ★', lead:'The complexity of modern life', tail:'.', chunks:['makes it hard','for people','to settle down','permanently'], note:'가목적어 it + 의미상 주어' },
  { id:'m32', type:'arr', kind:'재진술 배열', lead:'Hotel residents feel uncertain because', tail:'.', chunks:['they are not','part of','a stable group','of neighbors'], note:'' },
  { id:'m33', type:'arr', kind:'재진술 배열', lead:'Grieving for what is lost', tail:'.', chunks:['clears the way','for','a stronger commitment','to what remains'], note:'관계대명사 what' },
  { id:'m34', type:'arr', kind:'재진술 배열 ★', lead:'The obvious convenience of the microwave', tail:'on family life.', chunks:['made it','easy','to overlook','its long-term effects'], note:'5형식 가목적어' },
  { id:'m35', type:'arr', kind:'재진술 배열', lead:'Sensor data', tail:'.', chunks:['can be used','to keep','the digital twin','continuously updated'], note:'be used to-v / keep + O + p.p.' },
  { id:'m36', type:'arr', kind:'도치 배열 ★', lead:'Not only', tail:', but they also anticipate their future needs.', chunks:['do','animals','seek out','the best locations'], note:'not only 도치' },
  { id:'m37', type:'arr', kind:'재진술 배열', lead:'Collectivist cultures require that', tail:'.', chunks:['speakers','limit','themselves','to indirect expressions'], note:'require that + S + (should) 동사원형' },
  { id:'m38', type:'arr', kind:'재진술 배열 ★', lead:'If someone is dreading an event, crowding', tail:'.', chunks:['will','make','the experience','even worse'], note:'make + O + 형용사(비교급 강조 even)' },
  { id:'m39', type:'arr', kind:'재진술 배열', lead:'Unaddressed exclusion', tail:'.', chunks:['has','a strongly negative','effect','on performance'], note:'have an effect on' },
  { id:'m40', type:'arr', kind:'재진술 배열 ★', lead:'', tail:'motivates us to do more good later.', chunks:['seeing','ourselves','as people','who do good'], note:'동명사 주어 → 단수 동사; 첫 글자 대문자' },
  { id:'m41', type:'arr', kind:'재진술 배열 ★', lead:'The way choices are presented', tail:'.', chunks:['can strongly','influence','the decisions','people make'], note:'목적격 관계대명사 생략' },
  // ───────── 마지막 쪽: 최우선 8문항 ─────────
  { id:'f1a', type:'arr', kind:'요약문 (A)', lead:'In 1932, two bacteriologists, Kendrick and Eldering, (A)', tail:'', chunks:['began','developing','a vaccine','for whooping cough'], note:'' },
  { id:'f1b', type:'arr', kind:'요약문 (B)', lead:'although (B)', tail:', and after large-scale trials their vaccine started (C) (distribute) nationwide in 1940.', chunks:['funding','was','extremely limited','due to','the Depression'], note:'' },
  { id:'f1c', type:'form', kind:'(C) 어형 변화', text:'(C) distribute', answer:'being distributed', note:'동명사의 수동형' },
  { id:'f2a', type:'arr', kind:'사례 적용 (A)', lead:'A birdwatching app asked ordinary users to (A)', tail:',', chunks:['upload','photos and','locations of','local birds'], note:'' },
  { id:'f2b', type:'arr', kind:'사례 적용 (B)', lead:'and the data they collected (B)', tail:'.', chunks:['allowed','scientists','to track','migration patterns'], note:'' },
  { id:'f3', type:'arr', kind:'재진술 (가정법)', lead:'Had it not been for the aurora chasers, STEVE', tail:'.', chunks:['might','have','remained','unnoticed'], note:'' },
  { id:'f4a', type:'arr', kind:'대화문 (A)', lead:'A: Why did the two scientists refuse to patent their vaccine? — B: They said it (A)', tail:'.', chunks:['had not been','created','by them alone','but with','the help of others'], note:'' },
  { id:'f4b', type:'arr', kind:'대화문 (B)', lead:'A: Then what was their reward? — B: Simply (B)', tail:'.', chunks:['knowing','that','many lives','were being saved'], note:'' },
  { id:'f5', type:'find', kind:'본문에서 찾아 쓰기', text:'Kendrick and Eldering faced a severe lack of (A) f______ for their research, and before the first field test they confirmed that the vaccine had no negative (B) s___ e______. / Galaxy Zoo was a (C) c__________ online project, and visitors were asked to click buttons that described the (D) f_______ of each galaxy.', answer:'(A) funding (B) side effects (C) crowdsourced (D) features', note:'' },
  { id:'f6', type:'arr', kind:'도치 전환', lead:'Not until 1500 BCE (A)', tail:'.', chunks:['did','most of','their food','come','from farming'], note:'' },
  { id:'f7', type:'arr', kind:'빈칸 배열', lead:'The short-term convenience of the microwave (A)', tail:'.', chunks:['made it','easy','to overlook','the long-term implications'], note:'' },
  { id:'f8', type:'arr', kind:'빈칸 배열', lead:'Many studies have shown that not only (A)', tail:', but that they can anticipate their future needs.', chunks:['do','animals','have','a remarkable ability','to find the best locations'], note:'' },
];
